/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f615844d4ff671202effa60ea9513743)
interface __BaseEnv_Env {
	PORTAL_REQUESTS: RateLimit;
	ASSETS: Fetcher;
	JV_PUBLIC_ENDPOINT: "https://yhneskzvmtcmbsknidlt.supabase.co/functions/v1/title-jv-public";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JV_PUBLIC_ENDPOINT">> {}
}
