import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const built=await build({stdin:{contents:"export * from './lib/title/agency-setup';export * from './lib/title/agency-maintenance';export {captureCommands} from './lib/title/command-log';export {validateBusinessMutation} from './lib/title/business';export {businessDay} from './lib/title/business-date';export {emptyWorkspace,executeCommands,projectWorkspace} from './lib/backend/workspace';export {saveCompanyUnderwriters} from './lib/title/business';",resolveDir:fileURLToPath(new URL('../',import.meta.url))},bundle:true,write:false,format:'esm',platform:'node'});
const lib=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text+'\n//# sourceURL=agency-phase-one-test-bundle.mjs').toString('base64')}`);
const {configureAgencySetup,syncAgencySetup,agencySetupReadiness,defaultAgencySetupTemplate,saveAgencySetupTemplate,updateAgencyTask,activateAgencyCompany,validateAgencySetup,validateAgencyMaintenance,saveAgencyMaintenance,syncAgencyMaintenance,completeAgencyMaintenance,suggestedAgencyMaintenance,nextMaintenanceDate,upcomingMaintenance,saveAgencyMaintenanceNotifications,captureCommands,validateBusinessMutation,businessDay}=lib;
const state=(states=['NC'],writers=['WFG'])=>({version:1,user:'Test operator',companies:[{id:'c1',name:'Test Title',initials:'TT',color:'blue',contact:'',email:'',location:'',jurisdiction:states[0],operatingStates:states,stage:'Onboarding',steps:Array(7).fill(false),members:[{id:'member1',name:'Test owner',share:100}]}],documents:[],tasks:[],orders:[],inbox:[],activity:[],rules:[],revisions:[],fieldRevisions:[],replyDrafts:[],importTemplates:[],approvedReports:[],expenses:{},expansionStates:[],business:{onboarding:[{companyId:'c1',requiredUnderwriters:writers,evidence:[{step:2,reference:'Retained legacy EIN evidence'}],applicationStatus:'Not started',launchedAt:''}],policies:[],commitments:[],cpls:[],credentials:[],closes:[],handoffs:[],corrections:[],followups:[]}});
const configure=(s,kind='individual',count=1)=>configureAgencySetup(s,{companyId:'c1',expectedVersion:s.companies[0].agencySetup?.version||0,templateVersion:1,owners:[{memberId:'member1',kind}],agreementCount:count,eoCovered:true});
const original=(id,category,companyId='c1',visibility='Restricted')=>({id,companyId,name:id+'.pdf',category,visibility,assetId:'asset-'+id,version:1,date:businessDay(),size:'1 KB'});
const update=(s,t,patch={})=>updateAgencyTask(s,{taskId:t.id,expectedRevision:t.phaseOne.revision,status:'Complete',due:t.due,completedOn:businessDay(),...(t.phaseOne.itemId==='license-approved'?{effectiveOn:businessDay()}:{}),notes:'Verified fixture',documentIds:t.documentIds||[],owner:t.owner,...patch});
function structuredProfile(s){s.companies[0].email='orders@example.test';s.companies[0].desk={logoDocumentId:'',folders:[],renewals:[],domain:'company.example.test',website:'https://company.example.test',emails:[{id:'email1',label:'Primary',address:'orders@example.test',primary:true}]};}
function finish(s){structuredProfile(s);for(const r of suggestedAgencyMaintenance(s,'c1').filter(r=>r.kind.endsWith('agency license')))saveAgencyMaintenance(s,{expectedRevision:0,record:r});for(const t of s.tasks.filter(t=>t.phaseOne?.required&&t.phaseOne.applicable)){const requirement=t.phaseOne.documentRequirement;const ids=[];for(let n=0;n<(requirement?.minimum||0);n++){const doc=original(`${t.id}-original-${n}`,requirement.categories[0]);s.documents.push(doc);ids.push(doc.id);}update(s,t,{documentIds:ids});}}
const renewal=(s,kind='Domain')=>suggestedAgencyMaintenance(s,'c1').find(r=>r.kind===kind);
const saveRenewal=(s,record)=>saveAgencyMaintenance(s,{expectedRevision:0,record});

test('NC/SC state, every underwriter, and individual/existing/new owner choices generate only applicable shared tasks',()=>{
 for(const states of [['NC'],['SC'],['NC','SC']])for(const kind of ['individual','existing','new']){const s=state(states,['WFG','Commonwealth','First American']);configure(s,kind);assert.equal(s.tasks.filter(t=>t.phaseOne.itemId==='license-original').length,states.length);assert.deepEqual(s.tasks.filter(t=>t.phaseOne.itemId==='underwriter-original').map(t=>t.phaseOne.subject),['WFG','Commonwealth','First American']);assert.equal(s.tasks.filter(t=>t.phaseOne.itemId==='owner-private').length,kind==='individual'?1:0);assert.equal(s.tasks.filter(t=>t.phaseOne.itemId==='owner-llc-authorization').length,kind==='new'?1:0);assert.equal(s.tasks.filter(t=>t.phaseOne.itemId==='owner-status').length,kind==='existing'?1:0);validateAgencySetup(s);}
});
test('stored Restricted application completes legacy collection task without OCR or review and preserves evidence/Active import',()=>{
 const s=state();s.companies[0].operatingStatus={status:'Active',confirmedBy:'owner@example.test',confirmedAt:'2026-10-05T12:00:00.000Z',note:'Existing active business'};s.tasks=[{id:'collect-existing',title:'Collect onboarding application',companyId:'c1',scope:'agency',owner:'John',due:'',done:false,priority:'Normal'}];s.documents.push(original('stored-app','Applications'));const legacy=structuredClone(s.business);configure(s);const t=s.tasks.find(t=>t.phaseOne.itemId==='application-original');assert.equal(t.id,'collect-existing');assert.equal(t.done,true);assert.deepEqual(t.documentIds,['stored-app']);assert.deepEqual(s.business,legacy);assert.equal(s.companies[0].operatingStatus.status,'Active');const snapshot=structuredClone(s);syncAgencySetup(s,'c1');assert.deepEqual(s,snapshot);
});
test('application completion rejects wrong-company, missing bytes, archived, partner and wrong-category sources',()=>{
 for(const patch of [{companyId:'other'},{assetId:''},{archivedAt:'2026-10-05T00:00:00.000Z'},{visibility:'Partner'},{visibility:'Internal'},{category:'Agreements'},{orderId:'order-1'}]){const s=state();s.documents.push({...original('bad','Applications'),...patch});configure(s);assert.equal(s.tasks.find(t=>t.phaseOne.itemId==='application-original').done,false);}
});
test('required original completion enforces valid references and one or two governing agreements',()=>{
 const s=state();configure(s,'individual',2);const task=s.tasks.find(t=>t.phaseOne.itemId==='agreements-original');s.documents.push(original('one','Agreements'),original('two','Agreements'),original('foreign','Agreements','other'),original('internal','Agreements','c1','Internal'));for(const ids of [[],['one'],['one','foreign'],['one','internal'],['one','one']])assert.throws(()=>update(s,task,{documentIds:ids}));update(s,task,{documentIds:['one','two']});assert.equal(task.status,'Complete');assert.ok(task.completedOn);assert.throws(()=>updateAgencyTask(s,{taskId:task.id,expectedRevision:1,status:'Not Started',due:'',completedOn:'',notes:'',documentIds:[],owner:''}),/changed/);
});
test('optional business cards and delayed QuickBooks do not block activation; direct stage edits cannot bypass explicit activation',()=>{
 const s=state();configure(s);const before=structuredClone(s);finish(s);assert.equal(agencySetupReadiness(s,'c1').ready,true);assert.equal(s.tasks.find(t=>t.phaseOne.itemId==='cards').done,false);assert.equal(s.tasks.find(t=>t.phaseOne.itemId==='quickbooks').done,false);const forged=structuredClone(s);forged.companies[0].stage='Active';assert.throws(()=>validateBusinessMutation(before,forged),/launch review/);activateAgencyCompany(s,{companyId:'c1',expectedVersion:1});assert.equal(s.companies[0].stage,'Active');assert.doesNotThrow(()=>validateBusinessMutation(before,s));assert.deepEqual(s.companies[0].steps,Array(7).fill(false));
});
test('saved domain, primary email and website must substantiate completion; clearing fields invalidates readiness',()=>{
 const s=state();configure(s);
 for(const itemId of ['domain','primary-email','website'])assert.throws(()=>update(s,s.tasks.find(t=>t.phaseOne.itemId===itemId)),/Save/);
 structuredProfile(s);for(const itemId of ['domain','primary-email','website'])update(s,s.tasks.find(t=>t.phaseOne.itemId===itemId));
 s.companies[0].desk.domain='';s.companies[0].desk.emails=[];s.companies[0].desk.website='';syncAgencySetup(s,'c1');
 for(const itemId of ['domain','primary-email','website'])assert.equal(s.tasks.find(t=>t.phaseOne.itemId===itemId).done,false);
 assert.equal(agencySetupReadiness(s,'c1').ready,false);s.companies[0].desk.websiteNotNeeded=true;syncAgencySetup(s,'c1');assert.equal(s.tasks.find(t=>t.phaseOne.itemId==='website').phaseOne.applicable,false);
 const bad=state();configure(bad);structuredProfile(bad);bad.companies[0].desk.domain='https://example.test/path';assert.throws(()=>update(bad,bad.tasks.find(t=>t.phaseOne.itemId==='domain')),/domain/);bad.companies[0].desk.emails[0].address='not-an-email';assert.throws(()=>update(bad,bad.tasks.find(t=>t.phaseOne.itemId==='primary-email')),/primary company email/);bad.companies[0].desk.website='javascript:alert(1)';assert.throws(()=>update(bad,bad.tasks.find(t=>t.phaseOne.itemId==='website')),/website URL/);
});
test('configuration changes retain completed work/history while retiring no-longer-applicable tasks',()=>{
 const s=state(['NC','SC']);configure(s);const t=s.tasks.find(t=>t.phaseOne.itemId==='welcome-sent');update(s,t);const id=t.id,revision=t.phaseOne.revision;s.companies[0].operatingStates=['NC'];assert.equal(agencySetupReadiness(s,'c1').ready,false);syncAgencySetup(s,'c1');assert.equal(s.tasks.find(t=>t.id===id).done,true);assert.equal(s.tasks.find(t=>t.id===id).phaseOne.revision,revision);assert.equal(s.tasks.filter(t=>t.phaseOne.subject==='SC'&&t.phaseOne.applicable).length,0);assert.ok(s.tasks.some(t=>t.phaseOne.subject==='SC'));validateAgencySetup(s);
});
test('administrator template revisions are immutable versions, conditional and bounded',()=>{
 const s=state();configure(s);const template=defaultAgencySetupTemplate();const next=[...template.items,{id:'extra',title:'Optional custom handoff',group:'Setup',condition:'state',required:false}];saveAgencySetupTemplate(s,{expectedVersion:1,name:'Updated checklist',items:next});assert.equal(s.agencySetupTemplates.length,2);assert.equal(s.companies[0].agencySetup.templateVersion,1);configureAgencySetup(s,{companyId:'c1',expectedVersion:1,templateVersion:2,owners:[{memberId:'member1',kind:'individual'}],agreementCount:1,eoCovered:true});assert.ok(s.tasks.some(t=>t.phaseOne.itemId==='extra'));assert.throws(()=>saveAgencySetupTemplate(s,{expectedVersion:1,name:'stale',items:next}),/changed/);assert.throws(()=>saveAgencySetupTemplate(s,{expectedVersion:2,name:'Invalid',items:[...next,next[0]]}),/unique/);assert.throws(()=>configureAgencySetup(s,{companyId:'c1',expectedVersion:2,templateVersion:2,owners:[{memberId:'wrong',kind:'new'}],agreementCount:1,eoCovered:false}));
});
test('maintenance keeps company/entity/agency identities separate and seeds one E&O and credential only',()=>{
 const s=state(['NC','SC']);configure(s,'existing');const suggestions=suggestedAgencyMaintenance(s);assert.equal(suggestions.filter(r=>r.scope==='agency'&&r.kind==='Agency credential').length,1);assert.equal(suggestions.filter(r=>r.scope==='agency'&&r.kind==='Agency E&O').length,1);assert.equal(suggestions.filter(r=>r.scope==='entity').length,2);assert.ok(suggestions.some(r=>r.scope==='company'&&r.kind==='Annual report'));for(const r of suggestions)saveRenewal(s,r);assert.equal(suggestedAgencyMaintenance(s).length,0);assert.throws(()=>saveRenewal(s,{...suggestions[0],id:'duplicate-id'}),/already tracked/);validateAgencyMaintenance(s);
});
test('verified NC April 1 and SC even-year January replace approval anniversaries, multi-year service terms and leap dates roll forward',()=>{
 const s=state(['NC','SC']);const suggestions=suggestedAgencyMaintenance(s,'c1','2026-10-06'),nc=suggestions.find(r=>r.kind==='NC agency license'),sc=suggestions.find(r=>r.kind==='SC agency license');assert.equal(nc.nextDueOn,'2027-04-01');assert.equal(sc.nextDueOn,'2028-01-01');assert.equal(nextMaintenanceDate(sc),'2030-01-01');assert.equal(nextMaintenanceDate({nextDueOn:'2028-02-29',intervalYears:1,schedule:'anniversary'}),'2029-02-28');assert.equal(nextMaintenanceDate({nextDueOn:'2026-05-18',intervalYears:3,schedule:'anniversary'}),'2029-05-18');assert.throws(()=>saveRenewal(s,{...nc,nextDueOn:'2027-07-10'}),/verified renewal/);assert.throws(()=>saveRenewal(s,{...sc,nextDueOn:'2027-01-01'}),/verified renewal/);
});
test('14-day window is inclusive, overdue stays visible, paused records do not create tasks, duplicate sync is idempotent',()=>{
 const s=state(),record=renewal(s);record.nextDueOn='2026-10-20';saveRenewal(s,record);syncAgencyMaintenance(s,'2026-10-05','c1');assert.equal(s.tasks.length,0);syncAgencyMaintenance(s,'2026-10-06','c1');assert.equal(s.tasks.length,1);const first=structuredClone(s.tasks);syncAgencyMaintenance(s,'2026-10-07','c1');assert.deepEqual(s.tasks,first);assert.equal(upcomingMaintenance(s,'2026-11-01')[0].overdue,true);saveAgencyMaintenance(s,{expectedRevision:1,record:{...s.agencyMaintenance.records[0],revision:2,active:false}});assert.equal(upcomingMaintenance(s,'2026-11-01').length,0);assert.equal(s.tasks[0].phaseOne.applicable,false);
});
test('completion rolls from scheduled cycle, retains history, rejects stale replay and cannot be completed through generic task command',()=>{
 const s=state(),record=renewal(s);record.nextDueOn=businessDay();record.intervalYears=2;saveRenewal(s,record);syncAgencyMaintenance(s,businessDay(),'c1');const task=s.tasks[0];assert.throws(()=>update(s,task),/maintenance record/);update(s,task,{status:'In Progress',completedOn:''});const input={maintenanceId:record.id,expectedRevision:s.agencyMaintenance.records.find(r=>r.id===record.id).revision,cycleOn:record.nextDueOn,completedOn:businessDay(),notes:'Renewed fixture',documentIds:[],nextDueOn:nextMaintenanceDate(record)};completeAgencyMaintenance(s,input);assert.equal(s.tasks[0].done,true);assert.equal(s.agencyMaintenance.history.length,1);assert.equal(s.agencyMaintenance.records[0].nextDueOn,input.nextDueOn);assert.throws(()=>completeAgencyMaintenance(s,input),/changed/);syncAgencyMaintenance(s,input.nextDueOn,'c1');assert.equal(s.tasks.length,2);assert.equal(s.tasks[0].done,true);validateAgencyMaintenance(s);validateAgencySetup(s);
});
test('rescheduling retires old pending cycle without deleting task history; company-scoped sync cannot generate agency work',()=>{
 const s=state(),record=renewal(s);record.nextDueOn='2026-10-06';saveRenewal(s,record);const agency=suggestedAgencyMaintenance(s).find(r=>r.kind==='Agency credential');agency.nextDueOn='2026-10-06';saveRenewal(s,agency);syncAgencyMaintenance(s,'2026-10-06','c1');assert.equal(s.tasks.length,1);saveAgencyMaintenance(s,{expectedRevision:1,record:{...record,revision:2,nextDueOn:'2026-10-07'}});syncAgencyMaintenance(s,'2026-10-06','c1');assert.equal(s.tasks.length,2);assert.equal(s.tasks[0].phaseOne.applicable,false);syncAgencyMaintenance(s,'2026-10-06');assert.equal(s.tasks.length,3);
});
test('entity good-standing completion requires current Restricted evidence and records delinquency independently',()=>{
 const s=state();configure(s,'existing');const r=suggestedAgencyMaintenance(s).find(r=>r.scope==='entity'&&r.kind==='Good standing');r.nextDueOn=businessDay();r.standing='Delinquent';saveRenewal(s,r);syncAgencyMaintenance(s,businessDay(),'c1');const input={maintenanceId:r.id,expectedRevision:1,cycleOn:r.nextDueOn,completedOn:businessDay(),notes:'Status checked',documentIds:[],nextDueOn:nextMaintenanceDate(r)};assert.throws(()=>completeAgencyMaintenance(s,input),/required original/);s.documents.push(original('standing','Formation'));completeAgencyMaintenance(s,{...input,documentIds:['standing']});assert.equal(s.agencyMaintenance.records.find(x=>x.id===r.id).standing,'Current');assert.deepEqual(s.agencyMaintenance.history[0].documentIds,['standing']);
});
test('all supported changes emit explicit replayable commands and reminders require a saved address and explicit enable',()=>{
 const s=state();let commands=captureCommands(s,d=>configure(d));assert.deepEqual(commands.map(c=>c.name),['configureAgencySetup']);commands=captureCommands(s,d=>saveAgencyMaintenanceNotifications(d,{expected:{enabled:false,recipient:'',leadDays:14},enabled:true,recipient:'agency@example.test'}));assert.deepEqual(commands.map(c=>c.name),['saveAgencyMaintenanceNotifications']);assert.equal(s.agencyMaintenance.notifications.enabled,true);assert.throws(()=>saveAgencyMaintenanceNotifications(state(),{expected:{enabled:false,recipient:'',leadDays:14},enabled:true,recipient:''}));assert.throws(()=>saveAgencyMaintenanceNotifications(s,{expected:{enabled:false,recipient:'',leadDays:14},enabled:false,recipient:''}),/changed/);
});
const actor={userId:'test-owner',email:'owner@example.test',role:'owner',allCompanies:true,companyIds:[],restricted:true,version:1,partnerMembers:[]};
function serverState(){const s=lib.emptyWorkspace();s.companies=state().companies;structuredProfile(s);lib.saveCompanyUnderwriters(s,{companyId:'c1',names:['WFG'],expected:[]});return s;}
function replay(before,mutate,access=actor){const after=structuredClone(before);const commands=captureCommands(after,mutate);return lib.executeCommands(before,commands,access);}
test('server command replay creates setup and maintenance, protects direct edits and scoped/global boundaries',()=>{
 let s=serverState();s=replay(s,d=>configure(d));assert.ok(s.companies[0].agencySetup);assert.equal(s.tasks.length,defaultAgencySetupTemplate().items.filter(i=>!['new','existing'].includes(i.condition)).length);
 assert.throws(()=>replay(s,d=>{d.tasks[0].done=true;}),/reviewed task actions|complete|status/i);
 const task=s.tasks.find(t=>t.phaseOne.itemId==='welcome-sent');s=replay(s,d=>update(d,d.tasks.find(t=>t.id===task.id)));assert.equal(s.tasks.find(t=>t.id===task.id).done,true);
 assert.throws(()=>replay(s,d=>configure(d),{...actor,role:'onboarding',allCompanies:false,companyIds:['other']}));
 const record=renewal(s);record.nextDueOn=businessDay();s=replay(s,d=>saveRenewal(d,record));s=replay(s,d=>syncAgencyMaintenance(d,businessDay(),'c1'),{...actor,role:'onboarding',allCompanies:false,companyIds:['c1']});assert.ok(s.tasks.some(t=>t.phaseOne?.maintenanceId===record.id));
 assert.throws(()=>replay(s,d=>syncAgencyMaintenance(d,businessDay()),{...actor,role:'onboarding',allCompanies:false,companyIds:['c1']}),/administrator|outside|access/i);
 assert.throws(()=>replay(s,d=>saveAgencySetupTemplate(d,{expectedVersion:1,name:'Unauthorized',items:defaultAgencySetupTemplate().items}),{...actor,role:'onboarding',allCompanies:true}));
 assert.equal(lib.projectWorkspace(s,{...actor,role:'operations'}).companies[0].agencySetup,undefined);assert.equal(lib.projectWorkspace(s,{...actor,role:'operations'}).agencyMaintenance,undefined);
});
test('server accepts explicit Phase One activation after replay and automatically reconciles application uploads without review',()=>{
 let s=serverState();s=replay(s,d=>configure(d));const app=original('replayed-app','Applications');s=replay(s,d=>{d.documents.push(app);});assert.equal(s.tasks.find(t=>t.phaseOne.itemId==='application-original').done,true);assert.equal(s.business.onboarding[0].applicationStatus,'Not started');
 // Sources are pre-existing immutable uploads; completion commands explicitly link them.
 for(const t of s.tasks.filter(t=>t.phaseOne.required&&!t.done)){for(let i=0;i<(t.phaseOne.documentRequirement?.minimum||0);i++)s.documents.push(original(`${t.id}-server-source-${i}`,t.phaseOne.documentRequirement.categories[0]));}
 s=replay(s,d=>{for(const r of suggestedAgencyMaintenance(d,'c1').filter(r=>r.kind.endsWith('agency license')))saveAgencyMaintenance(d,{expectedRevision:0,record:r});for(const t of d.tasks.filter(t=>t.phaseOne.required&&!t.done))update(d,t,{documentIds:d.documents.filter(doc=>doc.id.startsWith(t.id+'-server-source')).map(doc=>doc.id)});});
 assert.equal(agencySetupReadiness(s,'c1').ready,true);s=replay(s,d=>activateAgencyCompany(d,{companyId:'c1',expectedVersion:d.companies[0].agencySetup.version}));assert.equal(s.companies[0].stage,'Active');assert.equal(s.business.onboarding[0].launchedAt,'');
});
test('persisted JSON key ordering does not change setup revisions and forged requirement metadata is rejected',()=>{
 const s=state();configure(s);const revisions=s.tasks.map(t=>t.phaseOne.revision);for(const task of s.tasks){task.phaseOne=Object.fromEntries(Object.entries(task.phaseOne).reverse());if(task.phaseOne.documentRequirement)task.phaseOne.documentRequirement=Object.fromEntries(Object.entries(task.phaseOne.documentRequirement).reverse());}validateAgencySetup(s);syncAgencySetup(s,'c1');assert.deepEqual(s.tasks.map(t=>t.phaseOne.revision),revisions);s.tasks.find(t=>t.phaseOne.itemId==='license-original').phaseOne.required=false;assert.throws(()=>validateAgencySetup(s),/requirements must match/);
});
test('maintenance can complete successive historical cycles once each and rejects an outdated open completion after work changes',()=>{
 const s=state(),r=renewal(s);r.nextDueOn='2024-01-01';saveRenewal(s,r);syncAgencyMaintenance(s,businessDay(),'c1');completeAgencyMaintenance(s,{maintenanceId:r.id,expectedRevision:1,cycleOn:'2024-01-01',completedOn:'2024-01-01',notes:'Historical cycle one',documentIds:[],nextDueOn:'2025-01-01'});syncAgencyMaintenance(s,businessDay(),'c1');const pending=s.tasks.find(t=>!t.done),stale={maintenanceId:r.id,expectedRevision:2,cycleOn:'2025-01-01',completedOn:'2025-01-01',notes:'Historical cycle two',documentIds:[],nextDueOn:'2027-01-01'};update(s,pending,{status:'In Progress',completedOn:''});assert.throws(()=>completeAgencyMaintenance(s,stale),/changed/);completeAgencyMaintenance(s,{...stale,expectedRevision:3});assert.equal(s.agencyMaintenance.history.length,2);assert.equal(s.tasks.filter(t=>t.done).length,2);assert.throws(()=>saveAgencyMaintenance(s,{expectedRevision:4,record:{...s.agencyMaintenance.records[0],revision:5,nextDueOn:'2024-01-01'}}),/already complete/);validateAgencyMaintenance(s);
});
test('new-company creation and conditional checklist commands preserve deterministic task IDs through server replay',()=>{
 const before=lib.emptyWorkspace(),client=structuredClone(before);const commands=captureCommands(client,d=>{const company=state(['NC','SC'],['WFG','Commonwealth']).companies[0];company.members=[];d.companies.push(company);lib.saveCompanyUnderwriters(d,{companyId:'c1',names:['WFG','Commonwealth'],expected:[]});configureAgencySetup(d,{companyId:'c1',expectedVersion:0,templateVersion:1,owners:[],agreementCount:1,eoCovered:false});});let result=lib.executeCommands(before,commands,actor);assert.deepEqual(result.tasks.map(t=>[t.id,t.title]),client.tasks.map(t=>[t.id,t.title]));assert.equal(result.tasks.filter(t=>t.phaseOne.itemId==='license-original').length,2);assert.equal(result.tasks.filter(t=>t.phaseOne.itemId==='underwriter-original').length,2);result=replay(result,d=>{d.companies[0].members=state().companies[0].members;configure(d,'new',2);});assert.equal(result.companies[0].agencySetup.owners[0].kind,'new');assert.ok(result.tasks.some(t=>t.phaseOne?.itemId==='owner-llc-authorization'));
});
