import test,{before,after,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const web=fileURLToPath(new URL('../',import.meta.url));let server,browser,context,page,origin;let errors=[];
before(async()=>{
 const bundle=await build({absWorkingDir:web,outfile:'phase-one-ui.mjs',write:false,bundle:true,platform:'browser',format:'esm',jsx:'automatic',logLevel:'silent',define:{'process.env.NODE_ENV':'"production"','process.env.NEXT_PUBLIC_SUPABASE_URL':'""','process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY':'""','process.env.NEXT_PUBLIC_TITLE_HOSTED_PILOT':'""'},stdin:{resolveDir:web,loader:'tsx',contents:`
 import React from 'react';import {createRoot} from 'react-dom/client';import {AgencySetup} from './components/title/agency-setup';import {AgencyMaintenance} from './components/title/agency-maintenance';import {Tasks} from './components/title/operations';import {useWorkspace} from '@/lib/title/store';
 function App(){const {s}=useWorkspace();const q=new URLSearchParams(location.search);return <>{q.has('tasks')?<Tasks scope="agency"/>:q.has('maintenance')?<AgencyMaintenance/>:<AgencySetup company={s.companies[0]}/>}<span id="ready"/></>};createRoot(document.getElementById('root')).render(<App/>);`},plugins:[{name:'fixture',setup(builder){builder.onResolve({filter:/^@\/lib\/title\/store$/},()=>({path:'workspace',namespace:'fixture'}));builder.onResolve({filter:/^@\/lib\/backend\/client$/},()=>({path:'client',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({loader:'tsx',resolveDir:web,contents:args.path==='client'?`
 export const activeWorkspace=()=> 'fixture';export async function backendRequest(path){if(path!=='/staff/assignable')throw Error('Unexpected API');return {staff:[{userId:'11111111-1111-4111-8111-111111111111',email:'operator@example.test',label:'Test operator'}],unavailable:0};}`:`
 import {useSyncExternalStore} from 'react';import {createSeed} from './lib/title/model';import {configureAgencySetup} from './lib/title/agency-setup';import {suggestedAgencyMaintenance,saveAgencyMaintenance,syncAgencyMaintenance} from './lib/title/agency-maintenance';import {businessDay} from './lib/title/business-date';
 const q=new URLSearchParams(location.search),listeners=new Set(),s=createSeed();s.companies=[{id:'c1',name:'Fictional Title',initials:'FT',color:'blue',contact:'',email:'',location:'',jurisdiction:'NC',operatingStates:['NC','SC'],stage:'Onboarding',steps:Array(7).fill(false),members:[{id:'m1',name:'Fictional Owner LLC',share:100}]}];s.orders=[];s.tasks=[];s.documents=[{id:'application',companyId:'c1',name:'Application original.pdf',category:'Applications',visibility:'Restricted',assetId:'A1',date:businessDay(),version:1,size:'1 KB'},{id:'license',companyId:'c1',name:'NC license original.pdf',category:'Licensing',visibility:'Restricted',assetId:'A2',date:businessDay(),version:1,size:'1 KB'}];s.business.onboarding=[{companyId:'c1',requiredUnderwriters:['WFG','Commonwealth'],evidence:[],applicationStatus:'Not started',launchedAt:''}];s.business.credentials=[];
 if(!q.has('fresh'))configureAgencySetup(s,{companyId:'c1',expectedVersion:0,templateVersion:1,owners:[{memberId:'m1',kind:'existing'}],agreementCount:1,eoCovered:true});
 if(q.has('tasks')){const r=suggestedAgencyMaintenance(s,'c1').find(r=>r.kind==='Domain');r.nextDueOn=businessDay();saveAgencyMaintenance(s,{expectedRevision:0,record:r});syncAgencyMaintenance(s,businessDay(),'c1');s.tasks.push({id:'production-task',companyId:'c1',title:'Hidden production work',scope:'production',done:false,owner:'',due:'',priority:'Normal'});}
 let snapshot={s,connection:q.has('viewer')?{access:{role:'viewer',allCompanies:false,restricted:true,userId:'11111111-1111-4111-8111-111111111111',email:'operator@example.test'}}:undefined};window.phaseOneState=()=>structuredClone(snapshot.s);window.updates=[];
 export function useWorkspace(){const current=useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>snapshot);return {...current,update:async(fn,title)=>{const next=structuredClone(snapshot.s);fn(next);snapshot={...snapshot,s:next};window.updates.push(title);listeners.forEach(fn=>fn());return true;}};}
 export const download=()=>{};export const exportCsv=()=>{};export const saveAsset=()=>{throw Error('Unexpected write')};export const getAsset=()=>{throw Error('Unexpected read')};export const getAssetForDocument=()=>{throw Error('Unexpected read')};`}));}}]});
 server=createServer((req,res)=>{const path=new URL(req.url,'http://localhost').pathname;if(path==='/app.mjs'){res.setHeader('content-type','text/javascript');res.end(bundle.outputFiles.find(f=>f.path.endsWith('.mjs')).contents);}else if(path==='/app.css'){res.setHeader('content-type','text/css');res.end(bundle.outputFiles.find(f=>f.path.endsWith('.css')).contents);}else{res.setHeader('content-type','text/html');res.end('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><style>*{box-sizing:border-box}body{font:14px Arial;margin:18px}input,select,textarea{max-width:100%}.form-stack{display:grid;gap:16px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field-label{display:grid;gap:8px}.input{padding:8px}table{border-collapse:collapse}td{padding:8px}:root{--border:#ddd;--muted:#f7f7f7;--muted-foreground:#555;--primary:#00305b}button{cursor:pointer}[role=dialog]{background:white;border:1px solid #ddd;max-width:760px;width:calc(100vw - 32px);padding:24px;position:fixed;left:50%;top:50%;transform:translate(-50%,-50%)}[role=dialog] button{padding:6px}</style><div id="root"></div><script type="module" src="/app.mjs"></script></html>');}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;try{browser=await chromium.launch({headless:true});}catch{browser=await chromium.launch({channel:'chrome',headless:true});}
});
afterEach(async()=>{await context?.close();assert.deepEqual(errors,[]);});after(async()=>{await browser?.close();if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});
async function open(query='',viewport={width:1280,height:1000}){errors=[];context=await browser.newContext({viewport});await context.route('**/*',r=>{if(!r.request().url().startsWith(origin)){errors.push('Unexpected remote request');return r.abort();}return r.continue();});page=await context.newPage();page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`${origin}/?${query}`);await page.locator('#ready').waitFor({state:'attached'});}
const setupRow=title=>page.locator('section[aria-label="Setup and approvals"] div').filter({has:page.locator('strong').filter({hasText:title})}).filter({has:page.getByRole('button',{name:'Edit task',exact:true})}).last();
test('actual setup editor requires a linked original before completing a selected-state license task',async()=>{await open();const row=setupRow('NC: Agency license original uploaded');await row.getByRole('button',{name:'Edit task',exact:true}).click();await page.getByLabel('Task status',{exact:true}).selectOption('Complete');assert.equal(await page.getByRole('button',{name:'Save task',exact:true}).isDisabled(),true);await page.getByLabel('NC license original.pdf',{exact:true}).check();await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});const s=await page.evaluate(()=>window.phaseOneState());assert.equal(s.tasks.find(t=>t.phaseOne?.itemId==='license-original'&&t.phaseOne.subject==='NC').status,'Complete');assert.equal(s.tasks.find(t=>t.phaseOne?.itemId==='application-original').status,'Complete');assert.equal(s.tasks.find(t=>t.phaseOne?.itemId==='license-original'&&t.phaseOne.subject==='SC').status,'Not Started');});
test('setup choices generate new-owner authorization tasks and two governing originals',async()=>{await open('fresh=1');await page.getByRole('button',{name:'Create setup checklist',exact:true}).click();await page.getByLabel('Fictional Owner LLC ownership type',{exact:true}).selectOption('new');await page.getByLabel('Executed governing agreements',{exact:true}).selectOption('2');await page.getByRole('button',{name:'Save setup choices',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});const s=await page.evaluate(()=>window.phaseOneState());assert.equal(s.companies[0].agencySetup.owners[0].kind,'new');assert.equal(s.tasks.find(t=>t.phaseOne?.itemId==='agreements-original').phaseOne.documentRequirement.minimum,2);assert.ok(s.tasks.some(t=>t.phaseOne?.itemId==='owner-llc-authorization'));assert.equal(s.tasks.filter(t=>t.phaseOne?.itemId==='underwriter-original').length,2);});
test('maintenance creates a dated three-year domain cycle, completes it and preserves roll-forward history',async()=>{await open('maintenance=1');await page.getByRole('button',{name:'Add schedule',exact:true}).click();await page.getByLabel('Applicable obligation',{exact:true}).selectOption({label:'Fictional Title: domain renewal'});const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());await page.getByLabel('Next due date',{exact:true}).fill(today);await page.getByLabel('Renewal term (years)',{exact:true}).fill('3');await page.getByRole('button',{name:'Save schedule',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});await page.getByRole('button',{name:'Complete cycle',exact:true}).click();assert.equal((await page.getByLabel('Next renewal date',{exact:true}).inputValue()).slice(0,4),String(Number(today.slice(0,4))+3));await page.getByRole('button',{name:'Complete and roll forward',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});const s=await page.evaluate(()=>window.phaseOneState());assert.equal(s.agencyMaintenance.history.length,1);assert.equal(s.tasks.find(t=>t.phaseOne?.kind==='maintenance').done,true);assert.equal(s.agencyMaintenance.notifications.enabled,false);});
test('actual Agency Tasks hides production work and checkbox bypass; recurring completion stays in its cycle editor',async()=>{await open('tasks=1');assert.equal(await page.getByText('Hidden production work',{exact:true}).count(),0);const row=page.getByRole('row').filter({hasText:'NC: Agency license original uploaded'});assert.equal(await row.getByRole('checkbox').isDisabled(),true);await row.getByRole('button',{name:'Edit task',exact:true}).click();assert.equal(await page.getByLabel('Task status',{exact:true}).inputValue(),'Not Started');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('row').filter({hasText:'Fictional Title: domain renewal'}).getByRole('button',{name:'Edit task',exact:true}).click();assert.equal(await page.getByLabel('Task status',{exact:true}).locator('option[value="Complete"]').count(),0);assert.equal(await page.getByLabel('Due date',{exact:true}).isDisabled(),true);await page.getByLabel('Task status',{exact:true}).selectOption('In Progress');await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});assert.equal((await page.evaluate(()=>window.phaseOneState())).tasks.find(t=>t.phaseOne?.kind==='maintenance').status,'In Progress');});
test('viewers have read-only setup and mobile layout stays within viewport',async()=>{await open('viewer=1',{width:390,height:844});assert.equal(await page.getByRole('button',{name:'Edit task',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Setup choices',exact:true}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);});
test('license approval saves a structured effective date and cannot complete with a blank date',async()=>{await open();await setupRow('NC: Agency license approved and effective date recorded').getByRole('button',{name:'Edit task',exact:true}).click();await page.getByLabel('Task status',{exact:true}).selectOption('Complete');assert.equal(await page.getByLabel('License approval / effective date',{exact:true}).getAttribute('required'),'');assert.equal(await page.getByRole('button',{name:'Save task',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('dialog').count(),1);await page.getByLabel('License approval / effective date',{exact:true}).fill('2026-09-15');await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});assert.equal((await page.evaluate(()=>window.phaseOneState())).tasks.find(t=>t.phaseOne.itemId==='license-approved'&&t.phaseOne.subject==='NC').effectiveOn,'2026-09-15');});
test('template editor saves a new version while existing companies retain the selected version',async()=>{await open();await page.getByRole('button',{name:'Edit template',exact:true}).click();await page.getByLabel('Template name',{exact:true}).fill('Fictional revised setup');await page.getByRole('button',{name:'Save new template version',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});const s=await page.evaluate(()=>window.phaseOneState());assert.equal(s.agencySetupTemplates.length,2);assert.equal(s.agencySetupTemplates[1].name,'Fictional revised setup');assert.equal(s.companies[0].agencySetup.templateVersion,1);});

test('setup completion explains missing structured domain and disables save',async()=>{await open();await setupRow('Domain purchased and entered').getByRole('button',{name:'Edit task',exact:true}).click();await page.getByLabel('Task status',{exact:true}).selectOption('Complete');await page.getByText('Save a valid company domain in Overview before completing this task.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Save task',exact:true}).isDisabled(),true);assert.equal((await page.evaluate(()=>window.phaseOneState())).tasks.find(t=>t.phaseOne.itemId==='domain').done,false);});
