import test from 'node:test';
import assert from 'node:assert/strict';
import { assistantContext, emptyWorkspace, P } from '../.local-test/backend/api.mjs';
const a={userId:'user-a',email:'a@example.com',role:'operations',allCompanies:false,companyIds:['A'],restricted:false,version:1,partnerMembers:[]};
function fixture(){const s=emptyWorkspace(a.email);s.companies=['A','B'].map(id=>({id,name:`Company ${id}`,stage:'Onboarding',jurisdiction:'NC',steps:[false],members:[],contact:'Private Contact',email:'secret@example.com'}));s.orders=['A','B'].map(id=>({id:`O-${id}`,companyId:id,address:'Synthetic address '+id,status:'New',fields:[],notes:'PRIVATE NOTE'}));s.documents=[{id:'internal',companyId:'A',name:'Source.pdf',category:'Other',visibility:'Internal',version:1,assetId:'asset',text:'PRIVATE CONTENT'},{id:'restricted',companyId:'A',name:'PRIVATE APPLICATION',category:'Application',visibility:'Restricted',version:1,text:'PRIVATE SSN'},{id:'outside',companyId:'B',name:'PRIVATE B',visibility:'Internal',version:1}];return s;}
test('assistant omits contacts, applications, other companies and unread contents',()=>{const c=assistantContext(fixture(),a,'workspace',5,'A'),raw=JSON.stringify(c);assert(!raw.includes('PRIVATE'));assert(!raw.includes('secret@example.com'));assert(!raw.includes('O-B'));assert(c.sources.some(s=>s.id==='order:O-A'));assert.equal(c.sources.find(s=>s.id==='document:internal').facts.contentRead,false);});
test('assistant rejects wrong company, file and partner staff access',()=>{const s=fixture();assert.throws(()=>assistantContext(s,a,'w',1,'B'),/company/);assert.throws(()=>assistantContext(s,a,'w',1,'A','O-B'),/file/);assert.throws(()=>assistantContext(s,{...a,role:'partner'},'w',1),/partner/);});
test('companyless assistant exposes setup counts without file details',()=>{const c=assistantContext(fixture(),a,'w',1);assert(!c.sources.some(s=>s.id.startsWith('order:')));assert(!JSON.stringify(c).includes('Company B'));assert.equal(c.sources.find(s=>s.id==='workspace').facts.companyCount,1);});
test('restricted source dependencies disappear before assistant context construction',()=>{const s=fixture();s.documents[1].orderId='O-A';assert.throws(()=>assistantContext(s,a,'w',1,'A','O-A'),/file/);assert(!assistantContext(s,a,'w',1,'A').readableSourceIds.includes('order:O-A'));});
test('assistant context bounds records and discloses truncation',()=>{const s=fixture();s.tasks=Array.from({length:100},(_,i)=>({id:'t'+i,companyId:'A',title:'Task '+i,done:false}));const c=assistantContext(s,a,'w',1,'A');assert.equal(c.sources.length,60);assert(c.truncated);assert(c.readableSourceIds.length>60);});
test('finals facts use the scoped queue without inferring receipt or exposing reference text',()=>{const s=fixture();s.inbox=[{id:'final-a',companyId:'A',orderId:'O-A',kind:'Finals',time:'Yesterday',body:'PRIVATE EMAIL'},{id:'final-a-2',companyId:'A',orderId:'O-A',kind:'Finals',time:'2026-09-01T12:00:00Z'}];P.addReferencedSource(s,'O-A',{wording:'PRIVATE original reference',role:'Prior policy',required:true});const c=assistantContext(s,a,'w',2,'A');const facts=c.sources.find(x=>x.id==='order:O-A').facts.finals;assert.equal(facts.inBacklog,true);assert.equal(facts.stage,'Waiting');assert.equal(facts.requestCount,2);assert.equal(facts.ageDays,null);assert.equal(facts.receivedAt,null);assert.equal(facts.requiredReferenceHoldCount,1);assert(!JSON.stringify(c).includes('PRIVATE'));assert.equal(assistantContext(fixture(),a,'w',1,'A').sources.find(x=>x.id==='order:O-A').facts.finals.inBacklog,false);});
test('document metadata distinguishes current versions while keeping contents unread',()=>{const s=fixture();s.documents.push(...[1,2].map(version=>({id:'deed-'+version,companyId:'A',orderId:'O-A',name:'Recorded deed.pdf',sourceRole:'Deed',visibility:'Internal',version,text:'PRIVATE CONTENT'})));const c=assistantContext(s,a,'w',1,'A','O-A');assert.equal(c.sources.find(x=>x.id==='document:deed-1').facts.currentFileSource,false);assert.equal(c.sources.find(x=>x.id==='document:deed-2').facts.currentFileSource,true);assert(c.sources.filter(x=>x.id.startsWith('document:')).every(x=>x.facts.contentRead===false));assert(!JSON.stringify(c).includes('PRIVATE'));});
test('long metadata cannot exceed the assistant context character budget',()=>{const s=fixture();s.tasks=Array.from({length:10},(_,i)=>({id:'long-'+i,companyId:'A',title:'A'.repeat(20000),done:false}));const c=assistantContext(s,a,'w',1,'A');assert(c.truncated);assert(c.sources.map(x=>JSON.stringify(x).length).reduce((a,b)=>a+b,0)<=60000);assert(c.readableSourceIds.includes('task:long-9'));});
