import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const buildResult=await build({stdin:{contents:"export {createSeed} from './lib/title/model'; export {commitmentSnapshot,reviewCommitment,finalReadiness,titleFile,orderSources,outputRoles} from './lib/title/production';",resolveDir:fileURLToPath(new URL('../',import.meta.url))},write:false,bundle:true,platform:'node',format:'esm',target:'es2022'});
const {createSeed,commitmentSnapshot,reviewCommitment,finalReadiness,titleFile,orderSources,outputRoles}=await import(`data:text/javascript;base64,${Buffer.from(buildResult.outputFiles[0].text+'\n//# sourceURL=commitment-snapshot-test.mjs').toString('base64')}`);
const jsonb=value=>Array.isArray(value)?value.map(jsonb):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>b.length-a.length||b.localeCompare(a)).map(([key,item])=>[key,jsonb(item)])):value;
const needsReview=(s,o)=>finalReadiness(s,o).missingContext.includes('commitment review');
function fixture(){const s=createSeed(),o=s.orders[0];reviewCommitment(s,o,'Original commitment terms and references reviewed.');return{s,o};}
function legacySnapshot(s,o){const p=titleFile(o);return JSON.stringify({...(p.referencedSources?.length?{referencedSources:p.referencedSources}:{}),sources:orderSources(s,o.id).filter(d=>!outputRoles.includes(d.sourceRole)).map(d=>[d.id,d.version,d.sourceRole]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))),requirements:p.requirements,commitment:p.commitmentReference,prior:p.priorPolicyReference,financing:p.financing,loan:p.loanAmount,county:p.county});}
test('commitment review remains current after actual JSON serialization with reordered nested database keys',()=>{const{s,o}=fixture(),before=structuredClone(o.production.commitmentReview),snapshot=commitmentSnapshot(s,o);assert.equal(needsReview(s,o),false);const stored=jsonb(JSON.parse(JSON.stringify(s))),reloaded=stored.orders.find(order=>order.id===o.id);assert.notEqual(JSON.stringify(reloaded.production.requirements),JSON.stringify(o.production.requirements));assert.equal(commitmentSnapshot(stored,reloaded),snapshot);assert.equal(needsReview(stored,reloaded),false);assert.deepEqual(reloaded.production.commitmentReview,before);});
test('legacy insertion-order review stamps stay current without rewriting their actor, time or snapshot',()=>{const{s,o}=fixture();o.production.commitmentReview.snapshot=legacySnapshot(s,o);assert.notEqual(o.production.commitmentReview.snapshot,commitmentSnapshot(s,o));const original=structuredClone(o.production.commitmentReview),stored=jsonb(JSON.parse(JSON.stringify(s))),reloaded=stored.orders.find(order=>order.id===o.id);assert.equal(needsReview(stored,reloaded),false);assert.deepEqual(reloaded.production.commitmentReview,original);});
test('semantic comparison still rejects changed requirements, source versions, values, types, missing or additional facts and array order',()=>{for(const change of [(s,o)=>o.production.requirements[0].text+=' changed',(s,o)=>o.production.requirements[0].evidence='Different evidence',(s,o)=>o.production.requirements.reverse(),(s,o)=>o.production.loanAmount++,(s,o)=>o.production.loanAmount=String(o.production.loanAmount),(s,o)=>o.production.county='Another county',(s,o)=>o.production.commitmentReference+=' revised',(s,o)=>s.documents.find(d=>d.sourceRole==='Deed'&&d.orderId===o.id).version++,(s,o)=>o.production.requirements[0].extra='unreviewed fact',(s,o)=>delete o.production.requirements[0].note]){for(const legacy of [false,true]){const{s,o}=fixture();if(legacy)o.production.commitmentReview.snapshot=legacySnapshot(s,o);const stored=jsonb(JSON.parse(JSON.stringify(s))),reloaded=stored.orders.find(order=>order.id===o.id);change(stored,reloaded);assert.equal(needsReview(stored,reloaded),true,change.toString());}}});
test('malformed, empty, primitive and unrelated review stamps never become current',()=>{for(const invalid of ['',undefined,null,'{invalid','null','[]','42','{}','{"county":"Mecklenburg"}']){const{s,o}=fixture();o.production.commitmentReview.snapshot=invalid;assert.equal(needsReview(s,o),true)}});
test('nested referenced-source decisions compare by values, preserve review array order and reject amended decisions',()=>{const{s,o}=fixture();o.production.referencedSources=[{id:'reference-1',role:'Prior policy',wording:'Review the prior original',reviews:[{decision:'Not applicable',documentId:'',documentVersion:0,note:'Explicitly reviewed and inapplicable',reviewer:'Reviewer',at:'2026-09-24T12:00:00Z'}]}];reviewCommitment(s,o,'Referenced source decision checked.');o.production.commitmentReview.snapshot=legacySnapshot(s,o);const stored=jsonb(JSON.parse(JSON.stringify(s))),reloaded=stored.orders.find(order=>order.id===o.id);assert.equal(needsReview(stored,reloaded),false);reloaded.production.referencedSources[0].reviews[0].note='Different reviewed evidence';assert.equal(needsReview(stored,reloaded),true)});
