// Real guided upload component. Fictional company/file records and in-memory transport.
import test, { before, after, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { chromium } from 'playwright';
const web = fileURLToPath(new URL('../', import.meta.url));
let server, browser, context, page, origin, errors=[];
before(async()=>{
 const bundle=await build({absWorkingDir:web,write:false,bundle:true,platform:'browser',format:'esm',jsx:'automatic',logLevel:'silent',define:{'process.env.NODE_ENV':'"production"'},stdin:{resolveDir:web,loader:'tsx',contents:`
 import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {UploadDocument} from './components/title/document-upload';import {useWorkspace} from '@/lib/title/store';
 function App(){const q=new URLSearchParams(location.search);const[open,setOpen]=useState(true);useWorkspace();const role=q.get('output');return <>{open?<UploadDocument productionOnly={q.has('productionOnly')} companyId={q.has('company')||q.has('order')||role?'qa-a':null} initialDestination={q.has('companyDestination')?'company':q.has('title')?'title':undefined} orderId={q.has('order')||role?'qa-order':undefined} initialRole={role||undefined} policyId={role==='Final policy'&&!q.has('missing')?'qa-policy':undefined} cplId={role==='CPL'&&!q.has('missing')?'qa-cpl':undefined} cplVersion={role==='CPL'?2:undefined} correctionId={role==='Correction output'&&!q.has('missing')?'qa-correction':undefined} commitmentVersion={role==='Commitment output'?2:undefined} onClose={()=>setOpen(false)}/>:<p>Upload closed</p>}<i id='fixture-ready'/></>};createRoot(document.getElementById('root')).render(<App/>);
 `},plugins:[{name:'upload-fixture',setup(b){b.onResolve({filter:/^@\/lib\/title\/store$/},()=>({path:'store',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({resolveDir:web,loader:'tsx',contents:`
 import {useSyncExternalStore} from 'react';import {createSeed} from './lib/title/model';import {titleFile,neededFields} from './lib/title/production';
 const q=new URLSearchParams(location.search),listeners=new Set();const s=createSeed();s.companies=s.companies.slice(0,2);s.companies[0].id='qa-a';s.companies[0].name='QA Alpha Title';s.companies[1].id='qa-b';s.companies[1].name='QA Beta Title';s.orders=s.orders.slice(0,2);s.orders[0].id='qa-order';s.orders[0].companyId='qa-a';s.orders[0].address='1 Fictional Way';s.orders[0].status='Ready for jacket';s.orders[0].production={...titleFile(s.orders[0]),version:4};s.orders[0].fields=neededFields(s.orders[0]).map(f=>({...f,value:'reviewed value',reviewed:true}));s.orders[1].id='qa-other';s.orders[1].companyId='qa-b';s.documents=[];
 s.business={policies:[{id:'qa-policy',orderId:'qa-order',version:3,status:'Prepared',preparedSnapshot:'qa-policy-snapshot'}],commitments:[{orderId:'qa-order',version:2,status:'Prepared',snapshot:q.has('missing')?'':'qa-commitment-snapshot'}],cpls:[{id:'qa-cpl',orderId:'qa-order',version:2,status:'Prepared',snapshot:'qa-cpl-snapshot'}],corrections:[{id:'qa-correction',orderId:'qa-order',policyId:'qa-policy',status:'Reviewed',reviewSnapshot:'qa-correction-snapshot'}]};
 if(q.has('collision'))s.documents.push({id:'qa-existing',companyId:'qa-a',orderId:'qa-order',name:'original.txt',sourceRole:'Deed',version:1});
 let snapshot={s,connection:{workspaceId:'qa-workspace',revision:1,access:{userId:'qa-user',role:q.get('accessRole')||'owner',version:1,allCompanies:true,companyIds:[],restricted:!q.has('norestricted')}}};window.allocationUploads=[];window.allocationSaves=[];window.allocationFailure=q.has('fail');window.allocationSaveFailure=q.has('savefail');window.allocationPending=[];window.allocationState=()=>structuredClone(snapshot);
 window.allocationChange=kind=>{const next=structuredClone(snapshot);if(kind==='identity')next.connection.access.userId='qa-new-user';if(kind==='workspace')next.connection.workspaceId='qa-new-workspace';if(kind==='access')next.connection.access.version++;if(kind==='order')next.s.orders[0].companyId='qa-b';if(kind==='production')next.s.orders[0].production.version++;if(kind==='company')next.s.companies=[];snapshot=next;listeners.forEach(fn=>fn());};
 export function useWorkspace(){const current=useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>snapshot);return {...current,update:async(fn,title,detail)=>{if(window.allocationSaveFailure)return false;const next=structuredClone(snapshot.s);fn(next);snapshot={...snapshot,s:next};window.allocationSaves.push({title,detail});listeners.forEach(fn=>fn());return !window.allocationLostResponse;}};}
 export async function saveAsset(id,file,binding){if(window.allocationFailure)throw Error('Synthetic upload failure');window.allocationUploads.push({id,binding,name:file.name,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))});if(q.has('hold'))await new Promise(resolve=>window.allocationPending.push(resolve));}
 `}));}}]});
 server=createServer((req,res)=>{const script=req.url==='/app.mjs';res.writeHead(200,{'content-type':script?'text/javascript':'text/html'});res.end(script?bundle.outputFiles[0].contents:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font:14px Arial}.allocation-upload{background:white;position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);display:grid;gap:16px;padding:24px}button{cursor:pointer}button:disabled{cursor:default}</style><div id="root"></div><script type="module" src="/app.mjs"></script>');});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;try{browser=await chromium.launch({headless:true});}catch{browser=await chromium.launch({headless:true,channel:'chrome'});}
});
afterEach(async()=>{await context?.close();assert.deepEqual(errors,[]);});
after(async()=>{await browser?.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}});
async function open(query='',mobile=false){errors=[];context=await browser.newContext({viewport:mobile?{width:320,height:650}:{width:1200,height:1000}});await context.route('**/*',route=>route.request().url().startsWith(origin+'/')?route.continue():(errors.push('External request'),route.abort()));page=await context.newPage();page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?'+query);await page.locator('#fixture-ready').waitFor({state:'attached'});}
const file=(name='original.txt',text='Fictional original bytes\n§')=>({name,mimeType:'text/plain',buffer:Buffer.from(text)});
async function add(files=file()){await page.getByLabel('Select documents',{exact:true}).setInputFiles(files);}
async function review(){await page.getByRole('button',{name:'Review documents',exact:true}).click();}
async function saved(){await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText('Upload closed',{exact:true}).waitFor();return page.evaluate(()=>({state:window.allocationState().s,uploads:window.allocationUploads,saves:window.allocationSaves}));}

test('global upload has no guessed company and saves mixed company categories with unchanged originals',async()=>{
 await open();assert.equal(await page.getByLabel('Upload company').inputValue(),'');assert.equal(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('Select documents').count(),0);
 await page.getByLabel('Upload company').selectOption('qa-b');await page.getByRole('button',{name:'Continue',exact:true}).click();await add([file('formation.txt'),file('application.txt'),file('logo.txt')]);await review();
 await page.getByLabel('Document category for formation.txt (1)',{exact:true}).selectOption('Formation');await page.getByLabel('Document category for application.txt (2)',{exact:true}).selectOption('Applications');await page.getByLabel('Document category for logo.txt (3)',{exact:true}).selectOption('Branding');
 assert.equal(await page.getByLabel('Document visibility for application.txt (2)',{exact:true}).inputValue(),'Restricted');assert.equal(await page.getByLabel('Document visibility for application.txt (2)',{exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('Uploaded source type').count(),0);assert.equal(await page.getByLabel('Link upload to order').count(),0);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);
 await page.screenshot({path:'/tmp/title-allocation-review.png'});const result=await saved();assert.equal(result.uploads.length,3);for(const upload of result.uploads){assert.equal(upload.binding.companyId,'qa-b');assert.deepEqual(upload.bytes,Array.from(file().buffer));}assert.deepEqual(result.state.documents.map(d=>[d.name,d.category,d.visibility]).sort(),[['application.txt','Applications','Restricted'],['formation.txt','Formation','Internal'],['logo.txt','Branding','Internal']]);assert.ok(result.state.documents.every(d=>!d.orderId&&!d.sourceRole));
});
test('company context locks destination; Back preserves selections and removal updates the batch',async()=>{
 await open('company=1');await add([file('keep.txt'),file('remove.txt')]);await review();await page.getByLabel('Document category for keep.txt (1)').selectOption('Agreements');await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();assert.equal(await page.getByLabel('Upload company').inputValue(),'qa-a');assert.equal(await page.getByLabel('Upload company').isDisabled(),true);await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Remove remove.txt',exact:true}).click();await review();assert.equal(await page.getByLabel('Document category',{exact:true}).inputValue(),'Agreements');const result=await saved();assert.equal(result.uploads.length,1);assert.equal(result.uploads[0].name,'keep.txt');
});
test('title-only entry asks for a real same-company file and never selects one automatically',async()=>{
 await open('company=1&title=1');assert.equal(await page.getByLabel('Upload company').inputValue(),'qa-a');assert.equal(await page.getByLabel('Link upload to order').inputValue(),'');assert.equal(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);assert.deepEqual(await page.getByLabel('Link upload to order').locator('option').evaluateAll(options=>options.map(o=>o.value)),['','qa-order']);await page.getByLabel('Link upload to order').selectOption('qa-order');await page.getByRole('button',{name:'Continue',exact:true}).click();await add();await review();assert.equal(await page.getByLabel('Uploaded source type').inputValue(),'Other');assert.match(await page.getByRole('dialog').innerText(),/choose its source type before capturing fields/);assert.deepEqual(await page.getByLabel('Uploaded source type').locator('option').evaluateAll(options=>options.filter(o=>['CPL','Final policy','Correction output','Commitment output','Revised commitment'].includes(o.value))),[]);
});
for(const [label,query] of [['Production-only owner','productionOnly=1'],['operations account','accessRole=operations']])test(`${label} cannot choose company uploads and must keep a same-company title-file association`,async()=>{
 await open(query+'&companyDestination=1');
 const destination=page.getByRole('group',{name:'Document destination',exact:true});
 assert.equal(await destination.getByRole('button').count(),1);
 assert.equal(await destination.getByRole('button',{name:/Company documents/}).count(),0);
 assert.equal(await destination.getByRole('button',{name:/Title file documents/}).getAttribute('aria-pressed'),'true');
 assert.equal(await page.getByLabel('Upload company').inputValue(),'');
 assert.equal(await page.getByLabel('Link upload to order').inputValue(),'');
 assert.equal(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);
 await page.getByLabel('Upload company').selectOption('qa-a');
 assert.deepEqual(await page.getByLabel('Link upload to order').locator('option').evaluateAll(options=>options.map(option=>option.value)),['','qa-order']);
 assert.equal(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);
 await page.getByRole('dialog').locator('form').evaluate(form=>form.requestSubmit());
 assert.match(await page.getByRole('alert').innerText(),/Choose an existing title file belonging to this company/);
 assert.equal(await page.getByLabel('Select documents',{exact:true}).count(),0);
 assert.deepEqual(await page.evaluate(()=>({uploads:window.allocationUploads,saves:window.allocationSaves})),{uploads:[],saves:[]});
 await page.getByLabel('Link upload to order').selectOption('qa-order');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await add();await review();
 await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();
 assert.equal(await destination.getByRole('button',{name:/Company documents/}).count(),0);
 await page.getByLabel('Upload company').selectOption('qa-b');
 assert.equal(await page.getByLabel('Link upload to order').inputValue(),'');
 assert.equal(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);
 assert.deepEqual(await page.getByLabel('Link upload to order').locator('option').evaluateAll(options=>options.map(option=>option.value)),['','qa-other']);
 await page.getByLabel('Link upload to order').selectOption('qa-other');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await review();
 const result=await saved();
 assert.equal(result.uploads.length,1);assert.equal(result.uploads[0].binding.companyId,'qa-b');
 assert.deepEqual(result.state.documents.map(document=>[document.companyId,document.orderId,document.category,document.sourceRole]),[['qa-b','qa-other','Policy documents','Other']]);
});
test('mixed deed and security originals retain per-file provenance and invalidate affected reviews once',async()=>{
 await open('order=1');const before=await page.evaluate(()=>window.allocationState().s.orders[0]);await add([file('deed.txt'),file('security.txt')]);await review();await page.getByLabel('Source type for deed.txt (1)').selectOption('Deed');await page.getByLabel('Source type for security.txt (2)').selectOption('Deed of trust');const result=await saved();assert.deepEqual(result.state.documents.map(d=>[d.name,d.orderId,d.sourceRole]).sort(),[['deed.txt','qa-order','Deed'],['security.txt','qa-order','Deed of trust']]);assert.equal(result.state.orders[0].production.version,before.production.version+1);assert.equal(result.state.orders[0].status,'Needs review');assert.ok(result.state.orders[0].fields.some(f=>!f.reviewed));
});
for(const role of ['Commitment output','Final policy','CPL','Correction output','Revised commitment'])test(`${role} upload keeps its workflow binding, role, and production version`,async()=>{
 await open('output='+encodeURIComponent(role));await add();await review();assert.equal(await page.getByLabel('Uploaded source type').inputValue(),role);assert.equal(await page.getByLabel('Uploaded source type').isDisabled(),true);const result=await saved();const doc=result.state.documents[0];assert.equal(doc.sourceRole,role);assert.equal(doc.productionVersion,4);assert.equal(result.state.orders[0].production.version,4);if(role==='Commitment output'){assert.equal(doc.commitmentVersion,2);assert.equal(doc.preparationFingerprint,'qa-commitment-snapshot');}if(role==='Final policy'){assert.equal(doc.policyId,'qa-policy');assert.equal(doc.policyVersion,3);assert.equal(doc.preparationFingerprint,'qa-policy-snapshot');}if(role==='CPL'){assert.equal(doc.cplId,'qa-cpl');assert.equal(doc.cplVersion,2);assert.equal(doc.preparationFingerprint,'qa-cpl-snapshot');}if(role==='Correction output'){assert.equal(doc.correctionId,'qa-correction');assert.equal(doc.preparationFingerprint,'qa-correction-snapshot');}
});
for(const role of ['Commitment output','Final policy','CPL','Correction output'])test(`${role} missing provenance cannot upload bytes`,async()=>{
 await open('output='+encodeURIComponent(role)+'&missing=1');await add();await review();await page.getByRole('alert').waitFor();assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);assert.equal(await page.getByRole('button',{name:'Save documents',exact:true}).count(),0);
});
test('current title-file changes and source/output filename collisions fail before uploading',async()=>{
 await open('output=Final%20policy&collision=1');await add();await review();await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/distinct filename/);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);await page.evaluate(()=>window.allocationChange('production'));await page.getByRole('button',{name:'Save documents',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/changed/);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);
});
test('invalid types and excess files are visible without discarding selections or writing bytes',async()=>{
 await open('company=1');await add(Array.from({length:11},(_,i)=>file('item'+i+'.txt')));await review();assert.match(await page.getByRole('alert').innerText(),/up to 10 files/);assert.equal(await page.locator('.allocation-file').count(),11);await page.getByRole('button',{name:'Remove item10.txt',exact:true}).click();await add({name:'unsafe.html',mimeType:'text/html',buffer:Buffer.from('fictional')});await page.getByRole('button',{name:'Remove item9.txt',exact:true}).click();await review();assert.match(await page.getByRole('alert').innerText(),/Use PDF/);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);
});
test('upload and metadata failures preserve the reviewed originals for a successful retry',async()=>{
 await open('company=1&fail=1');await add();await review();await page.getByLabel('Document category',{exact:true}).selectOption('Formation');await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('Document category',{exact:true}).inputValue(),'Formation');await page.evaluate(()=>{window.allocationFailure=false;window.allocationSaveFailure=true;});await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText(/The save could not be confirmed/).waitFor();await page.evaluate(()=>{window.allocationSaveFailure=false;});const result=await saved();assert.equal(result.state.documents.length,1);assert.equal(result.state.documents[0].category,'Formation');assert.equal(result.uploads[0].id,result.uploads[1].id);
});
for(const change of ['identity','workspace','access'])test(`${change} changing during an upload prevents more bytes or document allocation`,async()=>{
 await open('company=1&hold=1');await add([file('one.txt'),file('two.txt')]);await review();await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.waitForFunction(()=>window.allocationPending.length===1);assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),1);await page.evaluate(kind=>window.allocationChange(kind),change);await page.evaluate(()=>window.allocationPending[0]());await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>window.allocationUploads.length),1);assert.equal(await page.evaluate(()=>window.allocationSaves.length),0);assert.equal(await page.getByRole('button',{name:'Save documents',exact:true}).isDisabled(),true);
});
test('restricted applications cannot upload without restricted access',async()=>{
 await open('company=1&norestricted=1');await add();await review();await page.getByLabel('Document category',{exact:true}).selectOption('Applications');await page.getByRole('button',{name:'Save documents',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/require restricted-document access/);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);
});
test('missing company and moved order fail before saving originals',async()=>{
 await open('order=1');await add();await review();await page.evaluate(()=>window.allocationChange('order'));await page.getByRole('button',{name:'Save documents',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/belonging to this company/);assert.deepEqual(await page.evaluate(()=>window.allocationUploads),[]);
});
test('review at 320px fits the viewport and leaves every control reachable',async()=>{
 await open('company=1',true);await add([file('very-long-fictional-formation-document-name-to-test-wrapping.txt'),file('application.txt')]);await review();const dimensions=await page.getByRole('dialog').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth,client:el.clientWidth,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right}));assert.ok(dimensions.left>=0&&dimensions.right<=320);assert.ok(dimensions.scroll<=dimensions.client+1);await page.getByLabel('Document category for application.txt (2)').selectOption('Applications');await page.getByRole('button',{name:'Save documents',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/title-allocation-mobile.png'});await saved();
});

test('moving a failed batch to another company creates new asset bindings without losing files',async()=>{
 await open('savefail=1');await page.getByLabel('Upload company').selectOption('qa-a');await page.getByRole('button',{name:'Continue',exact:true}).click();await add();await review();await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText(/The save could not be confirmed/).waitFor();await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByLabel('Upload company').selectOption('qa-b');await page.getByRole('button',{name:'Continue',exact:true}).click();await review();await page.evaluate(()=>{window.allocationSaveFailure=false;});const result=await saved();assert.equal(result.uploads.length,2);assert.notEqual(result.uploads[0].id,result.uploads[1].id);assert.equal(result.uploads[0].binding.companyId,'qa-a');assert.equal(result.uploads[1].binding.companyId,'qa-b');assert.equal(result.state.documents.length,1);assert.equal(result.state.documents[0].companyId,'qa-b');
});
test('a lost metadata response recovered by refresh is recognized without duplicate documents or uploads',async()=>{
 await open('company=1');await add();await review();await page.evaluate(()=>{window.allocationLostResponse=true;});await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText(/The save could not be confirmed/).waitFor();await page.evaluate(()=>{window.allocationLostResponse=false;});const result=await saved();assert.equal(result.state.documents.length,1);assert.equal(result.uploads.length,1);assert.equal(result.saves.length,1);
});
test('a previously committed batch with conflicting edited details demands review instead of duplication',async()=>{
 await open('company=1');await add();await review();await page.evaluate(()=>{window.allocationLostResponse=true;});await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText(/The save could not be confirmed/).waitFor();await page.getByLabel('Document category',{exact:true}).selectOption('Formation');await page.getByRole('button',{name:'Save documents',exact:true}).click();await page.getByText(/already saved with different details/).waitFor();assert.equal(await page.evaluate(()=>window.allocationState().s.documents.length),1);assert.equal(await page.evaluate(()=>window.allocationUploads.length),1);
});
test('same-name originals preview and save distinct version numbers in order',async()=>{
 await open('company=1');await add([file('same.txt','first original'),file('same.txt','second original')]);await review();await page.getByText('Will save as version 1',{exact:true}).waitFor();await page.getByText('Will save as version 2',{exact:true}).waitFor();const result=await saved();assert.deepEqual(result.state.documents.map(d=>d.version).sort(),[1,2]);assert.notEqual(result.uploads[0].id,result.uploads[1].id);assert.deepEqual(result.uploads[0].bytes,Array.from(Buffer.from('first original')));assert.deepEqual(result.uploads[1].bytes,Array.from(Buffer.from('second original')));
});
