import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const built=await build({stdin:{contents:"export * from './lib/backend/feedback-screenshots';export * from './lib/backend/feedback-screenshot-validation';",resolveDir:fileURLToPath(new URL('../',import.meta.url))},bundle:true,write:false,format:'esm',platform:'node'});
const lib=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6+9sAAAAASUVORK5CYII=','base64');
const workspaceId='10000000-0000-4000-8000-000000000001',id='20000000-0000-4000-8000-000000000001';
const input={workspaceId,id,kind:'problem',message:'Fictional screenshot',page:'Companies',view:'agency',screenshot:{fileName:'screenshot.png',mime:'image/png',base64:png.toString('base64')}};
function fixture(){let bytes,prepared,complete=false,failUpload=false,failRead=false;const calls=[];const context={workspaceId,email:'test@example.test',access:{userId:'author',version:1},rpc:async(name,args)=>{calls.push({name,args});if(failRead&&args.p_action==='read')throw {code:'42501'};if(args.p_action==='prepare'){if(prepared&&prepared.sha256!==args.p_input.sha256)throw {code:'PT409'};prepared=args.p_input;return{path:'private/path',ready:complete};}if(args.p_action==='complete'){complete=true;return{id,workspace_id:workspaceId,screenshot:{fileName:prepared.fileName}};}return{path:'private/path',sha256:prepared.sha256,mime:prepared.mime,fileName:prepared.fileName};},upload:async(path,value)=>{bytes=value;if(failUpload)throw Error('lost response');},download:async()=>bytes};return{context,calls,get bytes(){return bytes},set failUpload(v){failUpload=v},set failRead(v){failRead=v}};}
test('signature, dimensions, size, exact shape and canonical base64 are checked before any write',async()=>{const f=fixture();assert.deepEqual(lib.feedbackScreenshotBytes(png,'image/png'),{width:1,height:1});for(const screenshot of [{...input.screenshot,mime:'image/svg+xml'},{...input.screenshot,base64:Buffer.from('<svg/>').toString('base64')},{...input.screenshot,token:'secret'},{...input.screenshot,fileName:'../secret.png'},{...input.screenshot,base64:'!!!!'}])await assert.rejects(()=>lib.submitFeedbackScreenshot({...input,screenshot},f.context),e=>e.status===400);const huge=Buffer.from(png);huge.writeUInt32BE(12001,16);assert.throws(()=>lib.feedbackScreenshotBytes(huge,'image/png'));assert.throws(()=>lib.feedbackScreenshotBytes(new Uint8Array(4194305),'image/png'));assert.equal(f.calls.length,0);});
test('JPEG frame dimensions are bounded and mismatched PNG MIME is rejected',()=>{const jpg=Uint8Array.from([255,216,255,192,0,11,8,0,1,0,1,1,1,17,0,255,218,0,8,1,1,0,0,63,0,0,255,217]);assert.deepEqual(lib.feedbackScreenshotBytes(jpg,'image/jpeg'),{width:1,height:1});assert.throws(()=>lib.feedbackScreenshotBytes(jpg,'image/png'));});
test('immutable upload handles a lost upload response and same-report retry without replacing original',async()=>{const f=fixture();f.failUpload=true;assert.equal((await lib.submitFeedbackScreenshot(input,f.context)).id,id);assert.deepEqual(Buffer.from(f.bytes),png);const prepare=f.calls[0].args.p_input;assert.match(prepare.sha256,/^[a-f0-9]{64}$/);await lib.submitFeedbackScreenshot(input,f.context);assert.equal(f.calls.filter(c=>c.args.p_action==='prepare').length,2);const changed=Buffer.from(png);changed[42]^=1;await assert.rejects(()=>lib.submitFeedbackScreenshot({...input,screenshot:{...input.screenshot,base64:changed.toString('base64')}},f.context),e=>e.status===409);});
test('download uses private RPC authorization, verifies stored bytes and rechecks access after I/O',async()=>{const f=fixture();await lib.submitFeedbackScreenshot(input,f.context);const result=await lib.readFeedbackScreenshot({workspaceId,id},f.context);assert.equal(result.base64,input.screenshot.base64);assert.equal(f.calls.filter(c=>c.args.p_action==='read').length,2);f.context.download=async()=>{f.failRead=true;return png;};await assert.rejects(()=>lib.readFeedbackScreenshot({workspaceId,id},f.context),e=>e.status===403);await assert.rejects(()=>lib.readFeedbackScreenshot({workspaceId,id,objectPath:'other'},f.context),e=>e.status===400);});
