// Real guided UI; fictional account, private API and document-reader transport.
import test, { before, after, afterEach } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
const web = process.env.JV_WEB_ROOT || fileURLToPath(new URL("../", import.meta.url));
const require = createRequire(`${web}/package.json`);
const { build } = require("esbuild"), { chromium } = require("playwright");
let server, browser, context, page, origin;
let errors = [];
before(async () => {
  const result = await build({ absWorkingDir: web, nodePaths: [`${web}/node_modules`], write: false, bundle: true, platform: "browser", format: "esm", jsx: "automatic", logLevel: "silent", loader: { ".css": "empty" }, define: { "process.env.NODE_ENV": '"production"' },
    stdin: { resolveDir: web, loader: "tsx", contents: `import React from 'react';import {createRoot} from 'react-dom/client';import {JVApplicationPanel} from './components/title/jv-application';import {useWorkspace} from '@/lib/title/store';function App(){const {s}=useWorkspace();return <JVApplicationPanel company={s.companies[0]} onDocuments={()=>window.documentsOpened=true}/>;}createRoot(document.getElementById('root')).render(<App/>);` },
    plugins: [{ name: "jv-fixture", setup(b) {
      if (process.env.JV_UI_SOURCE) b.onResolve({ filter: /^\.\/components\/title\/jv-application$/ }, () => ({ path: process.env.JV_UI_SOURCE }));
      if (process.env.JV_DOMAIN_SOURCE) b.onResolve({ filter: /^@\/lib\/title\/jv-application$/ }, () => ({ path: process.env.JV_DOMAIN_SOURCE }));
      b.onResolve({ filter: /^\.\/shared$/ }, () => ({ path: `${web}/components/title/shared.tsx` }));
      b.onResolve({ filter: /^\.\/jv-application-reader$/ }, () => ({ path: "reader", namespace: "fixture" }));
      b.onLoad({ filter: /^reader$/, namespace: "fixture" }, () => ({ loader: "tsx", resolveDir: web, contents: `import React from 'react';export function JVApplicationReader({onFill}){return <button type="button" onClick={()=>onFill({name:'Compared Fictional Applicant'},'restricted-original')}>Fixture verified original</button>;}` }));
      b.onResolve({ filter: /^@\/lib\/backend\/jv-intake-client$/ }, () => ({ path: "api", namespace: "fixture" }));
      b.onLoad({ filter: /^api$/, namespace: "fixture" }, () => ({ loader: "ts", resolveDir: web, contents: `
        import {newJVApplication,jvIntakeFingerprint} from '@/lib/title/jv-application';
        const query=new URLSearchParams(location.search);window.jvRequests=[];window.jvPending=[];
        let payload=newJVApplication();
        if(query.has('complete'))Object.assign(payload.applicants[0],{name:'Fictional Applicant',email:'applicant@example.test',phone:'7045550101',dob:'1985-01-15',ssn:'123456789',driverLicense:'FICTIONAL-DL',currentAddress:'10 Example Street',ownershipType:'individual',businessStatus:'not-applicable',residenceHistory:[{id:'residence-1',address:'10 Example Street',from:'2000-01-01',to:''}],employmentHistory:[{id:'job-1',employer:'Example Employer',role:'Coordinator',address:'20 Example Street',from:'2000-01-01',to:''}]});
        let saved={companyId:'fictional-company',version:query.has('complete')?1:0,payload,status:'Draft',reviewNote:'',updatedAt:null,updatedBy:null,reviewedAt:null,reviewedBy:null};
        window.readJvRecord=()=>structuredClone(saved);
        export async function jvIntakeClientRequest(context,action,data){
          window.jvRequests.push({context,action,data:structuredClone(data)});
          if(window.holdJv){window.holdJv=false;await new Promise(resolve=>window.jvPending.push(resolve));}
          if(window.failJv){const status=window.failJv;window.failJv=0;throw Object.assign(Error('DO NOT DISPLAY private details'),{status});}
          if(action==='load')return structuredClone(saved);
          if(data.expectedVersion!==saved.version)throw Object.assign(Error('conflict'),{status:409});
          const changed=data.payload&&jvIntakeFingerprint(data.payload)!==jvIntakeFingerprint(saved.payload);
          saved={...saved,version:saved.version+1,payload:data.payload||saved.payload,status:action==='submit'?'Ready for review':action==='review'?'Reviewed':action==='reopen'||changed?'Draft':saved.status,reviewNote:action==='review'?data.reviewNote:changed||action==='reopen'?'':saved.reviewNote,reviewedAt:action==='review'?'2026-09-24T12:00:00Z':saved.reviewedAt};
          return structuredClone(saved);
        }` }));
      b.onResolve({ filter: /^@\/lib\/title\/store$/ }, () => ({ path: "store", namespace: "fixture" }));
      b.onLoad({ filter: /^store$/, namespace: "fixture" }, () => ({ loader: "tsx", resolveDir: web, contents: `
        import {useSyncExternalStore} from 'react';const query=new URLSearchParams(location.search),listeners=new Set();
        const company={id:'fictional-company',name:'Fictional Company'},base={companyId:company.id,version:1,date:'2026-09-24',size:'1 KB',mime:'application/pdf',category:'Applications',visibility:'Restricted',assetId:'asset-fictional'};
        let snapshot={s:{companies:[company],documents:[{...base,id:'restricted-original',name:'Fictional restricted original.pdf'},{...base,id:'internal-original',name:'Hidden internal original.pdf',visibility:'Internal'},{...base,id:'other-company',name:'Hidden other company.pdf',companyId:'other'},{...base,id:'order-original',name:'Hidden order original.pdf',orderId:'order-1'},{...base,id:'missing-asset',name:'Hidden missing original.pdf',assetId:undefined}]},connection:query.has('local')?undefined:{workspaceId:'workspace-one',access:{userId:'staff-one',version:1,role:query.get('role')||'owner',restricted:!query.has('unrestricted'),allCompanies:!query.has('outofscope'),companyIds:[],email:'fictional@example.test'}}};
        window.changeJvContext=patch=>{snapshot={...snapshot,connection:{...snapshot.connection,...patch,access:{...snapshot.connection.access,...patch.access}}};listeners.forEach(fn=>fn());};
        window.workspaceWrites=0;export function useWorkspace(){const current=useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>snapshot);return {...current,update:()=>{window.workspaceWrites++;throw Error('Private intake must never update general workspace state');}};}
      ` }));
      if (process.env.JV_UI_SOURCE) b.onResolve({ filter: /^@\// }, args => ({ path: `${web}/${args.path.slice(2)}${/\.[a-z]+$/.test(args.path) ? "" : args.path.startsWith("@/components") ? ".tsx" : ".ts"}` }));
    } }],
  });
  server=createServer((req,res)=>{res.setHeader('content-type',req.url==='/app.mjs'?'text/javascript':'text/html');res.end(req.url==='/app.mjs'?result.outputFiles[0].contents:'<!doctype html><html><meta charset="utf-8"><body><div id="root"></div><script type="module" src="/app.mjs"></script></body></html>');});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;
  try{browser=await chromium.launch({headless:true});}catch{browser=await chromium.launch({headless:true,channel:'chrome'});}
});
afterEach(async()=>{await context?.close();assert.deepEqual(errors,[]);});
after(async()=>{await browser?.close();if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});
async function open(query=''){errors=[];context=await browser.newContext();await context.route('**/*',route=>route.request().url().startsWith(origin+'/')?route.continue():route.abort());page=await context.newPage();page.setDefaultTimeout(4000);page.on('pageerror',error=>errors.push(error.message));await page.goto(`${origin}/?${query}`);await page.locator('#root').waitFor({state:'attached'});}
async function application(query=''){await open(query);await page.getByRole('button',{name:'Open private application',exact:true}).click();await page.getByLabel('Applicant name',{exact:true}).waitFor();}
const section=name=>page.getByRole('button',{name:new RegExp(`^[1-5]\\. ${name}$`)}).click();
async function choose(label,value){await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click();}
test('local mode and unauthorized roles never load or collect private applicant data',async()=>{for(const query of ['local=1','role=operations','role=partner','unrestricted=1','outofscope=1']){await open(query);await page.waitForTimeout(40);assert.equal(await page.getByRole('button',{name:'Open private application',exact:true}).count(),0);assert.equal(await page.locator('input').count(),0);assert.deepEqual(await page.evaluate(()=>window.jvRequests),[]);await context.close();}});
test('opens only on demand, masks identity fields, and saves privately with explicit scope/version',async()=>{await open();assert.deepEqual(await page.evaluate(()=>window.jvRequests),[]);await page.getByRole('button',{name:'Open private application',exact:true}).click();await page.getByLabel('Applicant name',{exact:true}).fill('Fictional New Applicant');for(const label of ['Date of birth','Social Security number','Driver’s license'])assert.equal(await page.getByLabel(label,{exact:true}).getAttribute('type'),'password');await page.getByRole('button',{name:'Reveal social security number',exact:true}).click();assert.equal(await page.getByLabel('Social Security number',{exact:true}).getAttribute('type'),'text');await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByText('Private application saved.',{exact:true}).waitFor();const sent=await page.evaluate(()=>window.jvRequests.at(-1));assert.equal(sent.action,'save');assert.equal(sent.data.expectedVersion,0);assert.equal(sent.data.payload.applicants[0].name,'Fictional New Applicant');assert.deepEqual(sent.context,{workspaceId:'workspace-one',userId:'staff-one',companyId:'fictional-company'});assert.equal(await page.evaluate(()=>window.workspaceWrites),0);assert.deepEqual(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length})),{local:0,session:0});});
test('applicants retain separate values and verified originals attach to the selected applicant',async()=>{await application();await page.getByLabel('Applicant name',{exact:true}).fill('First Fictional Applicant');await page.getByRole('button',{name:'Add applicant',exact:true}).click();assert.equal(await page.getByLabel('Applicant name',{exact:true}).inputValue(),'');await page.getByRole('button',{name:'Fixture verified original',exact:true}).click();await choose('Current applicant','Applicant 1');assert.equal(await page.getByLabel('Applicant name',{exact:true}).inputValue(),'First Fictional Applicant');await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByText('Private application saved.',{exact:true}).waitFor();const saved=await page.evaluate(()=>window.readJvRecord());assert.equal(saved.payload.applicants[1].name,'Compared Fictional Applicant');assert.deepEqual(saved.payload.sourceDocumentIds,['restricted-original']);});
test('business formation and histories are guided and originals are company/restriction scoped',async()=>{await application();await section('Ownership & history');await choose('Ownership election','Own through a business');await page.getByText('A business still being formed cannot be submitted for review.',{exact:false}).waitFor();await page.getByRole('button',{name:'Add residence',exact:true}).click();await page.getByLabel('Residence 1 address',{exact:true}).fill('10 Fictional Street');await page.getByRole('button',{name:'Add employment',exact:true}).click();await page.getByLabel('Employment 1 employer',{exact:true}).fill('Retired');await section('Branding & documents');await page.getByText('Fictional restricted original.pdf · v1',{exact:true}).waitFor();assert.equal(await page.getByText(/Hidden/).count(),0);await section('Setup checklist');assert.equal(await page.locator('.jv-checklist-row').count(),17);await page.locator('.jv-checklist-row').first().locator('summary').click();await page.getByLabel('Partnership agreement evidence reference',{exact:true}).fill('Fictional reviewed agreement');await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByText('Private application saved.',{exact:true}).waitFor();const saved=await page.evaluate(()=>window.readJvRecord());assert.equal(saved.payload.applicants[0].residenceHistory[0].address,'10 Fictional Street');assert.equal(saved.payload.applicants[0].employmentHistory[0].employer,'Retired');assert.equal(saved.payload.steps[0].reference,'Fictional reviewed agreement');});
test('close and conflict reload require confirmation before discarding dirty input',async()=>{await application();await page.getByLabel('Applicant name',{exact:true}).fill('Unsaved Fictional Applicant');page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Close application',exact:true}).click();assert.equal(await page.getByLabel('Applicant name',{exact:true}).inputValue(),'Unsaved Fictional Applicant');await page.evaluate(()=>window.failJv=409);await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'Save draft',exact:true}).isDisabled(),true);page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Reload latest application',exact:true}).click();assert.equal(await page.getByLabel('Applicant name',{exact:true}).inputValue(),'Unsaved Fictional Applicant');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Reload latest application',exact:true}).click();await page.waitForFunction(()=>document.querySelector('input')?.value==='');await page.getByLabel('Applicant name',{exact:true}).fill('Unsaved Again');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Close application',exact:true}).click();assert.equal(await page.getByLabel('Applicant name',{exact:true}).count(),0);});
test('permission failure clears the private draft and never displays server error details',async()=>{await application();await page.getByLabel('Applicant name',{exact:true}).fill('Private Fictional Value');await page.evaluate(()=>window.failJv=403);await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('Applicant name',{exact:true}).count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/DO NOT DISPLAY|Private Fictional Value/);});
test('workspace/user/access changes destroy drafts and ignore stale pending results',async()=>{for(const patch of [{workspaceId:'workspace-two'},{access:{userId:'staff-two'}},{access:{version:2}}]){await application();await page.getByLabel('Applicant name',{exact:true}).fill('Old Private Applicant');await page.evaluate(()=>window.holdJv=true);await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.waitForFunction(()=>window.jvPending.length===1);await page.evaluate(patch=>window.changeJvContext(patch),patch);await page.getByRole('button',{name:'Open private application',exact:true}).waitFor();await page.evaluate(()=>window.jvPending.shift()());await page.waitForTimeout(20);assert.equal(await page.getByLabel('Applicant name',{exact:true}).count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/Old Private Applicant/);await context.close();}});
test('explicit submission and evidence acknowledgement record review independently of checklist completion',async()=>{await application('complete=1');await section('Review');await page.getByRole('button',{name:'Save and submit for review',exact:true}).click();await page.getByLabel('Review note',{exact:true}).fill('Compared fictional originals and complete five-year histories.');const review=page.getByRole('button',{name:'Mark application reviewed',exact:true});assert.equal(await review.isDisabled(),true);await page.getByRole('checkbox',{name:'I compared each applicant’s details and histories with the originals and reviewed the ownership election.',exact:true}).check();await review.click();await page.getByText('Recorded review',{exact:true}).waitFor();let saved=await page.evaluate(()=>window.readJvRecord());assert.equal(saved.status,'Reviewed');assert.ok(saved.payload.steps.every(step=>step.status==='Not started'));await page.getByRole('button',{name:'Reopen as draft',exact:true}).click();await page.getByRole('button',{name:'Save and submit for review',exact:true}).waitFor();saved=await page.evaluate(()=>window.readJvRecord());assert.equal(saved.status,'Draft');assert.deepEqual(Object.keys((await page.evaluate(()=>window.jvRequests.at(-1))).data),['expectedVersion']);});
