// Exercises the actual Edge handler with fictional authentication and RPC transport.
import test, { beforeEach, after } from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const workspaceId='11111111-1111-4111-8111-111111111111', actorId='22222222-2222-4222-8222-222222222222', sessionId='33333333-3333-4333-8333-333333333333';
const companyId='fictional-jv', privateMarker='PRIVATE-FIXTURE-ERROR';
let handler,fixture;const originalDeno=globalThis.Deno;const ok=data=>({data,error:null});
const client={
 auth:{getUser:async()=>fixture.auth?ok({user:{id:actorId,email:'owner@example.test',email_confirmed_at:fixture.confirmed?'2026-01-01':null,is_anonymous:false}}):{data:{user:null},error:{message:'invalid'}},getClaims:async()=>ok({claims:{sub:actorId,session_id:sessionId,aal:fixture.aal}})},
 from(table){const filters=[];return {select(){return this},eq(k,v){filters.push([k,v]);return this},async maybeSingle(){assert.equal(table,'title_memberships');const m={workspace_id:workspaceId,user_id:actorId,active:fixture.active,role:fixture.role,restricted_access:fixture.restricted,all_companies:fixture.allCompanies,company_ids:fixture.companyIds,partner_members:[],version:7};return ok(filters.every(([k,v])=>m[k]===v)?m:null)},async single(){assert.equal(table,'title_workspaces');return ok({id:workspaceId,state:{companies:[{id:companyId}],documents:[]},revision:5})}}},
 async rpc(name,args){if(name==='title_security_state')return ok(fixture.security);assert.equal(name,'title_jv_intake');fixture.calls.push(structuredClone(args));if(fixture.rpcThrow)throw new Error(privateMarker);if(fixture.rpcCode)return {data:null,error:{code:fixture.rpcCode,message:privateMarker}};assert.equal(args.p_workspace,workspaceId);assert.equal(args.p_actor,actorId);assert.equal(args.p_access_version,7);if(args.p_action==='load')return ok(fixture.saved);const p=args.p_input;fixture.saved={companyId,version:(fixture.saved?.version??0)+1,payload:p.payload,status:p.status,reviewNote:p.reviewNote,updatedAt:'2026-09-24T12:00:00Z',updatedBy:actorId,reviewedAt:null,reviewedBy:null};return ok(fixture.saved)}
};
globalThis.__jvHttpClient=client;
globalThis.Deno={env:{get:n=>n==='SUPABASE_URL'?'https://synthetic.example.test':'synthetic-service-only'},serve:fn=>{handler=fn}};
const compiled=await build({entryPoints:['../supabase/functions/title-api/index.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'jv-fictional-service',setup(b){b.onResolve({filter:/^npm:@supabase\/supabase-js@/},()=>({path:'client',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createClient=()=>globalThis.__jvHttpClient;'}))}}]});
await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].contents).toString('base64')}`);
beforeEach(()=>{fixture={auth:true,confirmed:true,aal:'aal2',active:true,role:'owner',restricted:true,allCompanies:true,companyIds:[companyId],calls:[],saved:null,rpcCode:null,rpcThrow:false,security:{session_valid:true,password_change_required:false,has_totp:true,session_totp:true}}});
after(()=>{globalThis.Deno=originalDeno;delete globalThis.__jvHttpClient});
async function post(action='load',data={},raw){const r=await handler(new Request(`https://synthetic.example.test/functions/v1/title-api/jv-intake/${action}`,{method:'POST',headers:{Authorization:'Bearer synthetic','Content-Type':'application/json'},body:raw??JSON.stringify({workspaceId,companyId,...data})}));return {status:r.status,headers:r.headers,body:await r.json()}}
const noPrivate=result=>assert.ok(!JSON.stringify(result.body).includes(privateMarker));
test('private intake is no-store, company bound, and saved outside workspace mutations',async()=>{const r=await post();assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(r.body.version,0);assert.equal(r.body.payload.steps.length,17);const saved=await post('save',{expectedVersion:0,payload:r.body.payload});assert.equal(saved.status,200);assert.equal(saved.body.version,1);assert.ok(fixture.calls.every(c=>c.p_company===companyId));});
for(const role of ['operations','finance','viewer','partner'])test(`${role} cannot read or save private JV applications`,async()=>{fixture.role=role;for(const action of ['load','save','review'])assert.equal((await post(action)).status,403);assert.equal(fixture.calls.length,0)});
for(const role of ['owner','admin','onboarding'])test(`${role} requires restricted access and company assignment`,async()=>{fixture.role=role;fixture.restricted=false;assert.equal((await post()).status,403);fixture.restricted=true;fixture.allCompanies=false;fixture.companyIds=[];assert.equal((await post()).status,403);assert.equal(fixture.calls.length,0)});
for(const [label,change,expected] of [
 ['signed out',f=>f.auth=false,401],['email unverified',f=>f.confirmed=false,403],['MFA incomplete',f=>f.aal='aal1',403],['revoked',f=>f.active=false,403],['startup password',f=>f.security.password_change_required=true,403]
])test(`${label} blocks intake before private reads`,async()=>{change(fixture);assert.equal((await post()).status,expected);assert.equal(fixture.calls.length,0)});
test('cross-workspace and unknown company deny before private reads',async()=>{assert.equal((await post('load',{workspaceId:'99999999-9999-4999-8999-999999999999'})).status,403);assert.equal((await post('load',{companyId:'another-company'})).status,403);assert.equal(fixture.calls.length,0)});
test('bounded streaming body rejects excess bytes even without Content-Length',async()=>{const chunks=[new TextEncoder().encode('{"x":"'),new Uint8Array(140000).fill(97)];const req=new Request('https://synthetic.example.test/functions/v1/title-api/jv-intake/save',{method:'POST',duplex:'half',headers:{Authorization:'Bearer synthetic'},body:new ReadableStream({pull(c){const x=chunks.shift();if(x)c.enqueue(x);else c.close()}})});const response=await handler(req);assert.equal(response.status,413);assert.match((await response.json()).error,/128 KiB/);assert.equal(fixture.calls.length,0)});
test('malformed request and review with missing application return safe errors',async()=>{assert.equal((await post('load',{},'[]')).status,400);assert.equal((await post('load',{},'{bad')).status,400);const loaded=await post();assert.equal((await post('submit',{expectedVersion:0,payload:loaded.body.payload})).status,400)});
for(const [code,status]of[['42501',403],['PT409',409],['40001',409],['XX000',503]])test(`RPC ${code} is sanitized`,async()=>{fixture.rpcCode=code;const r=await post();assert.equal(r.status,status);noPrivate(r)});
test('transport errors do not echo submitted or stored applicant material',async()=>{fixture.rpcThrow=true;const r=await post();assert.equal(r.status,503);noPrivate(r)});
