import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const compiled = await build({ entryPoints:['lib/backend/jv-portal-http.ts'], bundle:true, write:false, format:'esm', platform:'node' });
const { jvPortalPublicHttp } = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].contents).toString('base64')}`);
const gatewayKey='fictional-gateway-secret-with-more-than-32-bytes', token='t'.repeat(43);
const url='https://fictional.example.test/functions/v1/title-jv-public';
function fixture(){const calls=[];return {calls,gatewayKey,context:{portalUrl:'https://applications.example.test',mailConfigured:false,sendEmail:async()=>{throw Error('Must not send')},rpc:async(name,input)=>{calls.push({name,input});throw Error('PRIVATE-SERVER-MARKER')},storage:{upload:async()=>{throw Error('Must not upload')},download:async()=>{throw Error('Must not download')},remove:async()=>{throw Error('Must not delete')}}}};}
const req=(path='load',data={session:token},headers={})=>new Request(`${url}/${path}`,{method:'POST',headers:{'Content-Type':'application/json','X-JV-Gateway-Key':gatewayKey,'X-JV-Client-IP':'192.0.2.1',...headers},body:JSON.stringify(data)});
test('unconfigured and unknown gateways deny before protocol or storage',async()=>{for(const key of ['',undefined,'short','x'.repeat(60)]){const f=fixture();if(key===undefined)f.gatewayKey=undefined;const r=await jvPortalPublicHttp(req('load',{session:token},{'X-JV-Gateway-Key':key??gatewayKey}),f);assert.ok([403,503].includes(r.status));assert.equal(f.calls.length,0);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.match(r.headers.get('cache-control'),/no-store/);}});
test('only fixed recipient actions and POST JSON are exposed',async()=>{for(const path of ['staff/list','workspace','load?token=leaked','load/','../title-api/workspace']){const f=fixture(),r=await jvPortalPublicHttp(req(path),f);assert.equal(r.status,404);assert.equal(f.calls.length,0);}let f=fixture();assert.equal((await jvPortalPublicHttp(new Request(`${url}/load`,{headers:{'X-JV-Gateway-Key':gatewayKey,'X-JV-Client-IP':'192.0.2.1'}}),f)).status,405);assert.equal((await jvPortalPublicHttp(req('load',{session:token},{'Content-Type':'text/plain'}),f)).status,415);});
test('trusted gateway IP is mandatory and capability bodies cannot inject scope or actions',async()=>{for(const ip of ['', '192.0.2.1, 192.0.2.2','private']){const f=fixture();assert.equal((await jvPortalPublicHttp(req('load',{session:token},{'X-JV-Client-IP':ip}),f)).status,403);assert.equal(f.calls.length,0);}for(const data of [{session:token,workspaceId:'other'},{session:token,companyId:'other'},{session:token,action:'apply'},{session:'bad'}]){const f=fixture();assert.ok([400,403].includes((await jvPortalPublicHttp(req('load',data),f)).status));assert.equal(f.calls.length,0);}});
test('valid request hashes credentials and sanitizes database failure',async()=>{const f=fixture(),r=await jvPortalPublicHttp(req(),f);assert.equal(r.status,503);assert.equal(f.calls.length,1);assert.doesNotMatch(JSON.stringify(f.calls),new RegExp(token));assert.match(f.calls[0].input.p_credential,/^[a-f0-9]{64}$/);assert.doesNotMatch(await r.text(),/PRIVATE-SERVER-MARKER/);});
test('chunked oversized JSON is stopped before protocol',async()=>{const f=fixture();const request=new Request(`${url}/save`,{method:'POST',duplex:'half',headers:{'Content-Type':'application/json','X-JV-Gateway-Key':gatewayKey,'X-JV-Client-IP':'192.0.2.1'},body:new ReadableStream({start(c){c.enqueue(new Uint8Array(131073));c.close();}})});assert.equal((await jvPortalPublicHttp(request,f)).status,413);assert.equal(f.calls.length,0);});
test('malformed JSON and multipart duplicate fields are rejected',async()=>{const f=fixture();let request=req();request=new Request(request,{body:'{bad'});assert.equal((await jvPortalPublicHttp(request,f)).status,400);const form=new FormData();form.append('session',token);form.append('session',token);form.append('file',new File(['fictional'],'fake.txt',{type:'text/plain'}));assert.equal((await jvPortalPublicHttp(new Request(`${url}/upload`,{method:'POST',headers:{'X-JV-Gateway-Key':gatewayKey,'X-JV-Client-IP':'192.0.2.1'},body:form}),f)).status,400);assert.equal(f.calls.length,0);});
test('missing email service never creates or sends a challenge',async()=>{const f=fixture();const r=await jvPortalPublicHttp(req('start',{token}),f);assert.equal(r.status,503);assert.equal(f.calls.length,0);});
