// Actual staff Edge handler; synthetic auth/RPC/storage and intercepted provider transport only.
import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const workspaceId='11111111-1111-4111-8111-111111111111',actorId='22222222-2222-4222-8222-222222222222',sessionId='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',attachmentId='55555555-5555-4555-8555-555555555555',jobId='66666666-6666-4666-8666-666666666666';
const companyId='fictional-jv',privateMarker='PRIVATE-FIXTURE-ERROR',bytes=new TextEncoder().encode('FICTIONAL ORIGINAL');
let fixture,handler;const oldDeno=globalThis.Deno,oldFetch=globalThis.fetch,ok=data=>({data,error:null});
const sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');
const record=()=>({id,recipientName:'Fictional Recipient',email:'recipient@example.test',status:'Draft',version:4,expiresAt:'2026-10-01T00:00:00Z',submittedAt:null,deliveryStatus:'not_sent',appliedVersion:null,needsMerge:false,notificationStatus:'not_sent'});
const client={auth:{getUser:async()=>fixture.auth?ok({user:{id:actorId,email:'staff@example.test',email_confirmed_at:fixture.confirmed?'2026-01-01':null,is_anonymous:fixture.anonymous}}):{data:{user:null},error:{message:'invalid'}},getClaims:async()=>ok({claims:{sub:actorId,session_id:sessionId,aal:fixture.aal}})},from(table){const filters=[];return {select(){return this},eq(k,v){filters.push([k,v]);return this},async maybeSingle(){assert.equal(table,'title_memberships');const membership={workspace_id:workspaceId,user_id:actorId,active:fixture.active,role:fixture.role,restricted_access:fixture.restricted,all_companies:fixture.allCompanies,company_ids:fixture.companyIds,partner_members:[],version:7};return ok(filters.every(([k,v])=>membership[k]===v)?membership:null)},async single(){assert.equal(table,'title_workspaces');return ok({id:workspaceId,state:{companies:[{id:companyId,name:'Fictional Company'}],documents:[]},revision:5})}}},async rpc(name,args){if(name==='title_security_state'){fixture.securityCalls++;return ok(fixture.security)}assert.equal(name,'title_jv_portal_staff');fixture.calls.push(structuredClone(args));if(fixture.rpcThrow)throw new Error(privateMarker);if(fixture.rpcCode)return {data:null,error:{code:fixture.rpcCode,message:privateMarker}};if(args.p_action==='list')return ok({requests:[record()]});if(args.p_action==='create')return ok({request:record(),tokenIssued:true});if(args.p_action==='send')return ok({request:record(),job:{jobId,to:'recipient@example.test',recipientName:'Fictional Recipient',companyName:'Fictional Company'}});if(args.p_action==='delivery-result')return ok({request:{...record(),deliveryStatus:args.p_input.status}});if(args.p_action==='download-attachment'){if(fixture.rejectReauth&&fixture.calls.filter(c=>c.p_action==='download-attachment').length===2)return {data:null,error:{code:'42501',message:privateMarker}};return ok({objectPath:'fictional/own-original',attachment:{id:attachmentId,name:'Fictional original.txt',mime:'text/plain',bytes:bytes.length,sha256}})}return ok({request:record()})},storage:{from(bucket){assert.equal(bucket,'title-documents');return {async download(path){fixture.downloads.push(path);return ok(new Blob([fixture.corruptBytes?new TextEncoder().encode('ALTERED ORIGINAL'):bytes],{type:'text/plain'}))}}}}};
globalThis.__portalStaffHttpClient=client;globalThis.Deno={env:{get:name=>({SUPABASE_URL:'https://synthetic.example.test',SUPABASE_SERVICE_ROLE_KEY:'fictional-service',RESEND_API_KEY:'fictional-email-key',TITLE_APPLICATION_EMAIL_FROM:'Fictional <no-reply@example.test>',TITLE_APPLICATION_PORTAL_URL:'https://fictional-portal.example.test',JV_PORTAL_GATEWAY_KEY:'fictional-gateway-key'}[name])},serve:fn=>handler=fn};
globalThis.fetch=async(url,init)=>{assert.equal(String(url),'https://api.resend.com/emails');fixture.emailCalls.push(JSON.parse(init.body));return Response.json({id:'fictional-provider-acceptance'})};
const bundle=await build({entryPoints:['../supabase/functions/title-api/index.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'fictional-portal-http',setup(b){b.onResolve({filter:/^npm:@supabase\/supabase-js@/},()=>({path:'client',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createClient=()=>globalThis.__portalStaffHttpClient'}))}}]});await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].contents).toString('base64')}`);
beforeEach(()=>{fixture={auth:true,confirmed:true,anonymous:false,aal:'aal2',active:true,role:'owner',restricted:true,allCompanies:true,companyIds:[companyId],calls:[],downloads:[],emailCalls:[],securityCalls:0,rpcCode:null,rpcThrow:false,security:{session_valid:true,password_change_required:false,has_totp:true,session_totp:true}}});after(()=>{globalThis.Deno=oldDeno;globalThis.fetch=oldFetch;delete globalThis.__portalStaffHttpClient});
const actions={list:{},create:{recipientName:'Fictional Recipient',email:'recipient@example.test',requestId:id},send:{id,expectedVersion:4},'download-attachment':{id,attachmentId}};
async function post(action='list',data={},raw,authorized=true){const r=await handler(new Request(`https://synthetic.example.test/functions/v1/title-api/jv-portal/${action}`,{method:'POST',headers:{...(authorized?{Authorization:'Bearer fictional'}:{}),'Content-Type':'application/json'},body:raw??JSON.stringify({workspaceId,companyId,...actions[action],...data})}));const binary=r.headers.get('content-type')==='text/plain';return {status:r.status,headers:r.headers,body:binary?await r.text():await r.json()}}
const noPrivate=r=>assert.ok(!JSON.stringify(r.body).includes(privateMarker));
test('staff list and preparation are private scoped RPCs and preparation sends no email',async()=>{
 const listed=await post();assert.equal(listed.status,200);assert.match(listed.headers.get('cache-control'),/no-store/);assert.equal(listed.body.mailConfigured,true);const created=await post('create');assert.equal(created.status,200);assert.match(created.body.link,/^https:\/\/fictional-portal.example.test\/#[-_A-Za-z0-9]{43}$/);assert.equal(fixture.emailCalls.length,0);assert.equal(fixture.securityCalls,2);assert.ok(fixture.calls.every(c=>c.p_workspace===workspaceId&&c.p_company===companyId&&c.p_actor===actorId&&c.p_access_version===7));assert.match(fixture.calls.find(c=>c.p_action==='create').p_input.tokenHash,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(fixture.calls).includes(created.body.link.split('#')[1]),false);
});
test('explicit send invokes only intercepted email transport and records provider acceptance',async()=>{
 const r=await post('send');assert.equal(r.status,200);assert.equal(r.body.deliveryStatus,'sent');assert.equal(fixture.emailCalls.length,1);assert.deepEqual(fixture.emailCalls[0].to,['recipient@example.test']);assert.deepEqual(fixture.calls.map(c=>c.p_action),['send','delivery-result']);
});
for(const role of ['owner','admin','onboarding'])test(`${role} can use staff portal only with restricted access and company assignment`,async()=>{
 fixture.role=role;fixture.allCompanies=false;assert.equal((await post()).status,200);fixture.restricted=false;assert.equal((await post()).status,403);fixture.restricted=true;fixture.companyIds=[];assert.equal((await post()).status,403);assert.equal(fixture.calls.length,1);
});
for(const role of ['operations','finance','viewer','partner'])test(`${role} cannot list, create, send or download recipient applications`,async()=>{
 fixture.role=role;for(const action of Object.keys(actions))assert.equal((await post(action)).status,403);assert.equal(fixture.calls.length,0);assert.equal(fixture.emailCalls.length,0);assert.equal(fixture.downloads.length,0);
});
for(const [label,change,status]of[['signed out',f=>f.auth=false,401],['unverified email',f=>f.confirmed=false,403],['anonymous',f=>f.anonymous=true,403],['MFA incomplete',f=>f.aal='aal1',403],['revoked session',f=>f.security.session_valid=false,401],['startup password',f=>f.security.password_change_required=true,403],['MFA absent',f=>{f.security.has_totp=false;f.security.session_totp=false},403],['session TOTP absent',f=>f.security.session_totp=false,403],['membership revoked',f=>f.active=false,403]])test(`${label} stops every staff portal operation before private RPC`,async()=>{
 change(fixture);for(const action of Object.keys(actions))assert.equal((await post(action)).status,status);assert.equal(fixture.calls.length,0);assert.equal(fixture.emailCalls.length,0);assert.equal(fixture.downloads.length,0);
});
test('staff routes are never public and reject cross-workspace or unknown company',async()=>{
 for(const action of Object.keys(actions))assert.equal((await post(action,{},undefined,false)).status,401);assert.equal((await post('list',{workspaceId:'99999999-9999-4999-8999-999999999999'})).status,403);assert.equal((await post('list',{companyId:'other-company'})).status,403);assert.equal(fixture.calls.length,0);
});
test('128 KiB streaming route bound holds without Content-Length',async()=>{
 const chunks=[new TextEncoder().encode('{"notes":"'),new Uint8Array(131073).fill(97)];const response=await handler(new Request('https://synthetic.example.test/functions/v1/title-api/jv-portal/create',{method:'POST',duplex:'half',headers:{Authorization:'Bearer fictional'},body:new ReadableStream({pull(c){const chunk=chunks.shift();if(chunk)c.enqueue(chunk);else c.close()}})}));assert.equal(response.status,413);assert.match((await response.json()).error,/128 KiB/);assert.equal(fixture.calls.length,0);
});
test('malformed bodies and public capability action names cannot enter staff RPC',async()=>{
 for(const raw of ['[]','null','{bad'])assert.equal((await post('list',{},raw)).status,400);for(const action of ['start','verify','save','submit'])assert.equal((await post(action)).status,400);assert.equal(fixture.calls.length,0);
});
test('original download returns private binary bytes with safe headers and a second authorization check',async()=>{
 const r=await post('download-attachment');assert.equal(r.status,200);assert.equal(r.body,'FICTIONAL ORIGINAL');assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.match(r.headers.get('content-disposition'),/^attachment;/);assert.deepEqual(fixture.downloads,['fictional/own-original']);assert.deepEqual(fixture.calls.map(c=>c.p_action),['download-attachment','download-attachment']);assert.ok(fixture.calls.every(c=>c.p_input.id===id&&c.p_input.attachmentId===attachmentId));
});
test('revocation during storage download and changed original bytes both fail closed',async()=>{
 fixture.rejectReauth=true;const denied=await post('download-attachment');assert.equal(denied.status,403);noPrivate(denied);fixture.rejectReauth=false;fixture.corruptBytes=true;const altered=await post('download-attachment');assert.equal(altered.status,503);noPrivate(altered);assert.notEqual(altered.body,'ALTERED ORIGINAL');
});
for(const [code,status]of[['42501',403],['PT409',409],['40001',409],['22023',400],['PT429',429],['XX000',503]])test(`staff RPC ${code} is redacted`,async()=>{fixture.rpcCode=code;const r=await post();assert.equal(r.status,status);noPrivate(r)});
test('transport exceptions never echo applicant data or private backend detail',async()=>{fixture.rpcThrow=true;const r=await post();assert.equal(r.status,503);noPrivate(r)});
