import test,{before,after,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
const web=fileURLToPath(new URL('../',import.meta.url));let browser,server,origin,context,page;let errors=[];
before(async()=>{
 const result=await build({absWorkingDir:web,write:false,bundle:true,platform:'browser',format:'esm',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},stdin:{resolveDir:web,loader:'tsx',contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {JVApplicationReader} from './components/title/jv-application-reader';import {newJVApplicant} from './lib/title/jv-application';const applicant=newJVApplicant('fictional-person');window.fills=[];createRoot(document.getElementById('root')).render(<JVApplicationReader companyId="fictional-company" applicant={applicant} onFill={(patch,source)=>window.fills.push({patch,source})}/>);`},plugins:[{name:'fictional-jv-reader',setup(b){
 b.onResolve({filter:/^@\/lib\/title\/store$/},()=>({path:'store',namespace:'fixture'}));
 b.onResolve({filter:/^@\/lib\/title\/source-field-reader$/},()=>({path:'reader',namespace:'fixture'}));
 b.onResolve({filter:/^\.\/documents$/},()=>({path:'preview',namespace:'fixture'}));
 b.onLoad({filter:/^store$/,namespace:'fixture'},()=>({loader:'js',resolveDir:web,contents:`import {useSyncExternalStore} from 'react';const doc={id:'fictional-app',companyId:'fictional-company',name:'Fictional application.pdf',category:'Applications',visibility:'Restricted',version:1,assetId:'fictional-asset',mime:'application/pdf'};let state={s:{documents:[doc,{...doc,id:'wrong-company',companyId:'elsewhere',name:'Wrong company.pdf'},{...doc,id:'public-app',visibility:'Internal',name:'Unrestricted.pdf'},{...doc,id:'order-app',orderId:'file-1',name:'Title file.pdf'}]},connection:{workspaceId:'workspace',access:{userId:'person',version:1}}};const listeners=new Set();window.changeOriginal=()=>{state={...state,s:{documents:[{...doc,version:2,assetId:'new-asset'}]}};listeners.forEach(fn=>fn())};export const useWorkspace=()=>useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>state);export const getAsset=async()=>new Blob(['fictional'],{type:'application/pdf'});` }));
 b.onLoad({filter:/^reader$/,namespace:'fixture'},()=>({loader:'js',contents:`export const readFieldSource=async()=>({status:'complete',totalPages:2,unreadPages:[],pages:[{page:2,text:'Name: Avery Example\\nSSN: 123-45-6789',method:'pdf-text'}],issues:[],notes:[]});`}));
 b.onLoad({filter:/^preview$/,namespace:'fixture'},()=>({loader:'tsx',resolveDir:web,contents:`import React from 'react';export const DocumentPreview=({initialPage,onClose})=><div role="dialog"><p>Original page {initialPage}</p><button onClick={onClose}>Close original</button></div>;`}));
 }}]});
 server=createServer((req,res)=>{res.setHeader('content-type',req.url==='/app.js'?'text/javascript':'text/html');res.end(req.url==='/app.js'?result.outputFiles[0].contents:'<div id="root"></div><script type="module" src="/app.js"></script>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 try{browser=await chromium.launch({headless:true})}catch{browser=await chromium.launch({channel:'chrome',headless:true})}
});
afterEach(async()=>{await context?.close();assert.deepEqual(errors,[])});after(async()=>{await browser?.close();server?.closeAllConnections();if(server)await new Promise(r=>server.close(r))});
async function open(){errors=[];context=await browser.newContext();page=await context.newPage();page.setDefaultTimeout(4000);page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await page.goto(origin);await page.getByRole('button',{name:'Read an uploaded application',exact:true}).click();}
async function scan(){await page.getByRole('combobox',{name:'Application original'}).selectOption('fictional-app');await page.getByRole('button',{name:'Find applicant fields',exact:true}).click();await page.getByText('2 labeled suggestions.',{exact:false}).waitFor();}
test('application reader lists only this company restricted application originals',async()=>{await open();const options=await page.getByRole('combobox',{name:'Application original'}).locator('option').allTextContents();assert.equal(options.length,2);assert.ok(options[1].includes('Fictional application'));});
test('candidate is added only after explicit original/applicant confirmation; evidence opens exact physical page',async()=>{await open();await scan();await page.locator('summary').filter({hasText:'Applicant name'}).click();const use=page.getByRole('button',{name:'Use reviewed applicant name',exact:true});assert.equal(await use.isDisabled(),true);await page.getByRole('button',{name:'View original page 2',exact:true}).first().click();await page.getByRole('dialog').getByText('Original page 2').waitFor();await page.getByRole('button',{name:'Close original'}).click();await page.getByRole('checkbox',{name:'I checked applicant name on page 2 and it belongs to this applicant.',exact:true}).check();await use.click();assert.deepEqual(await page.evaluate(()=>window.fills),[{patch:{name:'Avery Example'},source:'fictional-app'}]);});
test('rerun and original replacement clear prior confirmations and extracted private text',async()=>{await open();await scan();await page.locator('summary').filter({hasText:'Social Security number'}).click();await page.getByRole('checkbox',{name:'I checked social security number on page 2 and it belongs to this applicant.',exact:true}).check();await page.getByRole('button',{name:'Find applicant fields',exact:true}).click();await page.locator('summary').filter({hasText:'Social Security number'}).click();const use=page.getByRole('button',{name:'Use reviewed social security number',exact:true});assert.equal(await use.isDisabled(),true);await page.evaluate(()=>window.changeOriginal());assert.equal(await page.getByRole('button',{name:'Use reviewed social security number',exact:true}).count(),0);assert.equal(await page.getByText('SSN: 123-45-6789',{exact:true}).count(),0);});
