import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
const bundle=await build({stdin:{contents:`export * from './lib/backend/missive-intake'; export {emptyWorkspace,projectWorkspace} from './lib/backend/workspace'; export {importMissiveText,parseMissiveMessage,previewMissiveMessage} from './lib/backend/missive-import';`,resolveDir:fileURLToPath(new URL('../',import.meta.url))},write:false,bundle:true,format:'esm',platform:'node',target:'es2022'});
const api=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text+'\n//# sourceURL=missive-intake-test.mjs').toString('base64')}`);
const route={id:'route:org:team:A',organizationId:'org',teamId:'team',teamName:'Production',companyId:'A',version:1,enabled:true,productionOnly:true,approvedAt:'2026-09-24',approvedBy:'owner@example.test'};
const input={routeId:route.id,revision:1,conversationId:'conversation',messageId:'message'};
const pdf=new TextEncoder().encode('%PDF-1.7\nSynthetic reviewed original\n%%EOF\n');
const conversation={id:'conversation',organization:{id:'org'},team:{id:'team'},subject:'Finals',last_activity_at:1789200000};
const raw={id:'message',type:'email',draft:false,conversation,subject:'Finals for 123 Main Street',body:'<p>Please review 123 Main Street.</p><img src="https://private.test/pixel"><script>SECRET</script>',delivered_at:1789200000,created_at:1789199999,updated_at:1789200001,from_field:{name:'Attorney',address:'attorney@example.test'},to_fields:[],attachments:[{id:'attachment',filename:'final.pdf',media_type:'application',sub_type:'pdf',size:pdf.length,url:'https://storage.test-files.net/file.pdf?PRIVATE_SIGNATURE'}]};
function fixture(){
 const vendor=[],credentials=[],commits=[],assets=[],stored={exists:true,configured:true,revision:3,verifiedAt:'2026-09-24T00:00:00Z',token:'PRIVATE_TOKEN'};
 const access={userId:crypto.randomUUID(),email:'operations@example.test',role:'operations',companyIds:['A'],allCompanies:false,restricted:true,version:7,partnerMembers:[]};
 const state=api.emptyWorkspace(access.email);
 state.companies=['A','B'].map(id=>({id,name:`Company ${id}`,initials:id,color:'blue',contact:'Person',email:'contact@example.test',location:'NC',jurisdiction:'NC',stage:'Onboarding',steps:[],members:[{name:'Member',share:100}]}));
 state.orders=['A','B'].map(companyId=>({id:`FILE-${companyId}`,companyId,address:'123 Main Street',client:'Buyer',type:'Purchase',underwriter:'WFG',owner:'Test',jurisdiction:'NC',status:'New',due:'2026-09-24',premium:100,rate:.4,month:'2026-09',fields:[],notes:'',exception:'',delivered:false,remitted:false}));
 const f={vendor,credentials,commits,assets,stored,raw:structuredClone(raw),binary:pdf,receipts:new Map()};
 f.ctx={workspaceId:'workspace',access,state,revision:10,integration:{status:'configured',config:{schemaVersion:2,revision:1,mappings:[structuredClone(route)]}},fallback:{},attachmentOrigins:['https://storage.test-files.net'],credential:async(routeId,revision,decrypt)=>{credentials.push({routeId,revision,decrypt});if(f.revoked)throw Object.assign(new Error('Access revoked'),{status:403});return{...stored,token:decrypt?stored.token:undefined};},fetcher:async(url,options)=>{vendor.push({url,options});assert.equal(options.method,'GET');assert.equal(options.body,undefined);assert.equal(options.redirect,'error');if(String(url).startsWith('https://storage.test-files.net')){assert.equal(options.headers.Authorization,undefined);f.onDownload?.();return new Response(f.binary,{headers:{'Content-Type':'application/pdf','Content-Length':String(f.binary.length)}});}f.onProvider?.(url);if(url.endsWith('/v1/conversations/conversation'))return new Response(JSON.stringify({conversations:[f.raw.conversation]}));if(url.endsWith('/v1/messages/message'))return new Response(JSON.stringify({messages:f.raw}));assert.fail(url);},receipt:async(id,hash)=>{const prior=f.receipts.get(id);if(prior&&prior!==hash)throw new Error('Request reused');return!!prior;},persistAsset:async artifact=>{f.onPersist?.();assets.push(artifact);},commit:async(next,d)=>{f.onCommit?.();commits.push(d);f.ctx.state=next;f.ctx.revision++;f.receipts.set(d.requestId,d.hash);return{revision:f.ctx.revision};}};return f;
}
const request=(f,action='preview',extra={})=>api.missiveIntakeRequest(`/missive-intake/${action}`,'POST',{...input,...extra},f.ctx);
async function reviewed(f){const p=await request(f);return{orderId:'FILE-A',kind:'Finals',fingerprint:p.message.fingerprint,requestId:crypto.randomUUID(),expectedRevision:f.ctx.revision};}
async function source(f){const selected=await reviewed(f);await request(f,'save-source',selected);return{...selected,requestId:crypto.randomUUID(),expectedRevision:f.ctx.revision,attachmentId:'attachment'};}
const status=n=>error=>error.status===n;
test('review exposes plaintext and a real source fingerprint with same-company suggestions only',async()=>{const f=fixture(),p=await request(f);assert.deepEqual(p.files.map(x=>x.id),['FILE-A']);assert.equal(p.files[0].suggested,true);assert.equal(p.existingOrderId,null);assert.match(p.message.fingerprint,/^[a-f0-9]{64}$/);assert.equal(p.message.html,undefined);assert.equal(p.message.body,'Please review 123 Main Street.');assert.doesNotMatch(JSON.stringify(p),/PRIVATE_TOKEN|PRIVATE_SIGNATURE|SECRET|<img/);assert.equal(f.commits.length,0);assert.equal(f.vendor.length,3);});
test('operations source save retains actual actor and original HTML bound to explicit same-company file',async()=>{const f=fixture(),selected=await reviewed(f),result=await request(f,'save-source',selected);assert.equal(result.revision,11);const mail=f.ctx.state.inbox[0];assert.equal(mail.companyId,'A');assert.equal(mail.orderId,'FILE-A');assert.equal(mail.missive.importedBy,f.ctx.access.email);assert.equal(JSON.parse(f.ctx.state.documents[0].text).html,raw.body);assert.equal(f.ctx.access.role,'operations');assert.equal(api.projectWorkspace(f.ctx.state,f.ctx.access).inbox.length,1);assert.equal(f.commits[0].credentialRevision,3);});
test('legacy importer and forged capability cannot grant operations access',async()=>{const f=fixture(),m=api.parseMissiveMessage({messages:raw},route,'message'),p=await api.previewMissiveMessage(m);for(const grant of [undefined,{}])await assert.rejects(api.importMissiveText(f.ctx.state,f.ctx.access,route,m,'FILE-A','Finals',p.fingerprint,crypto.randomUUID(),grant),status(403));});
test('general, shared including paused, unassigned and unsupported roles reject before decrypt or vendor GET',async()=>{for(const mutate of [f=>f.ctx.integration.config.mappings[0].productionOnly=false,f=>f.ctx.integration.config.mappings.push({...route,id:'route:org:team:B',companyId:'B',enabled:false}),f=>f.ctx.access.companyIds=['B'],...['viewer','finance','onboarding','partner'].map(role=>f=>f.ctx.access.role=role)]){const f=fixture();mutate(f);await assert.rejects(request(f),status(403));assert.equal(f.vendor.length,0);assert.equal(f.credentials.length,0);}});
test('owner can review general inbox and JSON cannot fabricate access',async()=>{const f=fixture();f.ctx.access.role='owner';f.ctx.access.allCompanies=true;f.ctx.integration.config.mappings[0].productionOnly=false;await request(f);await assert.rejects(request(f,'preview',{access:{role:'owner'}}),status(400));});
test('disabled and stale routing never fetch provider data',async()=>{for(const mutate of [f=>f.ctx.integration.status='disabled',f=>f.ctx.integration.config.revision=2]){const f=fixture();mutate(f);await assert.rejects(request(f));assert.equal(f.vendor.length,0);}});
test('cross-company and issued destination cannot save a valid preview',async()=>{for(const issued of [false,true]){const f=fixture(),selected=await reviewed(f);if(issued)f.ctx.state.orders[0].status='Issued';await assert.rejects(request(f,'save-source',{...selected,orderId:issued?'FILE-A':'FILE-B'}),status(409));assert.equal(f.commits.length,0);}});
test('changed/redacted body, draft, outgoing or moved email reject reviewed source',async()=>{for(const mutate of [f=>f.raw.body+='changed',f=>delete f.raw.body,f=>f.raw.draft=true,f=>f.raw.author={id:'staff'},f=>f.raw.conversation.team.id='another']){const f=fixture(),selected=await reviewed(f);mutate(f);await assert.rejects(request(f,'save-source',selected));assert.equal(f.commits.length,0);}});
test('revocation or credential rotation during GET rejects review',async()=>{for(const revoke of [f=>f.revoked=true,f=>f.stored.revision++]){const f=fixture();f.onProvider=()=>revoke(f);await assert.rejects(request(f));assert.equal(f.commits.length,0);}});
test('attachment bytes, deterministic identity and provenance persist once with GET-only vendor traffic',async()=>{const f=fixture(),selected=await source(f);await request(f,'save-attachment',selected);assert.equal(f.ctx.state.documents.length,2);const doc=f.ctx.state.documents.find(d=>d.providerSource);assert.equal(doc.providerSource.importedBy,f.ctx.access.email);assert.equal(doc.orderId,'FILE-A');assert.equal(f.assets.length,1);assert.deepEqual(f.assets[0].bytes,pdf);assert.equal(f.commits[1].action,'attachment');const calls=f.vendor.length;await request(f,'save-attachment',{...selected,requestId:crypto.randomUUID(),expectedRevision:f.ctx.revision});assert.equal(f.vendor.length,calls);assert.equal(f.assets.length,1);assert.equal(f.commits.length,2);});
test('source replay is idempotent and cannot move its original file',async()=>{const f=fixture(),selected=await reviewed(f);await request(f,'save-source',selected);const calls=f.vendor.length;await request(f,'save-source',selected);assert.equal(f.vendor.length,calls);assert.equal(f.ctx.state.inbox.length,1);f.ctx.state.orders.push({...f.ctx.state.orders[0],id:'ANOTHER'});await assert.rejects(request(f,'save-source',{...selected,requestId:crypto.randomUUID(),orderId:'ANOTHER',expectedRevision:f.ctx.revision}),/another destination/);});
test('bad/incomplete bytes or changed manifest never reach storage and preserve already saved source',async()=>{for(const mutate of [f=>f.binary=new Uint8Array(pdf.length),f=>f.binary=pdf.slice(0,4),f=>f.raw.attachments[0].size++]){const f=fixture(),selected=await source(f);mutate(f);await assert.rejects(request(f,'save-attachment',selected));assert.equal(f.assets.length,0);assert.equal(f.commits.length,1);assert.equal(f.ctx.state.inbox.length,1);}});
test('revocation, parent movement and body changes during download reject before storage',async()=>{for(const mutate of [f=>f.revoked=true,f=>f.raw.conversation.team.id='another',f=>f.raw.body+='changed']){const f=fixture(),selected=await source(f);f.onDownload=()=>mutate(f);await assert.rejects(request(f,'save-attachment',selected));assert.equal(f.assets.length,0);assert.equal(f.commits.length,1);}});
test('access revoked while private asset persists prevents state commit',async()=>{const f=fixture(),selected=await source(f);f.onPersist=()=>f.revoked=true;await assert.rejects(request(f,'save-attachment',selected),status(403));assert.equal(f.commits.length,1);});
test('stale workspace and unsupported mutations never commit',async()=>{const f=fixture(),selected=await reviewed(f);await assert.rejects(request(f,'save-source',{...selected,expectedRevision:9}),status(409));await assert.rejects(api.missiveIntakeRequest('/missive-intake/send','POST',input,f.ctx),status(405));await assert.rejects(api.missiveIntakeRequest('/missive-intake/save-source','GET',selected,f.ctx),status(405));assert.equal(f.commits.length,0);});

test('restricted and hidden title files are omitted from suggestions and cannot borrow a route grant',async()=>{const f=fixture();f.ctx.access.restricted=false;f.ctx.state.documents.push({id:'restricted-source',companyId:'A',orderId:'FILE-A',visibility:'Restricted',name:'private.pdf',category:'Closing package',version:1,date:'2026-09-24',size:'10 B',mime:'application/pdf',text:'secret'});const p=await request(f);assert.equal(p.files.length,0);await assert.rejects(request(f,'save-source',{orderId:'FILE-A',kind:'Finals',expectedRevision:10,fingerprint:p.message.fingerprint,requestId:crypto.randomUUID()}),status(403));assert.equal(f.commits.length,0);});

test('legacy optional workspace fields stay absent and unrelated persisted rows remain byte-for-byte equivalent',async()=>{
 const f=fixture();delete f.ctx.state.deliveries;delete f.ctx.state.ownershipHistory;delete f.ctx.state.orchestration;
 const before=structuredClone(f.ctx.state),selected=await reviewed(f);await request(f,'save-source',selected);
 const withoutRecords=s=>{const copy=structuredClone(s);delete copy.documents;delete copy.inbox;delete copy.user;return copy};
 assert.deepEqual(withoutRecords(f.ctx.state),withoutRecords(before));assert.equal(Object.hasOwn(f.ctx.state,'deliveries'),false);assert.equal(Object.hasOwn(f.ctx.state,'orchestration'),false);
 const saved=structuredClone(f.ctx.state);await request(f,'save-attachment',{...selected,attachmentId:'attachment',expectedRevision:f.ctx.revision,requestId:crypto.randomUUID()});
 assert.deepEqual(withoutRecords(f.ctx.state),withoutRecords(before));assert.deepEqual(f.ctx.state.inbox,saved.inbox);assert.deepEqual(f.ctx.state.documents.filter(d=>!d.providerSource),saved.documents);
});
