import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const wid='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',sid='33333333-3333-4333-8333-333333333333';
const routeId='route:org:team:A',json=data=>({data,error:null});let f,handler;
const priorDeno=globalThis.Deno,priorFetch=globalThis.fetch;
const client={auth:{getUser:async()=>json({user:{id:actor,email:'staff@example.test',email_confirmed_at:'2026-09-01',is_anonymous:false}}),getClaims:async()=>json({claims:{sub:actor,session_id:sid,aal:'aal2'}})},from(table){const filters=[];return{select(){return this},eq(k,v){filters.push([k,v]);return this},async maybeSingle(){if(table==='title_memberships')return json(f.active&&filters.every(([k,v])=>({workspace_id:wid,user_id:actor,active:true})[k]===v)?{role:f.role,company_ids:['A'],all_companies:false,restricted_access:true,active:true,version:7,partner_members:[]}:null);if(table==='title_workspaces')return json({id:wid,state:f.state,revision:f.revision});if(table==='title_integrations')return json({status:'configured',config:f.routing});if(table==='title_bootstrap')return json({workspace_id:wid});if(table==='title_command_receipts')return json(null);throw new Error(`Unexpected table ${table}`)},async single(){return this.maybeSingle()}}},async rpc(name,args){if(name==='title_security_state')return json({session_valid:true,password_change_required:false,has_totp:true,session_totp:true});if(name==='title_record_security_event')return json(null);f.rpc.push({name,args});if(name==='title_missive_feed_context'){assert.equal(args.p_actor,actor);assert.equal(args.p_access_version,7);if(f.revoked)return{error:{code:'42501',message:'PRIVATE_SQL_DETAILS'}};return json({exists:true,configured:true,revision:4,verifiedAt:'2026-09-24',...(args.p_decrypt?{token:'PRIVATE_TOKEN'}:{})})}if(name==='title_commit_missive_intake'){if(f.commitError)return{error:{code:f.commitError,message:'PRIVATE_SQL_DETAILS'}};f.state=args.p_state;f.revision++;return json({revision:f.revision})}throw new Error(`Unexpected RPC ${name}`)}};
globalThis.__intakeClient=client;
globalThis.Deno={env:{get:key=>({SUPABASE_URL:'https://synthetic.example.test',SUPABASE_SERVICE_ROLE_KEY:'PRIVATE_SERVICE'})[key]},serve:fn=>handler=fn};
globalThis.fetch=async(url,options)=>{f.gets.push({url,options});assert.equal(options.method,'GET');assert.equal(options.body,undefined);f.onFetch?.();const conversation={id:'conversation',organization:{id:'org'},team:{id:'team'},subject:'Received',last_activity_at:1789200000};return new Response(JSON.stringify(url.endsWith('/v1/messages/message')?{messages:{id:'message',type:'email',draft:false,subject:'Finals',body:'<p>Immutable reviewed email</p>',delivered_at:1789200000,created_at:1789199999,updated_at:1789200001,conversation,from_field:{name:'Sender',address:'sender@example.test'},to_fields:[],attachments:[]}}:{conversations:[conversation]}));};
const built=await build({stdin:{contents:`import '../supabase/functions/title-api/index.ts'; export {emptyWorkspace} from './lib/backend/workspace';`,resolveDir:fileURLToPath(new URL('../',import.meta.url))},write:false,bundle:true,format:'esm',platform:'node',target:'es2022',plugins:[{name:'client',setup(b){b.onResolve({filter:/^npm:@supabase\/supabase-js@/},()=>({path:'client',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createClient=()=>globalThis.__intakeClient;'}));}}]});
const {emptyWorkspace}=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text+'\n//# sourceURL=missive-intake-http.mjs').toString('base64')}`);
beforeEach(()=>{const state=emptyWorkspace('staff@example.test');state.companies=[{id:'A',name:'Company A',initials:'A',color:'blue',contact:'Person',email:'contact@example.test',location:'NC',jurisdiction:'NC',stage:'Onboarding',steps:[],members:[{name:'Person',share:100}]}];state.orders=[{id:'FILE-A',companyId:'A',address:'123 Main Street',client:'Buyer',type:'Purchase',underwriter:'WFG',owner:'Staff',jurisdiction:'NC',status:'New',due:'2026-09-24',premium:100,rate:.4,month:'2026-09',fields:[],notes:'',exception:'',delivered:false,remitted:false}];f={role:'operations',active:true,state,revision:10,rpc:[],gets:[],routing:{schemaVersion:2,revision:2,mappings:[{id:routeId,organizationId:'org',teamId:'team',teamName:'Production',companyId:'A',version:2,enabled:true,productionOnly:true,approvedAt:'2026-09-24',approvedBy:'owner@example.test'}]}}});
after(()=>{globalThis.Deno=priorDeno;globalThis.fetch=priorFetch;delete globalThis.__intakeClient});
async function request(action='preview',extra={},method='POST'){const response=await handler(new Request(`https://synthetic.example.test/functions/v1/title-api/missive-intake/${action}${method==='GET'?`?workspaceId=${wid}`:''}`,{method,headers:{Authorization:'Bearer SYNTHETIC_SESSION','Content-Type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify({workspaceId:wid,routeId,revision:2,conversationId:'conversation',messageId:'message',...extra})})}));return{status:response.status,body:await response.json(),cache:response.headers.get('cache-control')}}
async function reviewed(){const p=await request();assert.equal(p.status,200);return{orderId:'FILE-A',kind:'Finals',expectedRevision:10,fingerprint:p.body.message.fingerprint,requestId:crypto.randomUUID()}}
test('real authenticated handler passes exact actor/access/routing/credential CAS to narrow intake RPC',async()=>{const selected=await reviewed(),result=await request('save-source',selected);assert.equal(result.status,200);assert.equal(result.body.revision,11);assert.equal(result.cache,'no-store');const c=f.rpc.find(r=>r.name==='title_commit_missive_intake').args;assert.equal(c.p_actor,actor);assert.equal(c.p_access_version,7);assert.equal(c.p_credential_revision,4);assert.equal(c.p_mapping_id,routeId);assert.equal(c.p_mapping_version,2);assert.equal(c.p_routing_revision,2);assert.equal(c.p_expected,10);assert.equal(c.p_order,'FILE-A');assert.equal(c.p_company,'A');assert.equal(c.p_action,'source');assert.equal(c.p_email,'staff@example.test');assert.equal(f.state.inbox[0].missive.importedBy,'staff@example.test');assert.doesNotMatch(JSON.stringify(result),/PRIVATE_/)});
test('real handler denies finance/viewer/partner/onboarding and general operations route before decrypt',async()=>{for(const role of ['finance','viewer','partner','onboarding']){f.role=role;assert.equal((await request()).status,403)}f.role='operations';f.routing.mappings[0].productionOnly=false;assert.equal((await request()).status,403);assert.equal(f.rpc.length,0);assert.equal(f.gets.length,0)});
test('real handler rejects fabricated access or company destination without local commit',async()=>{assert.equal((await request('preview',{access:{role:'owner'}})).status,400);const selected=await reviewed();assert.equal((await request('save-source',{...selected,orderId:'FILE-B'})).status,409);assert.equal(f.rpc.some(r=>r.name==='title_commit_missive_intake'),false)});
test('real handler fails closed for revoked membership during provider read and sanitizes database conflict',async()=>{f.onFetch=()=>f.revoked=true;const failed=await request();assert.equal(failed.status,403);assert.doesNotMatch(JSON.stringify(failed),/PRIVATE_/);f.onFetch=null;f.revoked=false;const selected=await reviewed();f.commitError='PT409';const conflict=await request('save-source',selected);assert.equal(conflict.status,409);assert.doesNotMatch(JSON.stringify(conflict),/PRIVATE_SQL/);assert.equal(f.state.inbox.length,0)});
test('unsupported intake mutation and unauthenticated membership never contact Missive',async()=>{assert.equal((await request('send')).status,405);assert.equal((await request('preview',{},'GET')).status,405);f.active=false;assert.equal((await request()).status,403);assert.equal(f.gets.length,0)});
