// Real application handlers; only platform, authentication, storage and network are synthetic.
import test, { beforeEach } from "node:test";
import assert from "node:assert/strict";
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { Worker } from "node:worker_threads";
const wid="11111111-1111-4111-8111-111111111111", actor="22222222-2222-4222-8222-222222222222", email="fictional@example.test";
const ok=data=>({data,error:null});
let fixture,handler;
globalThis.Deno={env:{get:name=>({SUPABASE_URL:"https://synthetic.example.test",SUPABASE_SERVICE_ROLE_KEY:"synthetic",...fixture?.env})[name]},serve:fn=>{handler=fn}};
globalThis.__inputClient={
 auth:{getUser:async()=>fixture.auth?ok({user:{id:actor,email,email_confirmed_at:"2026-01-01"}}):{data:{user:null},error:{}},getClaims:async()=>ok({claims:{sub:actor,session_id:wid,aal:"aal2"}})},
 rpc:async (name,args)=>{
 if(name==="title_prepare_document_ingestion")return ok({workspaceId:wid,companyId:"A",policy:fixture.scanPolicy||"pending_setup"});
 if(name==="title_record_document_scan"){fixture.scanReceipts.push(args);if(fixture.receiptFailure)return {data:null,error:{code:"PT503",message:"Scan clearance unavailable"}};return ok(null)}
 if(name==="title_record_security_event"){fixture.audit.push(args);return ok(null)}
 assert.equal(name,"title_security_state");return ok({session_valid:true,password_change_required:false,has_totp:true,session_totp:true})},
 from(table){let inserted;const q={select(){return this},eq(){return this},async maybeSingle(){if(table==="title_memberships")return ok({role:fixture.role || "owner",all_companies:true,company_ids:[],restricted_access:true,partner_members:[],version:1});if(table==="title_assets")return ok(null);throw Error(table)},async single(){assert.equal(table,"title_workspaces");return ok({id:wid,revision:1,state:fixture.state})},insert(value){inserted=value;return this},then(resolve,reject){if(inserted)fixture.inserts.push(inserted);return Promise.resolve(ok(null)).then(resolve,reject)}};return q},
 storage:{from(){return {async upload(path,bytes,options){fixture.uploads.push({bytes:bytes.byteLength,options});return ok({})},async remove(){return ok({})}}}},
};
globalThis.__inputEnv={TITLE_ASSISTANT:{async fetch(url,init){fixture.proxyCalls.push({url,init});return Response.json({accepted:true})}}};
globalThis.__inputAgent=async(name,context,input)=>{fixture.agentCalls.push({name,context,input});return {threads:[],context}};
const bundled=await build({stdin:{resolveDir:fileURLToPath(new URL("../",import.meta.url)),contents:`import '../supabase/functions/title-api/index.ts'; export {POST as proxy} from './app/api/assistant/route'; export {default as assistant} from '../services/title-assistant/src/index'; export * from './lib/shared/request-body'; export * from './lib/shared/html-text'; export {emptyWorkspace} from './lib/backend/workspace';`},write:false,bundle:true,format:"esm",platform:"node",target:"es2022",plugins:[{name:"synthetic-input-boundaries",setup(b){b.onResolve({filter:/^(npm:@supabase\/supabase-js@.*|agents|cloudflare:workers)$/},a=>({path:a.path,namespace:"fixture"}));b.onLoad({filter:/.*/,namespace:"fixture"},a=>({contents:a.path==="agents"?'export class Agent{}; export async function getAgentByName(nameSpace,name){return {handle:(context,input)=>globalThis.__inputAgent(name,context,input)}}':a.path==="cloudflare:workers"?'export const env=globalThis.__inputEnv;':'export const createClient=()=>globalThis.__inputClient;'}))}}]});
const {proxy,assistant,readRequestBytes,readRequestText,htmlPlainText,emptyWorkspace}=await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].contents).toString("base64")}`);
beforeEach(()=>{const state=emptyWorkspace(email);state.companies=[{id:"A",name:"Fictional",initials:"A",color:"blue",contact:"Person",email,location:"Charlotte",jurisdiction:"NC",stage:"Onboarding",steps:[],members:[]}];fixture={auth:true,state,scanReceipts:[],audit:[],scanCalls:0,env:{},uploads:[],inserts:[],proxyCalls:[],agentCalls:[],verificationCalls:[]};globalThis.fetch=async(url,init)=>{fixture.verificationCalls.push({url,init});return Response.json({userId:actor,workspaceId:wid,companyId:"A",orderId:"",role:"owner",accessVersion:1,revision:1,sources:[],readableSourceIds:[],truncated:false})}});
function streamRequest(url,{bytes=64000,chunk=16000,headers={},slow=false,signal}={}){let read=0,canceled=false;const stream=new ReadableStream({pull(c){if(slow)return;if(read>=bytes){c.close();return}const n=Math.min(chunk,bytes-read);read+=n;c.enqueue(new Uint8Array(n).fill(65))},cancel(){canceled=true}},{highWaterMark:0});return {request:new Request(url,{method:"POST",headers:{Authorization:"Bearer synthetic",apikey:"synthetic",...(url.endsWith("/assets/upload")?{"Content-Type":"multipart/form-data; boundary=fixture"}:{}),...headers},body:stream,duplex:"half",signal}),get read(){return read},get canceled(){return canceled}}}
async function accelerated(fn){const original=globalThis.setTimeout;globalThis.setTimeout=(callback,ms,...args)=>original(callback,Math.min(ms,25),...args);try{return await fn()}finally{globalThis.setTimeout=original}}
const endpoints=[{name:"assistant proxy",url:"https://pilot.example.test/api/assistant",limit:12000,run:proxy},{name:"assistant service",url:"https://assistant.internal/assistant",limit:12000,run:req=>assistant.fetch(req,{TITLE_API_URL:"https://synthetic.example.test/functions/v1/title-api"})},{name:"API JSON",url:"https://synthetic.example.test/functions/v1/title-api/assistant/context",limit:8_000_000,run:req=>handler(req)},{name:"API multipart",url:"https://synthetic.example.test/functions/v1/title-api/assets/upload",limit:52_500_000,run:req=>handler(req)}];
for(const endpoint of endpoints){
 test(`${endpoint.name} cancels omitted/forged length at actual byte overrun`,async()=>{for(const contentLength of [undefined,"1"]){const input=streamRequest(endpoint.url,{bytes:endpoint.limit+2_000_000,chunk:Math.min(65536,endpoint.limit+1),headers:{...(contentLength===undefined?{}:{"content-length":contentLength})}});const r=await endpoint.run(input.request);assert.equal(r.status,413,await r.text());assert.equal(input.canceled,true);assert(input.read<=endpoint.limit+65536);assert(input.read<endpoint.limit+2_000_000)}assert.equal(fixture.uploads.length+fixture.inserts.length+fixture.proxyCalls.length+fixture.agentCalls.length+fixture.verificationCalls.length,0)});
 test(`${endpoint.name} rejects declared excess before reading`,async()=>{const input=streamRequest(endpoint.url,{headers:{"content-length":String(endpoint.limit+1)}});assert.equal((await endpoint.run(input.request)).status,413);assert.equal(input.read,0);assert.equal(input.canceled,true)});
 test(`${endpoint.name} stops slow input at a deadline and cancels`,async()=>{const input=streamRequest(endpoint.url,{slow:true});const r=await accelerated(()=>endpoint.run(input.request));assert.equal(r.status,408,await r.text());assert.equal(input.canceled,true)});
 test(`${endpoint.name} cancels client abort`,async()=>{const control=new AbortController(),input=streamRequest(endpoint.url,{slow:true,signal:control.signal});const pending=endpoint.run(input.request);setTimeout(()=>control.abort(),5);const r=await pending;assert.equal(r.status,408);assert.equal(input.canceled,true)});
}
test("UTF-8 bytes, not character count, bound both assistant handlers and API JSON",async()=>{for(const endpoint of endpoints.slice(0,3)){const text=JSON.stringify({value:"é".repeat(Math.ceil(endpoint.limit/2))});assert(text.length<endpoint.limit);const r=await endpoint.run(new Request(endpoint.url,{method:"POST",headers:{Authorization:"Bearer synthetic",apikey:"synthetic"},body:text}));assert.equal(r.status,413)}});
test("invalid UTF-8 and body-stream faults produce bounded sanitized errors",async()=>{for(const endpoint of endpoints.slice(0,3)){const headers={Authorization:"Bearer synthetic",apikey:"synthetic"};let r=await endpoint.run(new Request(endpoint.url,{method:"POST",headers,body:new Uint8Array([0xc3,0x28])}));assert.equal(r.status,400);const stream=new ReadableStream({start(c){c.error(Error("PRIVATE_STREAM_FAILURE"))}});r=await endpoint.run(new Request(endpoint.url,{method:"POST",headers,body:stream,duplex:"half"}));assert.equal(r.status,400);assert.doesNotMatch(await r.text(),/PRIVATE/)} });
test("normal proxy requests preserve authorization and body; disallowed origin stays denied",async()=>{const body=JSON.stringify({action:"list",workspaceId:wid});const make=origin=>new Request(endpoints[0].url,{method:"POST",headers:{origin,Authorization:"Bearer synthetic",apikey:"synthetic"},body});assert.equal((await proxy(make("https://other.example.test"))).status,403);assert.equal(fixture.proxyCalls.length,0);assert.equal((await proxy(make("https://pilot.example.test"))).status,200);assert.equal(fixture.proxyCalls[0].init.body,body);assert.equal(fixture.proxyCalls[0].init.headers.Authorization,"Bearer synthetic")});
test("assistant verifies context then uses server identity; missing auth stays denied",async()=>{const body=JSON.stringify({action:"list",workspaceId:wid,companyId:"A",userId:"spoofed"});assert.equal((await assistant.fetch(new Request(endpoints[1].url,{method:"POST",body}),{})).status,401);const r=await endpoints[1].run(new Request(endpoints[1].url,{method:"POST",headers:{Authorization:"Bearer synthetic",apikey:"synthetic"},body}));assert.equal(r.status,200);assert.equal(fixture.agentCalls[0].name,`${wid}:${actor}`);assert.equal(fixture.verificationCalls.length,1)});
test("normal authenticated JSON reaches actual context while invalid auth stays denied",async()=>{const make=()=>new Request(endpoints[2].url,{method:"POST",headers:{Authorization:"Bearer synthetic"},body:JSON.stringify({workspaceId:wid,companyId:"A"})});assert.equal((await handler(make())).status,200);fixture.auth=false;assert.equal((await handler(make())).status,401)});
function uploadRequest(content,mime="application/pdf"){const form=new FormData();for(const [key,value]of Object.entries({workspaceId:wid,id:"asset-a",companyId:"A",documentId:"doc-a"}))form.set(key,value);form.set("file",new File([content],"fictional.pdf",{type:mime}));return new Request(endpoints[3].url,{method:"POST",headers:{Authorization:"Bearer synthetic"},body:form})}
test("normal multipart PDF persists original bytes and declared MIME",async()=>{const bytes=new TextEncoder().encode("%PDF-1.7\nSynthetic fixture\n%%EOF");const r=await handler(uploadRequest(bytes));assert.equal(r.status,200,await r.text());assert.equal(fixture.uploads[0].bytes,bytes.length);assert.equal(fixture.inserts[0].mime,"application/pdf")});
test("manual uploads reject mismatched signatures and invalid UTF-8 before storage",async()=>{for(const [bytes,mime] of [["<html>active</html>","application/pdf"],["NOT PNG","image/png"],[new Uint8Array([0xc3,0x28]),"text/plain"],[new Uint8Array([0]),"text/csv"]]){const r=await handler(uploadRequest(bytes,mime));assert.equal(r.status,400,await r.text())}assert.equal(fixture.uploads.length+fixture.inserts.length,0)});
test("all existing known formats pass shared signature checks and octet-stream remains binary",async()=>{for(const [bytes,mime] of [[new Uint8Array([137,80,78,71,13,10,26,10]),"image/png"],[new Uint8Array([255,216,255]),"image/jpeg"],["GIF89a","image/gif"],["RIFFxxxxWEBP","image/webp"],[new Uint8Array([80,75,3,4]),"application/vnd.openxmlformats-officedocument.wordprocessingml.document"],[new Uint8Array([208,207,17,224,161,177,26,225]),"application/msword"],["café","text/plain"],["a,b\n1,2","text/csv"],[new Uint8Array([0xff,0]),"application/octet-stream"]]){const r=await handler(uploadRequest(bytes,mime));assert.equal(r.status,200,`${mime}: ${await r.text()}`)}});
test("multipart retains 50 MiB original-file allowance",async()=>{const bytes=new Uint8Array(52_428_800);bytes.set(new TextEncoder().encode("%PDF-1.7"));const r=await handler(uploadRequest(bytes));assert.equal(r.status,200,await r.text());assert.equal(fixture.inserts[0].byte_size,52_428_800)});
test("malformed multipart produces 400 and no storage changes",async()=>{const r=await handler(new Request(endpoints[3].url,{method:"POST",headers:{Authorization:"Bearer synthetic","content-type":"multipart/form-data; boundary=missing"},body:"not a form"}));assert.equal(r.status,400);assert.equal(fixture.uploads.length,0)});
test("reader accepts exact byte limit and rejects malformed declared length",async()=>{assert.equal((await readRequestBytes(new Request("https://input.test",{method:"POST",body:"café"}),{maxBytes:5})).length,5);assert.equal(await readRequestText(new Request("https://input.test",{method:"POST",body:"café"}),{maxBytes:5}),"café");for(const value of ["-1","1, 1","x"]){const input=streamRequest("https://input.test",{headers:{"content-length":value}});await assert.rejects(readRequestBytes(input.request,{maxBytes:5}),e=>e.status===400);assert.equal(input.canceled,true)}});
test("HTML conversion retains normal paragraphs, table separation and entities without executable markup",()=>{assert.equal(htmlPlainText('<p>Hello &amp; welcome.</p><table><tr><td>250000</td><td>300000</td></tr></table><SCRIPT>hide()</SCRIPT><style>hide</style><p>&#x1f3e0; &lt;script&gt;</p>'),"Hello & welcome.\n250000 | 300000 |\n🏠 <script>");assert.equal(htmlPlainText('<a title="a > b">Safe</a><!-- hidden --><br>Text'),"Safe\nText");assert.equal(htmlPlainText("First  \n\n\nLast\t"),"First\n\nLast");assert.equal(htmlPlainText("&constructor; &unknown; &#0;"),"&constructor; &unknown; �");assert.equal(htmlPlainText("İ<p>Unicode before tags</p>"),"İUnicode before tags")});
test("malformed HTML and whitespace perform bounded work at the provider maximum",async()=>{
 // Terminate the worker if a regression reintroduces synchronous backtracking;
 // a test-runner timeout alone cannot interrupt a blocked JavaScript event loop.
 const source=`const {parentPort,workerData}=require('node:worker_threads'); const convert=eval('('+workerData+')'); const results=[]; for(const token of ['<',' ','&','<!--','<script>','</script-not>'])for(const size of [250000,500000]){const input=token.repeat(Math.ceil(size/token.length)).slice(0,size);const start=performance.now();const text=convert(input);results.push({token,size,ms:performance.now()-start,length:text.length})}parentPort.postMessage(results)`;
 const results=await new Promise((resolve,reject)=>{const worker=new Worker(source,{eval:true,workerData:htmlPlainText.toString()});const timer=setTimeout(()=>{void worker.terminate();reject(Error('HTML conversion exceeded its bounded regression budget'))},2000);worker.once('message',value=>{clearTimeout(timer);void worker.terminate();resolve(value)});worker.once('error',error=>{clearTimeout(timer);reject(error)})});
 for(const r of results){assert(r.ms<1500,`slow ${r.token}`);assert(r.length<=r.size)}
 assert.equal(htmlPlainText("Safe<script>unfinished content"),"Safe");assert.equal(htmlPlainText("Visible<!-- unfinished comment"),"Visible");
});
test("exact assistant and API JSON byte allowances remain accepted",async()=>{for(const endpoint of endpoints.slice(0,3)){const value=JSON.stringify({action:"list",workspaceId:wid,companyId:"A"});const r=await endpoint.run(new Request(endpoint.url,{method:"POST",headers:{Authorization:"Bearer synthetic",apikey:"synthetic"},body:value.padEnd(endpoint.limit," ")}));assert.equal(r.status,200,await r.text())}});
test("multipart rejects a file one byte over its own limit even inside envelope allowance",async()=>{const bytes=new Uint8Array(52_428_801);bytes.set(new TextEncoder().encode("%PDF-1.7"));const r=await handler(uploadRequest(bytes));assert.equal(r.status,413);assert.equal(fixture.uploads.length,0)});
test("cancellation does not wait on an underlying producer that refuses to finish",async()=>{let canceled=false;const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(6))},cancel(){canceled=true;return new Promise(()=>{})}});await assert.rejects(readRequestBytes(new Request("https://input.test",{method:"POST",body:stream,duplex:"half"}),{maxBytes:5}),e=>e.status===413);assert.equal(canceled,true)});

const helpInput={workspaceId:wid,purpose:'help',screen:{page:'Companies',view:'agency',surface:'company'},companyId:'',orderId:''};
const contextRequest=input=>new Request(endpoints[2].url,{method:'POST',headers:{Authorization:'Bearer synthetic',apikey:'synthetic','Content-Type':'application/json'},body:JSON.stringify(input)});
test('authenticated help context uses static guides, ignores forged role, and carries no record data',async()=>{
 fixture.role='viewer';const response=await handler(contextRequest({...helpInput,role:'owner',userId:'spoofed'}));
 assert.equal(response.status,200);const data=await response.json();
 assert.equal(data.userId,actor);assert.equal(data.role,'viewer');assert.equal(data.purpose,'help');
 assert(data.sources.length>0);assert(data.sources.every(source=>source.id.startsWith('help:')));
 assert.doesNotMatch(JSON.stringify(data),/Fictional|spoofed|Person/);
 assert.equal(fixture.inserts.length+fixture.uploads.length,0);
});
test('help context denies malformed purpose, page and mixed record requests before agent use',async()=>{
 for(const input of [{...helpInput,purpose:'admin'},{...helpInput,screen:{}},{...helpInput,screen:{...helpInput.screen,page:'arbitrary'}},{...helpInput,companyId:'A'},{...helpInput,orderId:'O-A'},{...helpInput,purpose:undefined},...[null,false,0].flatMap(value=>[{...helpInput,companyId:value},{...helpInput,orderId:value}])]){
  const response=await handler(contextRequest(input));assert.equal(response.status,400,await response.text());
 }
 assert.equal(fixture.agentCalls.length+fixture.inserts.length+fixture.uploads.length,0);
});
test('partner can ask portal help while staff record access stays denied',async()=>{
 fixture.role='partner';let response=await handler(contextRequest({...helpInput,screen:{page:'Partner portal',view:'partner'}}));
 assert.equal(response.status,200);const data=await response.json();assert(data.sources.every(source=>['Partner portal','Settings'].includes(source.page)));
 response=await handler(contextRequest({workspaceId:wid}));assert.equal(response.status,403);
 response=await handler(contextRequest(helpInput));assert.equal(response.status,403);
 fixture.auth=false;response=await handler(contextRequest({...helpInput,screen:{page:'Partner portal',view:'partner'}}));assert.equal(response.status,401);
});

const scannerEnv={TITLE_SCANNER_URL:"https://scanner.example.test/v1/scan",TITLE_SCANNER_TOKEN:"SYNTHETIC_SCANNER_TOKEN_32_CHARACTERS"};
function scanner(status="clean",alter={}){fixture.scanPolicy="required";fixture.env=scannerEnv;globalThis.fetch=async(_url,init)=>{fixture.scanCalls++;return Response.json({status,protocolVersion:1,requestId:init.headers["X-Scan-Request-ID"],sha256:init.headers["X-Content-SHA256"],byteLength:init.body.byteLength,scannedAt:new Date().toISOString(),engineVersion:"ClamAV 1.5.4",signatureVersion:"123",signatureUpdatedAt:new Date().toISOString(),...alter})}}
test("required scanner must clear exact bytes before storing manual uploads",async()=>{scanner();const r=await handler(uploadRequest("%PDF-1.7\nFictional"));assert.equal(r.status,200,await r.text());assert.equal(fixture.scanCalls,1);assert.equal(fixture.scanReceipts[0].p_receipt.status,"clean");assert.equal(fixture.uploads.length,1)});
for(const [name,status,alter,expected]of [["malware","infected",{},422],["wrong digest","clean",{sha256:"0".repeat(64)},503],["old signatures","clean",{signatureUpdatedAt:"2020-01-01T00:00:00Z"},503]])test(`required scanner blocks ${name} before any storage`,async()=>{scanner(status,alter);const r=await handler(uploadRequest("%PDF-1.7\nFictional"));assert.equal(r.status,expected,await r.text());assert.equal(fixture.uploads.length+fixture.inserts.length+fixture.scanReceipts.length,0);assert.equal(fixture.audit.length,1)});
test("required scanner missing configuration fails closed",async()=>{fixture.scanPolicy="required";const r=await handler(uploadRequest("%PDF-1.7\nFictional"));assert.equal(r.status,503);assert.equal(fixture.uploads.length+fixture.inserts.length,0)});
test("receipt persistence failure stops upload after scanner passes",async()=>{scanner();fixture.receiptFailure=true;const r=await handler(uploadRequest("%PDF-1.7\nFictional"));assert.notEqual(r.status,200);assert.equal(fixture.uploads.length+fixture.inserts.length,0)});
test("pending setup never calls scanner or labels original clean",async()=>{const r=await handler(uploadRequest("%PDF-1.7\nFictional"));assert.equal(r.status,200);assert.equal(fixture.scanCalls,0);assert.equal(fixture.scanReceipts[0].p_receipt,null)});
