create function pg_temp.check_true(ok boolean,label text) returns integer language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'Assertion failed: %',label; end if; return 1; end $$;
create function pg_temp.expect_error(code text,statement text) returns integer language plpgsql as $$ begin
 begin execute statement; exception when others then if sqlstate=code then return 1; end if; raise; end;
 raise exception 'Expected SQLSTATE % for %',code,statement; end $$;

do $$
declare w uuid='20000000-0000-4000-8000-000000000001'; w2 uuid='20000000-0000-4000-8000-000000000002';
 owner uuid='10000000-0000-4000-8000-000000000001'; admin uuid='10000000-0000-4000-8000-000000000002';
 staff uuid='10000000-0000-4000-8000-000000000003'; limited uuid='10000000-0000-4000-8000-000000000004';
 request uuid='30000000-0000-4000-8000-000000000001';
 ds jsonb='{"accountId":"11111111-1111-1111-1111-111111111111","accountName":"Fictional title sandbox","baseUri":"https://demo.docusign.net"}';
 qb jsonb='{"realmId":"123456789","accountName":"Fictional company sandbox"}';
 tokens jsonb='{"accessToken":"synthetic-access-one","refreshToken":"synthetic-refresh-one"}';
 rotated jsonb='{"accessToken":"synthetic-access-two","refreshToken":"synthetic-refresh-two"}';
 r jsonb; lease uuid; checks integer=0; count_rounds integer=0; name text; signature regprocedure; role_name text;
begin
 for round in 1..5 loop
  begin
   insert into auth.users(id,email) values(owner,'owner@example.test'),(admin,'admin@example.test'),(staff,'staff@example.test'),(limited,'limited@example.test');
   insert into public.title_workspaces(id,name,state) values(w,'Synthetic vendor workspace','{"companies":[{"id":"company-a"},{"id":"company-b"}]}'),(w2,'Other workspace','{"companies":[{"id":"company-a"}]}');
   insert into public.title_memberships(workspace_id,user_id,role,all_companies) values(w,owner,'owner',true),(w,admin,'admin',true),(w,staff,'operations',true),(w,limited,'admin',false),(w2,owner,'owner',true);
   r=public.title_vendor_status(w,owner,1,'docusign','company-a');
   checks=checks+pg_temp.check_true(r->'configured'='false' and r->>'revision'='0','new company has disconnected revision zero');
   checks=checks+pg_temp.check_true(public.title_vendor_list(w,admin,1)='[]','empty connection list');
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_status(%L,%L,1,%L,%L)',w,staff,'docusign','company-a'));
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_status(%L,%L,1,%L,%L)',w,limited,'docusign','company-a'));
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_status(%L,%L,2,%L,%L)',w,owner,'docusign','company-a'));
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_status(%L,%L,1,%L,%L)',w,owner,'docusign','missing'));
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_list(%L,%L,1)',w2,admin));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_status(%L,%L,1,%L,%L)',w,owner,'missive','company-a'));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_start_oauth(%L,%L,1,%L,%L,%L,0,%L)',w,owner,'docusign','company-a','sandbox','bad'));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_start_oauth(%L,%L,1,%L,%L,%L,0,%L)',w,owner,'docusign','company-a','unknown',repeat('a',64)));
   r=public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',0,repeat('a',64));
   checks=checks+pg_temp.check_true((r->>'expiresAt')::timestamptz between clock_timestamp()+interval '9 minutes' and clock_timestamp()+interval '11 minutes','state TTL ten minutes');
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w2,owner,1,'docusign','company-a',repeat('a',64))->>'ok')='false','cross workspace callback denied');
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w,owner,1,'quickbooks','company-a',repeat('a',64))->>'ok')='false','cross provider callback denied');
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w,owner,1,'docusign','company-b',repeat('a',64))->>'ok')='false','cross company callback denied');
   r=public.title_vendor_claim_oauth(w,admin,1,'docusign','company-a',repeat('a',64));
   checks=checks+pg_temp.check_true(r->>'ok'='false','different authorized actor denied');
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('a',64))->>'ok')='false','wrong actor attempt consumes state');
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',0,repeat('b',64));
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',0,repeat('c',64));
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('b',64))->>'ok')='false','new consent invalidates prior state');
   r=public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('c',64)); lease=(r->>'leaseId')::uuid;
   checks=checks+pg_temp.check_true(r->>'ok'='true' and r->>'environment'='sandbox','valid callback claims bound environment');
   checks=checks+pg_temp.check_true((public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('c',64))->>'ok')='false','callback cannot replay');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_start_oauth(%L,%L,1,%L,%L,%L,0,%L)',w,owner,'docusign','company-a','sandbox',repeat('d',64)));
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,admin,'docusign','company-a',lease,tokens,ds,'1 hour'));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,owner,'docusign','company-a',lease,tokens,ds,'25 hours'));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,owner,'docusign','company-a',lease,tokens||'{"unexpected":"secret"}'::jsonb,ds,'1 hour'));
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,owner,'docusign','company-a',lease,tokens,ds||'{"baseUri":"https://evil.example"}'::jsonb,'1 hour'));
   r=public.title_vendor_finish(w,owner,1,'docusign','company-a',lease,tokens,ds,clock_timestamp()+interval '1 hour');
   checks=checks+pg_temp.check_true(r->>'configured'='true' and r->>'revision'='1' and r->>'generation'='1' and r->>'busy'='false','successful callback publishes verified connection');
   checks=checks+pg_temp.check_true(not r ? 'tokens' and not r ? 'secret_id','public status has no tokens');
   checks=checks+pg_temp.check_true(public.title_vendor_read(w,admin,1,'docusign','company-a')->'tokens'=tokens,'authorized server reader obtains encrypted tokens through gate');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_read(%L,%L,1,%L,%L)',w,owner,'docusign','company-b'));
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,owner,'docusign','company-a',lease,tokens,ds,'1 hour'));
   perform set_config('title_test.vault_read_failure','yes',true);
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_read(%L,%L,1,%L,%L)',w,owner,'docusign','company-a'));
   perform set_config('title_test.vault_read_failure','no',true);
   r=public.title_vendor_reserve_draft(w,owner,1,'docusign','company-a',1,request,repeat('1',64));
   checks=checks+pg_temp.check_true(r->>'created'='true' and r->>'status'='pending','draft durable pending reservation');
   checks=checks+pg_temp.check_true(public.title_vendor_reserve_draft(w,owner,1,'docusign','company-a',1,request,repeat('1',64))->>'created'='false','retry never resends pending draft');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_reserve_draft(%L,%L,1,%L,%L,1,%L,%L)',w,owner,'docusign','company-a',request,repeat('2',64)));
   checks=checks+pg_temp.check_true(public.title_vendor_claim_draft_check(w,admin,1,'docusign','company-a',request)->>'status'='pending','uncertain pending draft can be checked once immediately');
   checks=checks+pg_temp.expect_error('PT429',format('select public.title_vendor_claim_draft_check(%L,%L,1,%L,%L,%L)',w,owner,'docusign','company-a',request));
   update public.title_vendor_drafts set last_checked_at=clock_timestamp()-interval '16 minutes' where request_id=request;
   checks=checks+pg_temp.check_true(public.title_vendor_claim_draft_check(w,owner,1,'docusign','company-a',request)->>'lastCheckedAt' is not null,'later lookup acquires new provider check');
   r=public.title_vendor_claim_refresh(w,admin,1,'docusign','company-a',1); lease=(r->>'leaseId')::uuid;
   checks=checks+pg_temp.check_true(r->'tokens'=tokens and r->>'ok'='true','refresh claims original token');
   checks=checks+pg_temp.check_true(public.title_vendor_claim_refresh(w,owner,1,'docusign','company-a',1)->>'ok'='false','only one live refresh lease');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,admin,'docusign','company-a',lease,rotated,ds||'{"accountId":"22222222-2222-2222-2222-222222222222"}'::jsonb,'1 hour'));
   perform set_config('title_test.vault_write_failure','yes',true);
   checks=checks+pg_temp.expect_error('P0001',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,admin,'docusign','company-a',lease,rotated,ds,'1 hour'));
   checks=checks+pg_temp.check_true(public.title_vendor_read(w,owner,1,'docusign','company-a')->'tokens'=tokens,'failed token write preserves original');
   perform set_config('title_test.vault_write_failure','no',true);
   r=public.title_vendor_finish(w,admin,1,'docusign','company-a',lease,rotated,ds,clock_timestamp()+interval '1 hour');
   checks=checks+pg_temp.check_true(r->>'revision'='2' and r->>'generation'='1','token rotation changes revision but preserves account generation');
   checks=checks+pg_temp.check_true(public.title_vendor_read(w,owner,1,'docusign','company-a')->'tokens'=rotated,'refresh stores new refresh token');
   checks=checks+pg_temp.check_true(public.title_vendor_reserve_draft(w,owner,1,'docusign','company-a',2,request,repeat('1',64))->>'created'='false','same draft intent after token refresh returns its pending reservation without resend');
   update public.title_memberships set version=2 where workspace_id=w and user_id=owner;
   checks=checks+pg_temp.check_true(public.title_vendor_reserve_draft(w,owner,2,'docusign','company-a',2,request,repeat('1',64))->>'created'='false','current creator permission version permits read-only reservation replay');
   update public.title_memberships set version=1 where workspace_id=w and user_id=owner;
   checks=checks+pg_temp.expect_error('22023',format('select public.title_vendor_finish_draft(%L,%L,1,%L,%L,%L,%L,%L)',w,owner,'docusign','company-a',request,'not-a-guid','created'));
   r=public.title_vendor_finish_draft(w,admin,1,'docusign','company-a',request,'eeeeeeee-1111-1111-1111-111111111111','created');
   checks=checks+pg_temp.check_true(r->>'envelopeId'='eeeeeeee-1111-1111-1111-111111111111' and r->>'status'='created','other current admin can recover after refresh');
   checks=checks+pg_temp.check_true(public.title_vendor_finish_draft(w,owner,1,'docusign','company-a',request,'eeeeeeee-1111-1111-1111-111111111111','completed')->>'envelopeStatus'='completed','status refresh records provider status');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish_draft(%L,%L,1,%L,%L,%L,%L,%L)',w,owner,'docusign','company-a',request,'eeeeeeee-2222-2222-2222-222222222222','created'));
   checks=checks+pg_temp.expect_error('PT429',format('select public.title_vendor_claim_draft_check(%L,%L,1,%L,%L,%L)',w,owner,'docusign','company-a',request));
   checks=checks+pg_temp.check_true(jsonb_array_length(public.title_vendor_list_drafts(w,owner,1,'docusign','company-a'))=1,'company draft list returns one ledger');
   checks=checks+pg_temp.check_true(public.title_vendor_list_drafts(w,owner,1,'docusign','company-b')='[]','other company draft list isolated');
   foreach name in array array['timedout','processing','correct'] loop
     checks=checks+pg_temp.check_true(public.title_vendor_finish_draft(w,admin,1,'docusign','company-a',request,'eeeeeeee-1111-1111-1111-111111111111',name)->>'envelopeStatus'=name,'adapter status persists: '||name);
   end loop;
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_list_drafts(%L,%L,1,%L,%L)',w,staff,'docusign','company-a'));
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','production',2,repeat('d',64));
   checks=checks+pg_temp.check_true(public.title_vendor_claim_refresh(w,admin,1,'docusign','company-a',2)->>'ok'='false','pending consent fences token refresh');
   r=public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('d',64)); lease=(r->>'leaseId')::uuid;
   checks=checks+pg_temp.check_true(public.title_vendor_release(w,owner,1,'docusign','company-a',lease)->>'released'='true','provider failure releases lease');
   checks=checks+pg_temp.check_true(public.title_vendor_read(w,owner,1,'docusign','company-a')->'tokens'=rotated,'failed reauthorization preserves old connection');
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',2,repeat('e',64));
   update public.title_memberships set version=2 where workspace_id=w and user_id=owner;
   checks=checks+pg_temp.check_true(public.title_vendor_claim_oauth(w,owner,2,'docusign','company-a',repeat('e',64))->>'ok'='false','membership update invalidates pending consent even current version');
   checks=checks+pg_temp.check_true((select consumed_at is not null from public.title_vendor_oauth_states where state_hash=repeat('e',64)),'access failure consumption persists');
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_read(%L,%L,1,%L,%L)',w,owner,'docusign','company-a'));
   update public.title_memberships set version=1 where workspace_id=w and user_id=owner;
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',2,repeat('f',64));
   update public.title_vendor_oauth_states set expires_at=clock_timestamp()-interval '1 second' where state_hash=repeat('f',64);
   checks=checks+pg_temp.check_true(public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('f',64))->>'ok'='false','expired consent rejected');
   r=public.title_vendor_claim_refresh(w,admin,1,'docusign','company-a',2); lease=(r->>'leaseId')::uuid;
   r=public.title_vendor_disconnect(w,owner,1,'docusign','company-a',2);
   checks=checks+pg_temp.check_true(r->>'configured'='false' and r->>'revision'='3' and r->>'generation'='2','disconnect advances generation and clears secret');
   checks=checks+pg_temp.check_true((select count(*) from vault.secrets)=0,'disconnect deletes vault bytes');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,admin,'docusign','company-a',lease,tokens,ds,'1 hour'));
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish_draft(%L,%L,1,%L,%L,%L,%L,%L)',w,owner,'docusign','company-a',request,'eeeeeeee-1111-1111-1111-111111111111','completed'));
   perform public.title_vendor_start_oauth(w,owner,1,'docusign','company-a','sandbox',3,repeat('9',64));
   r=public.title_vendor_claim_oauth(w,owner,1,'docusign','company-a',repeat('9',64));
   r=public.title_vendor_finish(w,owner,1,'docusign','company-a',(r->>'leaseId')::uuid,tokens,ds,clock_timestamp()+interval '1 hour');
   checks=checks+pg_temp.check_true(r->>'generation'='3' and r->>'revision'='4','reconnect has distinct account generation even for same vendor account');
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_reserve_draft(%L,%L,1,%L,%L,4,%L,%L)',w,owner,'docusign','company-a',request,repeat('1',64)));
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish_draft(%L,%L,1,%L,%L,%L,%L,%L)',w,owner,'docusign','company-a',request,'eeeeeeee-1111-1111-1111-111111111111','completed'));
   perform public.title_vendor_start_oauth(w,owner,1,'quickbooks','company-a','sandbox',0,repeat('1',64));
   r=public.title_vendor_claim_oauth(w,owner,1,'quickbooks','company-a',repeat('1',64));
   perform public.title_vendor_finish(w,owner,1,'quickbooks','company-a',(r->>'leaseId')::uuid,tokens,qb,clock_timestamp()+interval '1 hour');
   perform public.title_vendor_start_oauth(w,owner,1,'quickbooks','company-b','sandbox',0,repeat('2',64));
   r=public.title_vendor_claim_oauth(w,owner,1,'quickbooks','company-b',repeat('2',64)); lease=(r->>'leaseId')::uuid;
   checks=checks+pg_temp.expect_error('PT409',format('select public.title_vendor_finish(%L,%L,1,%L,%L,%L,%L,%L,now()+interval %L)',w,owner,'quickbooks','company-b',lease,tokens,qb,'1 hour'));
   checks=checks+pg_temp.check_true((select count(*) from vault.secrets)=2,'duplicate realm rejection rolls back new vault secret');
   perform public.title_vendor_release(w,owner,1,'quickbooks','company-b',lease);
   perform public.title_vendor_start_oauth(w,owner,1,'quickbooks','company-b','production',0,repeat('3',64));
   r=public.title_vendor_claim_oauth(w,owner,1,'quickbooks','company-b',repeat('3',64));
   perform public.title_vendor_finish(w,owner,1,'quickbooks','company-b',(r->>'leaseId')::uuid,tokens,qb,clock_timestamp()+interval '1 hour');
   checks=checks+pg_temp.check_true(public.title_vendor_status(w,owner,1,'quickbooks','company-b')->>'configured'='true','same realm identifier in separate environment isolated');
   checks=checks+pg_temp.check_true(jsonb_array_length(public.title_vendor_list(w,owner,1))=3,'all connection rows listed without token values');
   checks=checks+pg_temp.check_true(public.title_vendor_list(w2,owner,1)='[]','cross workspace list isolated');
   update public.title_workspaces set state='{"companies":[{"id":"company-a"}]}' where id=w;
   checks=checks+pg_temp.check_true(jsonb_array_length(public.title_vendor_list(w,owner,1))=2,'removed company connection metadata excluded from list');
   update public.title_workspaces set state='{"companies":[{"id":"company-a"},{"id":"company-b"}]}' where id=w;
   checks=checks+pg_temp.check_true(not exists(select 1 from public.title_audit where detail::text like '%synthetic-%'),'audit stores no synthetic token values');
   update public.title_memberships set active=false,version=2 where workspace_id=w and user_id=admin;
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_read(%L,%L,1,%L,%L)',w,admin,'quickbooks','company-a'));
   checks=checks+pg_temp.expect_error('42501',format('select public.title_vendor_disconnect(%L,%L,1,%L,%L,1)',w,admin,'quickbooks','company-a'));
   raise exception 'Rollback fixtures' using errcode='PTCMP';
  exception when sqlstate 'PTCMP' then count_rounds=count_rounds+1;
  end;
 end loop;
 checks=checks+pg_temp.check_true(count_rounds=5,'five independent disposable rounds complete');
 checks=checks+pg_temp.check_true((select count(*) from public.title_workspaces)=0 and (select count(*) from vault.secrets)=0,'all synthetic records rolled back');
 foreach role_name in array array['anon','authenticated','service_role'] loop
  foreach name in array array['title_vendor_connections','title_vendor_oauth_states','title_vendor_drafts'] loop
   checks=checks+pg_temp.check_true(not has_table_privilege(role_name,'public.'||name,'select,insert,update,delete'),'all tables private from '||role_name);
  end loop;
 end loop;
 for signature in select p.oid::regprocedure from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'title_vendor_%' loop
  checks=checks+pg_temp.check_true(not has_function_privilege('anon',signature,'execute') and not has_function_privilege('authenticated',signature,'execute'),'browser cannot call '||signature::text);
 end loop;
 raise notice '% vendor SQL assertions passed',checks;
 perform set_config('title_test.vendor_check_count',checks::text,false);
end $$;
select current_setting('title_test.vendor_check_count')||' vendor SQL assertions passed';
