"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useWorkspace } from "@/lib/title/store";
import { type VaultDoc } from "@/lib/title/model";
import { businessDay } from "@/lib/title/business-date";
import { canManageCompanies } from "@/lib/title/workspace-capabilities";
import { eligibleAgencyTaskDocuments } from "@/lib/title/agency-setup";
import { completeAgencyMaintenance, defaultMaintenanceNotifications, maintenanceState, nextMaintenanceDate, saveAgencyMaintenance, saveAgencyMaintenanceNotifications, suggestedAgencyMaintenance, syncAgencyMaintenance, upcomingMaintenance, type AgencyMaintenanceRecord } from "@/lib/title/agency-maintenance";
import { FieldLabel } from "./shared";
import { StaffAssignmentPicker } from "./staff-assignment-picker";
import { useWorkspaceNavigationGuard } from "./use-workspace-navigation-guard";
import styles from "./agency-setup.module.css";

type CompletionDraft = { maintenanceId: string; expectedRevision: number; cycleOn: string; completedOn: string; notes: string; documentIds: string[]; nextDueOn: string };
export type AgencyMaintenanceAction = { maintenanceId: string; action: "complete" | "edit" };
const completionDraft = (record: AgencyMaintenanceRecord): CompletionDraft => ({ maintenanceId: record.id, expectedRevision: record.revision, cycleOn: record.nextDueOn, completedOn: businessDay(), notes: "", documentIds: [], nextDueOn: nextMaintenanceDate(record) });
export function AgencyMaintenance({ companyId, onDoc, initialAction, editorOnly = false, onActionClosed }: { companyId?: string; onDoc?: (document: VaultDoc) => void; initialAction?: AgencyMaintenanceAction; editorOnly?: boolean; onActionClosed?: () => void }) {
  const { s, connection, update } = useWorkspace(), canEdit = canManageCompanies(connection), admin = !connection || ["owner", "admin"].includes(connection.access.role) && connection.access.allCompanies;
  const state = maintenanceState(s), records = state.records.filter(r => companyId ? r.companyId === companyId : true), due = upcomingMaintenance(s).filter(r => companyId ? r.companyId === companyId : true);
  const initialRecord = canEdit ? records.find(record => record.id === initialAction?.maintenanceId && (record.scope !== "agency" || admin)) : undefined;
  const [draft, setDraft] = useState<{ expectedRevision: number; record: AgencyMaintenanceRecord } | null>(() => initialAction?.action === "edit" && initialRecord ? { expectedRevision: initialRecord.revision, record: { ...structuredClone(initialRecord), revision: initialRecord.revision + 1 } } : null), [completion, setCompletion] = useState<CompletionDraft | null>(() => initialAction?.action === "complete" && initialRecord?.active && initialRecord.nextDueOn ? completionDraft(initialRecord) : null), [suggestions, setSuggestions] = useState<AgencyMaintenanceRecord[]>([]), [notificationDraft, setNotificationDraft] = useState<{ expected: { enabled: boolean; recipient: string; leadDays: 14 }; enabled: boolean; recipient: string } | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [baseline, setBaseline] = useState(() => JSON.stringify(draft || completion || notificationDraft)); const dirty = !!(draft || completion || notificationDraft) && JSON.stringify(draft || completion || notificationDraft) !== baseline;
  useWorkspaceNavigationGuard("company-detail", { dirty, busy });
  useWorkspaceNavigationGuard("workspace", { dirty, busy });
  async function run(action: (workspace: typeof s) => void, title: string) { if (busy) return; setBusy(true); setError(""); try { const ok = await update(action, title, companyId ? s.companies.find(c => c.id === companyId)?.name || "Company" : "Agency maintenance"); if (ok) { setDraft(null); setCompletion(null); setNotificationDraft(null); onActionClosed?.(); } else setError("The maintenance change was not saved. Check the workspace notice."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save maintenance."); } finally { setBusy(false); } }
  function close() { if (!busy && (!dirty || window.confirm("Discard unsaved maintenance changes?"))) { setDraft(null); setCompletion(null); setNotificationDraft(null); onActionClosed?.(); } }
  function edit(record: AgencyMaintenanceRecord, isNew = false) { const next = { expectedRevision: isNew ? 0 : record.revision, record: { ...structuredClone(record), revision: isNew ? 1 : record.revision + 1 } }; setBaseline(JSON.stringify(next)); setError(""); setDraft(next); }
  function add() { const available = suggestedAgencyMaintenance(s, companyId).filter(r => admin || r.scope !== "agency"); setSuggestions(available); if (available[0]) edit(available[0], true); else setError("All applicable schedules are already tracked. Edit a current record to update its date."); }
  function complete(record: AgencyMaintenanceRecord) { const next = completionDraft(record); setBaseline(JSON.stringify(next)); setError(""); setCompletion(next); }
  const completionRecord = records.find(r => r.id === completion?.maintenanceId), completionTask = s.tasks.find(t => t.phaseOne?.maintenanceId === completion?.maintenanceId && t.phaseOne?.cycleOn === completion?.cycleOn);
  const documents = completionRecord ? eligibleAgencyTaskDocuments(s, completionTask || { companyId: completionRecord.companyId }) : [];
  const history = state.history.filter(h => records.some(r => r.id === h.maintenanceId));
  return <section className={editorOnly ? undefined : styles.panel} aria-label={editorOnly ? undefined : "Recurring maintenance"}>{!editorOnly && <><header className={styles.heading}><div><h3>Recurring maintenance</h3><p>Company renewals, separate owner-entity checks and agency obligations.</p></div><div className={styles.actions}>{canEdit && <Button size="sm" variant="outline" onClick={add}>Add schedule</Button>}{canEdit && (companyId || admin) && <Button size="sm" variant="outline" disabled={busy} onClick={() => void run(workspace => syncAgencyMaintenance(workspace, businessDay(), companyId || ""), "Due maintenance tasks refreshed")}>Refresh due tasks</Button>}{admin && !companyId && <Button size="sm" variant="ghost" onClick={() => { const settings = state.notifications || defaultMaintenanceNotifications(), next = { expected: { ...settings }, enabled: settings.enabled, recipient: settings.recipient }; setBaseline(JSON.stringify(next)); setError(""); setNotificationDraft(next); }}>Reminder delivery</Button>}</div></header>
    <div className={styles.metrics}><span>{records.length} schedules</span><span>{due.length} due within 14 days or overdue</span><span>{records.filter(r => !["Unknown", "Current"].includes(r.standing)).length} entity/status flags</span></div>
    <p className={styles.note}>Renewal terms and dates are editable. NC agency licensing is April 1 each year; SC renewal occurs in January of even years. Verify exact notices and entity-specific filing rules. Agency E&O is a single September event, and John’s credential is tracked once.</p>
    {!records.length && <div className={styles.empty}>Add the applicable schedules and confirm their dates. No renewal email is sent until an administrator enables delivery to the shared inbox.</div>}
    {records.map(record => { const currentTask = s.tasks.find(t => t.phaseOne?.maintenanceId === record.id && t.phaseOne.cycleOn === record.nextDueOn && t.phaseOne.applicable && !t.done); return <div className={styles.row} key={record.id}><div><strong>{record.title}</strong><small>{record.scope === "entity" ? "Ownership entity" : record.scope === "agency" ? "Agency" : "Title company"} · {record.active ? record.nextDueOn ? `Next due ${record.nextDueOn}` : "Confirm a due date" : "Paused"} · every {record.intervalYears} year{record.intervalYears > 1 ? "s" : ""}{record.owner ? ` · ${record.owner}` : ""}</small>{!["Unknown", "Current"].includes(record.standing) && <p className={styles.warning}>{record.standing} · needs attention</p>}{record.documentIds.length > 0 && onDoc && <div className={styles.actions}>{record.documentIds.map(id => { const doc = s.documents.find(d => d.id === id); return doc && <Button type="button" key={id} size="sm" variant="link" onClick={() => onDoc(doc)}>{doc.displayName || doc.name}</Button>; })}</div>}</div>{canEdit && (record.scope !== "agency" || admin) && <div className={styles.actions}><Button size="sm" variant="outline" onClick={() => { setSuggestions([]); edit(record); }}>Edit</Button>{currentTask && <Button size="sm" onClick={() => complete(record)}>Complete cycle</Button>}</div>}</div>; })}
    {!!history.length && <details><summary>{history.length} completed renewal cycle{history.length > 1 ? "s" : ""}</summary>{[...history].reverse().map(h => <p className={styles.note} key={h.id}>{records.find(r => r.id === h.maintenanceId)?.title} · due {h.cycleOn} · completed {h.completedOn} · next due {h.nextDueOn}{h.notes ? ` · ${h.notes}` : ""}</p>)}</details>}
    {error && !draft && !completion && !notificationDraft && <p role="alert">{error}</p>}</>}
    {draft && <Dialog open onOpenChange={v => { if (!v) close(); }}><DialogContent className={`modal ${styles.modal}`}><DialogHeader><DialogTitle>{draft.expectedRevision ? "Edit maintenance schedule" : "Add maintenance schedule"}</DialogTitle><DialogDescription>Confirm applicable dates, source and renewal term. Saving a schedule does not send email.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={e => { e.preventDefault(); void run(workspace => { saveAgencyMaintenance(workspace, draft); syncAgencyMaintenance(workspace, businessDay(), draft.record.companyId); }, "Maintenance schedule saved"); }}><fieldset disabled={busy} className={styles.fieldset}>
      {!draft.expectedRevision && <FieldLabel label="Applicable obligation"><select aria-label="Applicable obligation" className="input" value={draft.record.id} onChange={e => { const selected = suggestions.find(r => r.id === e.target.value); if (selected) edit(selected, true); }}>{suggestions.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></FieldLabel>}
      <FieldLabel label="Schedule name"><Input required maxLength={220} value={draft.record.title} onChange={e => setDraft({ ...draft, record: { ...draft.record, title: e.target.value } })} /></FieldLabel>
      <div className="form-grid"><FieldLabel label="Next due date"><Input type="date" value={draft.record.nextDueOn} onChange={e => setDraft({ ...draft, record: { ...draft.record, nextDueOn: e.target.value } })} /></FieldLabel><FieldLabel label="Renewal term (years)"><Input type="number" min={1} max={10} value={draft.record.intervalYears} onChange={e => setDraft({ ...draft, record: { ...draft.record, intervalYears: Number(e.target.value) } })} /></FieldLabel></div>
      <FieldLabel label="Renewal schedule"><select aria-label="Renewal schedule" className="input" value={draft.record.schedule} onChange={e => setDraft({ ...draft, record: { ...draft.record, schedule: e.target.value as AgencyMaintenanceRecord["schedule"] } })}><option value="anniversary">Verified notice / entered date and term</option>{draft.record.kind === "NC agency license" && <option value="nc-april">NC agency · April 1 annually</option>}{draft.record.kind === "SC agency license" && <option value="sc-even-january">SC agency · January of even years</option>}{draft.record.kind === "Agency E&O" && <option value="september">Agency E&O · September annually</option>}</select></FieldLabel>
      <StaffAssignmentPicker companyId={draft.record.companyId} label="Assigned person" owner={draft.record.owner} assigneeId={draft.record.assigneeId} onChange={assignment => setDraft({ ...draft, record: { ...draft.record, ...assignment } })} />
      <FieldLabel label="Status / good standing"><select aria-label="Status / good standing" className="input" value={draft.record.standing} onChange={e => setDraft({ ...draft, record: { ...draft.record, standing: e.target.value as AgencyMaintenanceRecord["standing"] } })}>{["Unknown", "Current", "Delinquent", "Inactive", "Dissolved", "Suspended"].map(status => <option key={status}>{status}</option>)}</select></FieldLabel>
      <FieldLabel label="Source / renewal notice"><Input maxLength={1000} value={draft.record.source} onChange={e => setDraft({ ...draft, record: { ...draft.record, source: e.target.value } })} /></FieldLabel><FieldLabel label="Last verified date"><Input type="date" max={businessDay()} value={draft.record.verifiedOn} onChange={e => setDraft({ ...draft, record: { ...draft.record, verifiedOn: e.target.value } })} /></FieldLabel><FieldLabel label="Notes"><Textarea maxLength={4000} rows={3} value={draft.record.notes} onChange={e => setDraft({ ...draft, record: { ...draft.record, notes: e.target.value } })} /></FieldLabel><label className={styles.check}><input type="checkbox" checked={draft.record.active} onChange={e => setDraft({ ...draft, record: { ...draft.record, active: e.target.checked } })} />Track this obligation (uncheck to pause when not applicable)</label>
    </fieldset>{error && <p role="alert">{error}</p>}<div className={styles.actions}><Button variant="ghost" type="button" onClick={close} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy}>Save schedule</Button></div></form></DialogContent></Dialog>}
    {completion && completionRecord && <Dialog open onOpenChange={v => { if (!v) close(); }}><DialogContent className={`modal ${styles.modal}`}><DialogHeader><DialogTitle>Complete renewal cycle</DialogTitle><DialogDescription>{completionRecord.title} · due {completion.cycleOn}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={e => { e.preventDefault(); void run(workspace => completeAgencyMaintenance(workspace, completion), "Maintenance cycle completed"); }}><fieldset disabled={busy} className={styles.fieldset}><div className="form-grid"><FieldLabel label="Completion date"><Input required type="date" max={businessDay()} value={completion.completedOn} onChange={e => setCompletion({ ...completion, completedOn: e.target.value })} /></FieldLabel><FieldLabel label="Next renewal date"><Input required type="date" value={completion.nextDueOn} onChange={e => setCompletion({ ...completion, nextDueOn: e.target.value })} /></FieldLabel></div><FieldLabel label="Completion notes"><Textarea maxLength={4000} rows={3} value={completion.notes} onChange={e => setCompletion({ ...completion, notes: e.target.value })} /></FieldLabel><fieldset className={styles.documents}><legend>Linked originals{completionTask?.phaseOne?.documentRequirement ? " · required" : ""}</legend>{documents.map(doc => <label key={doc.id}><input type="checkbox" checked={completion.documentIds.includes(doc.id)} onChange={e => setCompletion({ ...completion, documentIds: e.target.checked ? [...completion.documentIds, doc.id] : completion.documentIds.filter(id => id !== doc.id) })} />{doc.displayName || doc.name}</label>)}{!documents.length && <p>Upload the supporting original in Documents, then return here to link it.</p>}</fieldset></fieldset>{error && <p role="alert">{error}</p>}<div className={styles.actions}><Button variant="ghost" type="button" onClick={close} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy}>Complete and roll forward</Button></div></form></DialogContent></Dialog>}
    {notificationDraft && <Dialog open onOpenChange={v => { if (!v) close(); }}><DialogContent className="modal"><DialogHeader><DialogTitle>Maintenance reminder delivery</DialogTitle><DialogDescription>Choose the shared inbox for due and overdue obligations. Reminders begin 14 days before the due date.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={e => { e.preventDefault(); void run(workspace => saveAgencyMaintenanceNotifications(workspace, notificationDraft), "Maintenance reminder settings saved"); }}><fieldset disabled={busy} className={styles.fieldset}><FieldLabel label="Shared reminder inbox"><Input type="email" maxLength={254} required={notificationDraft.enabled} value={notificationDraft.recipient} onChange={e => setNotificationDraft({ ...notificationDraft, recipient: e.target.value })} /></FieldLabel><label className={styles.check}><input type="checkbox" checked={notificationDraft.enabled} onChange={e => setNotificationDraft({ ...notificationDraft, enabled: e.target.checked })} />Enable automatic renewal email to this shared inbox</label><p className={styles.note}>Delivery is disabled by default. Enabling this setting authorizes scheduled renewal reminders to the address entered above.</p></fieldset>{error && <p role="alert">{error}</p>}<div className={styles.actions}><Button type="button" variant="ghost" disabled={busy} onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>Save reminder settings</Button></div></form></DialogContent></Dialog>}
  </section>;
}
