"use client";
import { useEffect, useRef, useState } from "react";
import { Eye, EyeOff, LockKeyhole, Plus, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { FieldLabel } from "./shared";
import { useWorkspace, download } from "@/lib/title/store";
import { uid, type Company, type VaultDoc } from "@/lib/title/model";
import { jvIntakeClientRequest, type JVIntakeContext } from "@/lib/backend/jv-intake-client";
import { validateJVApplication, type JVRecord, type JVApplication } from "@/lib/title/jv-application";
import { emptyCompanyRecords, emptyFinancialTerms, emptyBankingMetadata, emptyEntityCompliance, distributionTotal, validateConfirmedDistributionMembers, applicationFieldSources, type FinancialTerms, type EntityCompliance, type CompanyRecords, type OwnerEntity, type CompanyAgreement, type ApplicationWorksheet } from "@/lib/title/company-records";
import { configureAgencySetup, latestAgencySetupTemplate } from "@/lib/title/agency-setup";
import { companyRecordMaintenanceChanged, syncCompanyRecordMaintenance } from "@/lib/title/company-records-maintenance";
import { prepareApplicationWorksheet } from "@/lib/title/application-worksheet";
import { useWorkspaceNavigationGuard } from "./use-workspace-navigation-guard";
import styles from "./company-workspace.module.css";

type Props = { company: Company; onDirtyChange?: (v: boolean) => void; onBusyChange?: (v: boolean) => void };
export function CompanyRecordsPanel(props: Props) {
  const { connection } = useWorkspace();
  if (!connection) return <p className={styles.privateNotice}>Sign in to the shared workspace to keep private owner records.</p>;
  const { access, workspaceId } = connection;
  if (!["owner", "admin", "onboarding"].includes(access.role) || !access.restricted || !(access.allCompanies || access.companyIds.includes(props.company.id))) return null;
  const scope = JSON.stringify([workspaceId, access, props.company.id]);
  return <PrivateCompanyRecords key={scope} {...props} context={{ workspaceId, userId: access.userId, companyId: props.company.id }} />;
}
function PrivateCompanyRecords({ company, context, onDirtyChange, onBusyChange }: Props & { context: JVIntakeContext }) {
  const { s, update } = useWorkspace();
  const [record, setRecord] = useState<JVRecord | null>(null), [draft, setDraft] = useState<CompanyRecords | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [conflict, setConflict] = useState(false);
  const alive = useRef(true), working = useRef(false);
  const dirty = !!draft && JSON.stringify(draft) !== JSON.stringify(record?.payload.companyRecords || emptyCompanyRecords());
  useWorkspaceNavigationGuard("company-detail", { dirty, busy });
  useEffect(() => { onDirtyChange?.(dirty); return () => onDirtyChange?.(false); }, [dirty, onDirtyChange]);
  useEffect(() => { onBusyChange?.(busy); return () => onBusyChange?.(false); }, [busy, onBusyChange]);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  async function load() {
    if (working.current || dirty && !window.confirm("Discard unsaved owner details and reload?")) return;
    working.current = true; setBusy(true); setError("");
    try {
      if (company.members.some(m => !m.id)) {
        const baseline = JSON.stringify(company.members);
        const ok = await update(state => { const c = state.companies.find(c => c.id === company.id); if (!c || JSON.stringify(c.members) !== baseline) throw new Error("Members changed. Reopen the company."); c.members = c.members.map(m => ({ ...m, id: m.id || uid("member") })); }, "Owner records enabled", company.name);
        if (!ok) throw new Error("Save the company members before opening owner records.");
      }
      const result = await jvIntakeClientRequest(context, "load");
      if (!alive.current) return;
      setRecord(result); setDraft(structuredClone(result.payload.companyRecords || emptyCompanyRecords())); setConflict(false); setNotice("");
    } catch (e) { if (alive.current) { const status = e && typeof e === "object" && "status" in e ? e.status : undefined; if (status === 401 || status === 403) { setRecord(null); setDraft(null); } setError("Owner records could not be loaded. Check your access and try again."); } }
    finally { working.current = false; if (alive.current) setBusy(false); }
  }
  async function save() {
    if (working.current || !draft || !record || conflict) return;
    working.current = true; setBusy(true); setError(""); setNotice("");
    try {
      validateConfirmedDistributionMembers(draft, company.members.map(m => m.id || ""));
      const payload = validateJVApplication({ ...record.payload, companyRecords: draft });
      const result = await jvIntakeClientRequest(context, "save", { expectedVersion: record.version, payload });
      if (!alive.current) return;
      setRecord(result); setDraft(structuredClone(result.payload.companyRecords!));
      const savedRecords = result.payload.companyRecords!;
      const choices = savedRecords.owners.filter(o => o.setupKind || o.kind === "individual").map(o => ({ memberId: o.memberId, kind: o.kind === "individual" ? "individual" as const : o.setupKind! }));
      let aligned = true;
      const previousRecords = record.payload.companyRecords || emptyCompanyRecords();
      const alignSetup = savedRecords.owners.some(o => o.setupKind) || !!(company.agencySetup && choices.length) || !!savedRecords.financialTerms;
      try { if (alignSetup || companyRecordMaintenanceChanged(previousRecords, savedRecords)) aligned = await update(state => {
        const current = state.companies.find(c => c.id === company.id); if (!current) throw new Error("Company changed. Reopen setup.");
        const prior = current.agencySetup;
        if (alignSetup) configureAgencySetup(state, { companyId: current.id, expectedVersion: company.agencySetup?.version || 0, templateVersion: prior?.templateVersion || latestAgencySetupTemplate(state).version, owners: [...(prior?.owners || []).filter(o => !choices.some(c => c.memberId === o.memberId)), ...choices], agreementCount: savedRecords.financialTerms ? savedRecords.financialTerms.agreementMode === "separate" ? 2 : 1 : prior?.agreementCount || 1, eoCovered: prior?.eoCovered || false });
        syncCompanyRecordMaintenance(state, current.id, previousRecords, savedRecords);
      }, "Company setup and maintenance aligned", company.name); } catch { aligned = false; }
      if (alive.current) setNotice(aligned ? "Owner and company records saved." : "Private records saved. Reopen Setup & Approvals and Maintenance to update the shared checklist or schedule.");
    } catch (e) {
      if (!alive.current) return;
      const status = e && typeof e === "object" && "status" in e ? e.status : undefined;
      if (status === 401 || status === 403) { setRecord(null); setDraft(null); }
      if (status === 409) setConflict(true);
      setError(status === 409 ? "The application or member records changed. Reload before saving again." : "Owner details could not be saved. Check the fields and document references, then try again.");
    } finally { working.current = false; if (alive.current) setBusy(false); }
  }
  function change(next: CompanyRecords) { if (!working.current) { setDraft(next); setNotice(""); setError(""); } }
  const originals = s.documents.filter(d => !d.archivedAt && d.companyId === company.id && !d.orderId && d.visibility === "Restricted" && !!d.assetId);
  return <section aria-label="Private owner records" className={styles.owner}>
    <div className={styles.heading}><div><h3><LockKeyhole size={17} className="inline" /> Ownership & Financial Terms</h3><p>Private owner records, separate financial terms, banking and entity status.</p></div><Button variant="outline" disabled={busy} onClick={() => void load()}>{draft ? "Reload saved records" : "Open owner details"}</Button></div>
    {error && <p role="alert" className="notice warning">{error}</p>}{notice && <p role="status">{notice}</p>}
    {busy && !draft && <p role="status">Loading private records…</p>}
    {draft && record && <form autoComplete="off" className="form-stack" onSubmit={e => { e.preventDefault(); void save(); }}><fieldset disabled={busy || conflict} className={styles.fieldset}>
      <EinField label="Title company EIN" value={draft.companyEin} onChange={value => change({ ...draft, companyEin: value })} />
      <p className={styles.privateNotice}>The company EIN belongs to {company.name}. Each owning LLC has its own EIN below. You can enter the number without uploading a document.</p>
      {company.members.map(member => { const owner = draft.owners.find(o => o.memberId === member.id); return <section key={member.id || member.name} className={styles.owner}>
        <div className={styles.heading}><div><h4>{owner?.legalName || member.name}</h4><p>{member.share}% ownership</p></div>{!owner && <Button type="button" variant="outline" disabled={!member.id || draft.owners.length >= 40} onClick={() => change({ ...draft, owners: [...draft.owners, { id: uid("owner"), memberId: member.id!, kind: "individual", legalName: member.name, ein: "", representatives: [{ id: uid("representative"), name: "", email: member.email || "", phone: member.phone || "" }], formationStatus: "Unknown", formationBy: "Not confirmed", formationState: "", formationReference: "", documentIds: [] }] })}>Add owner details</Button>}</div>
        {owner && <OwnerEditor owner={owner} applicants={record.payload.applicants} originals={originals} onChange={next => change({ ...draft, owners: draft.owners.map(o => o.id === owner.id ? next : o) })} />}
      </section>; })}
      {!company.members.length && <p>Add the company members and their interests above, then open their owner details here.</p>}
      {draft.owners.filter(o => !company.members.some(m => m.id === o.memberId)).map(o => <div role="alert" className="notice warning" key={o.id}><p>An owner record is linked to a member that is no longer present. Relink it or remove its private details before saving. The saved application and original files remain available.</p><select aria-label="Relink owner record" value="" onChange={e => change({ ...draft, owners: draft.owners.map(row => row.id === o.id ? { ...row, memberId: e.target.value } : row) })}><option value="">Choose member…</option>{company.members.filter(m => m.id && !draft.owners.some(o => o.memberId === m.id)).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><Button type="button" variant="outline" onClick={() => { if (window.confirm("Remove this former owner’s private details from the current company record?")) change({ ...draft, owners: draft.owners.filter(row => row.id !== o.id) }); }}>Remove former owner details</Button></div>)}
      <section className={styles.owner} aria-label="Ownership and distribution"><h4>Ownership & distribution</h4><p>Ownership interests total {company.members.reduce((sum, member) => sum + member.share, 0)}%. Edit ownership in the company member ledger.</p>
        {draft.financialTerms ? <FinancialTermsEditor terms={draft.financialTerms} company={company} agreements={draft.agreements} onChange={financialTerms => change({ ...draft, financialTerms })} /> : <><p className={styles.privateNotice}>Enter distribution percentages independently from ownership and record the management / operating fee separately.</p><Button type="button" variant="outline" onClick={() => change({ ...draft, financialTerms: { ...emptyFinancialTerms(), distribution: company.members.filter(m => m.id).map(m => ({ memberId: m.id!, percentage: "" })) } })}>Set financial terms</Button></>}
      </section>
      <details className={styles.owner}><summary>Banking & payment method</summary><p className={styles.privateNotice}>Record establishment and last four digits only. Do not enter full card numbers, security codes, or card images. Secure card-vault storage is reserved for a future phase.</p>
        {(() => { const b = draft.banking || emptyBankingMetadata(); const patch = (v: Partial<typeof b>) => change({ ...draft, banking: { ...b, ...v } }); return <div className="form-grid"><label><input type="checkbox" checked={b.bankEstablished} onChange={e => patch({ bankEstablished: e.target.checked })} /> Bank account established</label><FieldLabel label="Bank name"><Input value={b.bankName} maxLength={200} onChange={e => patch({ bankName: e.target.value })} /></FieldLabel><FieldLabel label="Bank establishment confirmation"><Input value={b.confirmation} maxLength={500} onChange={e => patch({ confirmation: e.target.value })} placeholder="Confirmation reference only" /></FieldLabel><label><input type="checkbox" checked={b.paymentEstablished} onChange={e => patch({ paymentEstablished: e.target.checked })} /> Company payment method established</label><FieldLabel label="Cardholder / company name"><Input value={b.cardholder} maxLength={200} onChange={e => patch({ cardholder: e.target.value })} /></FieldLabel><EinField label="Payment card last four digits" value={b.lastFour} onChange={lastFour => patch({ lastFour })} maxLength={4} placeholder="1234" /></div>; })()}
      </details>
      <details className={styles.owner}><summary>Title company annual report & status</summary><ComplianceEditor value={draft.companyCompliance || emptyEntityCompliance()} originals={originals} label="Title company" onChange={companyCompliance => change({ ...draft, companyCompliance })} /></details>
      <details className={styles.owner}><summary>Agreements & financial terms</summary><p className={styles.privateNotice}>Record the actual agreement terms separately from ownership interests. These entries do not change accounting calculations.</p>
        {draft.agreements.map(a => <section key={a.id}><AgreementEditor agreement={a} company={company} originals={originals} onChange={next => change({ ...draft, agreements: draft.agreements.map(row => row.id === a.id ? next : row) })} /><Button type="button" variant="ghost" onClick={() => { if (window.confirm("Remove this agreement entry? Its original documents will remain.")) change({ ...draft, agreements: draft.agreements.filter(row => row.id !== a.id) }); }}>Remove agreement entry</Button></section>)}
        <Button type="button" variant="outline" disabled={draft.agreements.length >= 40} onClick={() => change({ ...draft, agreements: [...draft.agreements, { id: uid("agreement"), title: "", effectiveOn: "", reference: "", documentIds: [], terms: [], notes: "" }] })}><Plus size={15} />Add agreement</Button>
      </details>
      <details className={styles.owner}><summary>Application preparation for John</summary><p className={styles.privateNotice}>Map the field labels from a current application to saved company details. Download a filled preparation sheet to check against the official form. The original application, signatures and submission stay separate.</p>
        {draft.worksheets.map(w => <section key={w.id}><WorksheetEditor worksheet={w} onChange={next => change({ ...draft, worksheets: draft.worksheets.map(row => row.id === w.id ? next : row) })} company={company} records={draft} originals={originals} saved={!dirty} /><Button type="button" variant="ghost" onClick={() => { if (window.confirm("Remove this application worksheet? Its original form will remain.")) change({ ...draft, worksheets: draft.worksheets.filter(row => row.id !== w.id) }); }}>Remove worksheet</Button></section>)}
        <Button type="button" variant="outline" disabled={draft.worksheets.length >= 30} onClick={() => change({ ...draft, worksheets: [...draft.worksheets, { id: uid("worksheet"), title: "", version: "1", documentId: "", fields: [] }] })}><Plus size={15} />Add application worksheet</Button>
      </details>
    </fieldset><Button type="submit" disabled={busy || conflict || !dirty}>{busy ? "Saving…" : "Save owner & company records"}</Button></form>}
  </section>;
}
function EinField({ label, value, onChange, maxLength = 10, placeholder = "XX-XXXXXXX (optional)" }: { label: string; value: string; onChange: (v: string) => void; maxLength?: number; placeholder?: string }) {
  const [shown, setShown] = useState(false);
  return <FieldLabel label={label}><div className="flex gap-2"><Input aria-label={label} type={shown ? "text" : "password"} inputMode="numeric" maxLength={maxLength} autoComplete="off" value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /><Button type="button" variant="outline" aria-label={`${shown ? "Hide" : "Show"} ${label}`} onClick={() => setShown(v => !v)}>{shown ? <EyeOff size={16} /> : <Eye size={16} />}</Button></div></FieldLabel>;
}
function DocumentLinks({ selected, originals, categories, onChange }: { selected: string[]; originals: VaultDoc[]; categories: string[]; onChange: (v: string[]) => void }) {
  const options = originals.filter(d => categories.includes(d.category));
  return <div className="form-stack"><p className={styles.privateNotice}>Link this company’s restricted originals, or save now and add them later.</p>{options.map(d => <label key={d.id} className="flex gap-2"><input type="checkbox" checked={selected.includes(d.id)} onChange={e => onChange(e.target.checked ? [...selected, d.id] : selected.filter(id => id !== d.id))} /><span>{d.name}</span></label>)}{selected.filter(id => !options.some(d => d.id === id)).map(id => <div key={id} role="alert"><span>An original is unavailable or has a different category. </span><Button type="button" variant="ghost" onClick={() => onChange(selected.filter(v => v !== id))}>Remove unavailable reference</Button></div>)}</div>;
}
function OwnerEditor({ owner, applicants, originals, onChange }: { owner: OwnerEntity; applicants: JVApplication["applicants"]; originals: VaultDoc[]; onChange: (owner: OwnerEntity) => void }) {
  const patch = (v: Partial<OwnerEntity>) => { const next = { ...owner, ...v }; if (next.compliance === undefined) delete next.compliance; if (next.setupKind === undefined) delete next.setupKind; if (next.kind === "individual") { delete next.setupKind; delete next.compliance; } else if (Object.hasOwn(v, "legalName") && v.legalName === "") { delete next.setupKind; delete next.compliance; } onChange(next); };
  return <div className="form-stack"><div className="form-grid"><FieldLabel label="Who owns this interest?"><select className="input" value={owner.kind} onChange={e => { const kind = e.target.value as OwnerEntity["kind"]; if (kind === "individual" && (owner.ein || owner.documentIds.length) && !window.confirm("Switch to an individual and clear this LLC's tax ID and formation-document links?")) return; patch({ kind, ...(kind === "individual" ? { ein: "", formationStatus: "Not applicable", formationState: "", formationReference: "", formationBy: "Not confirmed", documentIds: [] } : { formationStatus: "Unknown" }) }); }}><option value="individual">The person individually</option><option value="llc">Their LLC</option><option value="other">Another legal entity</option></select></FieldLabel><FieldLabel label="Legal owner name"><Input value={owner.legalName} maxLength={200} onChange={e => patch({ legalName: e.target.value })} /></FieldLabel></div>
    <div><p className={styles.privateNotice}>Correct the name above for this same owner. To record a different legal owner, clear the previous owner’s details first.</p><Button type="button" variant="ghost" onClick={() => { if (window.confirm("Start details for a different legal owner? This clears the current name, tax ID, formation links and representatives from this draft. Original documents and ownership percentages will not change.")) patch({ legalName: "", ein: "", formationStatus: owner.kind === "individual" ? "Not applicable" : "Unknown", formationState: "", formationReference: "", formationBy: "Not confirmed", documentIds: [], representatives: [] }); }}>Use a different legal owner</Button></div>
    {!!applicants.length && <FieldLabel label="Use saved application details"><select className="input" value="" onChange={e => { const a = applicants.find(a => a.id === e.target.value); if (!a || !window.confirm("Copy this applicant’s details? A changed legal owner clears the previous entity’s EIN and formation links. Ownership percentages stay the same.")) return;
      const known = a.ownershipType !== "undecided", kind = a.ownershipType === "business" ? "llc" as const : "individual" as const;
      const legalName = a.ownershipType === "business" ? a.businessName : a.name;
      const changedOwner = known && (kind !== owner.kind || legalName !== owner.legalName);
      patch({ ...(known ? { legalName, kind } : {}),
        ...(changedOwner ? { compliance: undefined, setupKind: undefined, ein: "", documentIds: [], formationState: "", formationReference: "", formationBy: "Not confirmed", formationStatus: kind === "individual" ? "Not applicable" : "Unknown" } : {}),
        representatives: [{ id: uid("representative"), name: a.name, email: a.email, phone: a.phone }],
        ...(a.ownershipType === "business" ? { formationReference: a.businessReference, formationStatus: a.businessStatus === "existing" ? "Formed" : "Being formed" } : {}) }); }}><option value="">Choose an applicant to copy…</option>{applicants.filter(a => a.name).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></FieldLabel>}
    {owner.kind !== "individual" && <><FieldLabel label="Ownership entity setup"><select className="input" value={owner.setupKind || ""} onChange={e => patch({ setupKind: e.target.value as "existing" | "new" })}><option value="" disabled>Choose existing or new entity…</option><option value="existing">Existing entity — verify current status</option><option value="new">New entity — authorization and formation required</option></select></FieldLabel><EinField label="Owner LLC / entity EIN" value={owner.ein} onChange={value => patch({ ein: value })} /><div className="form-grid"><FieldLabel label="Formation status"><select className="input" value={owner.formationStatus} onChange={e => patch({ formationStatus: e.target.value as OwnerEntity["formationStatus"] })}>{["Unknown", "Being formed", "Formed"].map(v => <option key={v}>{v}</option>)}</select></FieldLabel><FieldLabel label="Who is forming it?"><select className="input" value={owner.formationBy} onChange={e => patch({ formationBy: e.target.value as OwnerEntity["formationBy"] })}>{["Not confirmed", "Agency", "Owner / outside professional"].map(v => <option key={v}>{v}</option>)}</select></FieldLabel><FieldLabel label="Owner entity formation state"><Input maxLength={2} value={owner.formationState} placeholder="NC / SC" onChange={e => patch({ formationState: e.target.value.toUpperCase() })} /></FieldLabel><FieldLabel label="Secretary of State / filing reference"><Input maxLength={1000} value={owner.formationReference} onChange={e => patch({ formationReference: e.target.value })} /></FieldLabel></div><DocumentLinks selected={owner.documentIds} originals={originals} categories={["Formation", "Company records", "Partner entities"]} onChange={documentIds => patch({ documentIds })} />
      {(!owner.ein || owner.formationStatus !== "Formed" || !owner.formationReference) && <p className="notice">Still needed: {[!owner.ein && "tax ID", owner.formationStatus !== "Formed" && "formation confirmation", !owner.formationReference && "filing reference"].filter(Boolean).join(", ")}. You can save and finish later.</p>}</>}
    {owner.kind !== "individual" && <details className={styles.owner}><summary>Owner entity annual report & status</summary><ComplianceEditor value={owner.compliance || emptyEntityCompliance()} originals={originals} label="Owner entity" onChange={compliance => patch({ compliance })} /></details>}
    <h4>{owner.kind === "individual" ? "Person’s contact details" : "People representing this owner"}</h4>{owner.representatives.map((r, i) => <div className="form-grid" key={r.id}>{(["name", "email", "phone"] as const).map(key => <FieldLabel key={key} label={`Representative ${i + 1} ${key}`}><Input type={key === "email" ? "email" : "text"} maxLength={key === "email" ? 254 : key === "phone" ? 60 : 150} value={r[key]} onChange={e => patch({ representatives: owner.representatives.map(row => row.id === r.id ? { ...row, [key]: e.target.value } : row) })} /></FieldLabel>)}<Button type="button" variant="ghost" aria-label={`Remove representative ${i + 1}`} onClick={() => { if (window.confirm("Remove this representative from the owner record?")) patch({ representatives: owner.representatives.filter(row => row.id !== r.id) }); }}>Remove representative</Button></div>)}<Button type="button" variant="outline" disabled={owner.representatives.length >= 10} onClick={() => patch({ representatives: [...owner.representatives, { id: uid("representative"), name: "", email: "", phone: "" }] })}><Plus size={14} />Add representative</Button>
  </div>;
}
function AgreementEditor({ agreement: a, company, originals, onChange }: { agreement: CompanyAgreement; company: Company; originals: VaultDoc[]; onChange: (a: CompanyAgreement) => void }) {
  const patch = (v: Partial<CompanyAgreement>) => onChange({ ...a, ...v });
  return <div className={styles.owner}><div className="form-grid"><FieldLabel label="Agreement type"><select className="input" value={a.kind || "other"} onChange={e => patch({ kind: e.target.value as CompanyAgreement["kind"] })}><option value="combined">Combined JV / Operating Agreement</option><option value="jv">JV Agreement</option><option value="operating">Operating Agreement</option><option value="other">Other / legacy agreement</option></select></FieldLabel><label><input type="checkbox" checked={a.executed === true} onChange={e => patch({ executed: e.target.checked })} /> Fully executed agreement</label><FieldLabel label="Agreement title"><Input value={a.title} maxLength={200} onChange={e => patch({ title: e.target.value })} /></FieldLabel><FieldLabel label="Agreement effective date"><Input type="date" value={a.effectiveOn} onChange={e => patch({ effectiveOn: e.target.value })} /></FieldLabel></div><FieldLabel label="Agreement reference / version"><Input value={a.reference} maxLength={1000} onChange={e => patch({ reference: e.target.value })} /></FieldLabel><DocumentLinks selected={a.documentIds} originals={originals} categories={["Agreements"]} onChange={documentIds => patch({ documentIds })} />
    {a.terms.map((t, i) => <div className={styles.term} key={i}><select className="input" aria-label={`Agreement member ${i + 1}`} value={t.memberId} onChange={e => patch({ terms: a.terms.map((row, j) => j === i ? { ...row, memberId: e.target.value } : row) })}>{!company.members.some(m => m.id === t.memberId) && <option value={t.memberId}>Member unavailable — choose another</option>}{company.members.filter(m => m.id).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><Input aria-label={`Term label ${i + 1}`} placeholder="Distribution / fee / voting" maxLength={150} value={t.label} onChange={e => patch({ terms: a.terms.map((row, j) => j === i ? { ...row, label: e.target.value } : row) })} /><Input aria-label={`Term percentage ${i + 1}`} type="number" min="0" max="100" step="0.001" placeholder="%" value={t.percentage} onChange={e => patch({ terms: a.terms.map((row, j) => j === i ? { ...row, percentage: e.target.value } : row) })} /><Button type="button" variant="ghost" aria-label={`Remove agreement term ${i + 1}`} onClick={() => patch({ terms: a.terms.filter((_, j) => j !== i) })}>Remove term</Button></div>)}
    <Button type="button" variant="outline" disabled={!company.members.some(m => m.id) || a.terms.length >= 80} onClick={() => patch({ terms: [...a.terms, { memberId: company.members.find(m => m.id)!.id!, label: "", percentage: "" }] })}>Add percentage term</Button><FieldLabel label="Other agreement terms"><Textarea rows={3} maxLength={4000} value={a.notes} onChange={e => patch({ notes: e.target.value })} /></FieldLabel>
  </div>;
}
function WorksheetEditor({ worksheet: w, onChange, company, records, originals, saved }: { worksheet: ApplicationWorksheet; onChange: (w: ApplicationWorksheet) => void; company: Company; records: CompanyRecords; originals: VaultDoc[]; saved: boolean }) {
  const [ownerId, setOwnerId] = useState(""), [representativeId, setRepresentativeId] = useState(""), [error, setError] = useState("");
  const owner = records.owners.find(o => o.id === ownerId);
  function exportSheet() { try { const draft = prepareApplicationWorksheet(company, records, w, ownerId, representativeId); download("application-preparation.html", draft.html, "text/html"); setError(draft.missing.length ? `${draft.missing.length} fields need completion. The draft marks them as missing.` : ""); } catch (e) { setError(e instanceof Error ? e.message : "Check the worksheet."); } }
  return <div className={styles.owner}><div className="form-grid"><FieldLabel label="Application name"><Input maxLength={200} value={w.title} onChange={e => onChange({ ...w, title: e.target.value })} /></FieldLabel><FieldLabel label="Form version"><Input maxLength={80} value={w.version} onChange={e => onChange({ ...w, version: e.target.value })} /></FieldLabel></div><FieldLabel label="Original form (optional)"><select className="input" value={w.documentId} onChange={e => onChange({ ...w, documentId: e.target.value })}><option value="">Not supplied yet</option>{w.documentId && !originals.some(d => d.id === w.documentId && ["Applications", "Agreements", "Disclosures", "Company records"].includes(d.category)) && <option value={w.documentId}>Unavailable original — choose another or clear</option>}{originals.filter(d => ["Applications", "Agreements", "Disclosures", "Company records"].includes(d.category)).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></FieldLabel>
    {w.fields.map((f, i) => <div className="form-grid" key={f.id}><Input aria-label={`Application field label ${i + 1}`} maxLength={200} placeholder="Label on official application" value={f.label} onChange={e => onChange({ ...w, fields: w.fields.map(row => row.id === f.id ? { ...row, label: e.target.value } : row) })} /><select className="input" aria-label={`Source for application field ${i + 1}`} value={f.source} onChange={e => onChange({ ...w, fields: w.fields.map(row => row.id === f.id ? { ...row, source: e.target.value as typeof f.source } : row) })}>{applicationFieldSources.map(v => <option key={v.value} value={v.value}>{v.label}</option>)}</select><Button type="button" variant="ghost" aria-label={`Remove application field ${i + 1}`} onClick={() => onChange({ ...w, fields: w.fields.filter(row => row.id !== f.id) })}>Remove field</Button></div>)}
    <Button type="button" variant="outline" disabled={w.fields.length >= 100} onClick={() => onChange({ ...w, fields: [...w.fields, { id: uid("field"), label: "", source: "company.name" }] })}>Add mapped field</Button><div className="form-grid"><FieldLabel label="Prepare for owner"><select className="input" value={ownerId} onChange={e => { setOwnerId(e.target.value); setRepresentativeId(""); }}><option value="">Choose owner…</option>{records.owners.map(o => <option key={o.id} value={o.id}>{o.legalName || "Unnamed owner"}</option>)}</select></FieldLabel><FieldLabel label="Prepare for representative"><select className="input" value={representativeId} onChange={e => setRepresentativeId(e.target.value)}><option value="">Choose representative…</option>{owner?.representatives.map(r => <option key={r.id} value={r.id}>{r.name || "Unnamed representative"}</option>)}</select></FieldLabel></div><Button type="button" variant="outline" disabled={!saved || !ownerId || !representativeId} onClick={exportSheet}><Download size={15} />Download preparation draft</Button>{!saved && <p className="form-note">Save owner & company records before preparing a draft.</p>}{error && <p role="status">{error}</p>}
  </div>;
}

function FinancialTermsEditor({ terms: f, company, agreements, onChange }: { terms: FinancialTerms; company: Company; agreements: CompanyAgreement[]; onChange: (value: FinancialTerms) => void }) {
  const patch = (value: Partial<FinancialTerms>) => onChange({ ...f, ...value });
  const total = distributionTotal(f);
  return <div className="form-stack"><p className={total === 100 ? styles.privateNotice : "notice warning"} role="status">Distribution total: {total}%. Confirmed terms require exactly 100%.</p>
    {f.distribution.map((row, i) => <div className="form-grid" key={row.memberId}><FieldLabel label={`Distribution % — ${company.members.find(m => m.id === row.memberId)?.name || "Unavailable member"}`}><Input type="number" min="0" max="100" step="0.001" value={row.percentage} onChange={e => patch({ status: "Draft", distribution: f.distribution.map((r, j) => i === j ? { ...r, percentage: e.target.value } : r) })} /></FieldLabel><Button type="button" variant="ghost" aria-label={`Remove distribution ${i + 1}`} onClick={() => patch({ status: "Draft", distribution: f.distribution.filter((_, j) => i !== j) })}>Remove distribution</Button></div>)}
    {company.members.some(member => !f.distribution.some(row => row.memberId === member.id)) && <p role="alert" className="notice warning">Add a distribution percentage for every owner. Enter 0% where applicable.</p>}
    <FieldLabel label="Add distribution member"><select className="input" value="" onChange={e => { if (e.target.value) patch({ status: "Draft", distribution: [...f.distribution, { memberId: e.target.value, percentage: "" }] }); }}><option value="">Choose member…</option>{company.members.filter(m => m.id && !f.distribution.some(r => r.memberId === m.id)).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></FieldLabel>
    <div className="form-grid"><FieldLabel label="Management / operating fee %"><Input type="number" min="0" max="100" step="0.001" value={f.managementFeePercentage} onChange={e => patch({ status: "Draft", managementFeePercentage: e.target.value })} /></FieldLabel><FieldLabel label="Financial terms effective date"><Input type="date" value={f.effectiveOn} onChange={e => patch({ status: "Draft", effectiveOn: e.target.value })} /></FieldLabel><FieldLabel label="Governing agreements"><select className="input" value={f.agreementMode} onChange={e => patch({ status: "Draft", agreementMode: e.target.value as FinancialTerms["agreementMode"], jvAgreementId: "", operatingAgreementId: "" })}><option value="single">One combined JV / Operating Agreement</option><option value="separate">Separate JV and Operating Agreements</option></select></FieldLabel></div>
    {(["jvAgreementId", ...(f.agreementMode === "separate" ? ["operatingAgreementId"] : [])] as const).map(key => <FieldLabel key={key} label={key === "operatingAgreementId" ? "Governing Operating Agreement" : "Governing JV / combined agreement"}><select className="input" value={f[key as "jvAgreementId" | "operatingAgreementId"]} onChange={e => patch({ status: "Draft", [key]: e.target.value })}><option value="">Choose agreement…</option>{agreements.map(a => <option key={a.id} value={a.id}>{a.title || "Untitled agreement"}{a.executed && a.documentIds.length ? " — executed original linked" : " — original / execution needed"}</option>)}</select></FieldLabel>)}
    <FieldLabel label="Financial terms status"><select className="input" value={f.status} onChange={e => patch({ status: e.target.value as FinancialTerms["status"] })}><option>Draft</option><option>Confirmed</option></select></FieldLabel><p className={styles.privateNotice}>Confirm after linking the executed governing agreement(s), entering the effective date and fee, and verifying a 100% distribution. Drafts may be saved for completion later.</p>
  </div>;
}
function ComplianceEditor({ value: c, originals, label, onChange }: { value: EntityCompliance; originals: VaultDoc[]; label: string; onChange: (value: EntityCompliance) => void }) {
  const patch = (value: Partial<EntityCompliance>) => onChange({ ...c, ...value });
  return <div className="form-stack"><p className={styles.privateNotice}>Dated private filing evidence. Changed verified dates update the matching Maintenance schedule; use Maintenance for future renewal dates and completion.</p><div className="form-grid"><FieldLabel label={`${label} current status`}><select className="input" value={c.status} onChange={e => patch({ status: e.target.value as EntityCompliance["status"] })}>{["Unknown", "Current", "Delinquent", "Inactive", "Dissolved", "Suspended"].map(v => <option key={v}>{v}</option>)}</select></FieldLabel><FieldLabel label={`${label} status checked on`}><Input type="date" value={c.statusCheckedOn} onChange={e => patch({ statusCheckedOn: e.target.value })} /></FieldLabel><FieldLabel label={`${label} annual report filed on`}><Input type="date" value={c.annualReportFiledOn} onChange={e => patch({ annualReportFiledOn: e.target.value })} /></FieldLabel><FieldLabel label={`${label} annual report notice due date`}><Input type="date" value={c.annualReportDueOn} onChange={e => patch({ annualReportDueOn: e.target.value })} /></FieldLabel></div>{!["Unknown", "Current"].includes(c.status) && <p role="alert" className="notice warning">This entity was recorded as not current. Review its dated evidence and the current Maintenance status.</p>}<DocumentLinks selected={c.documentIds} originals={originals} categories={label === "Owner entity" ? ["Formation", "Company records", "Partner entities"] : ["Formation", "Company records"]} onChange={documentIds => patch({ documentIds })} /></div>;
}
